"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, Loader2, Send } from "lucide-react";
import type { RoadmapChallenge } from "@/lib/roadmap/qa-do-zero";

type Attempt = { id: string; response: string; created_at: string };

export function RoadmapChallengeClient({ challenge }: { challenge: RoadmapChallenge }) {
  const [response, setResponse] = useState(""); const [attempts, setAttempts] = useState<Attempt[]>([]); const [state, setState] = useState<"loading" | "idle" | "saving">("loading"); const [error, setError] = useState("");
  useEffect(() => { fetch(`/api/v1/roadmap-attempts?challengeId=${encodeURIComponent(challenge.id)}`).then(async (result) => { const body = await result.json().catch(() => ({})); if (result.ok) setAttempts(body.data ?? []); else setError(body.error?.message ?? "Não foi possível carregar suas tentativas."); }).finally(() => setState("idle")); }, [challenge.id]);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setState("saving"); const result = await fetch("/api/v1/roadmap-attempts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ challengeId: challenge.id, response }) }); const body = await result.json().catch(() => ({})); if (!result.ok) { setError(body.error?.message ?? "Não foi possível salvar."); setState("idle"); return; } setAttempts((current) => [body.data, ...current]); setResponse(""); setState("idle"); }
  return <section className="mt-10 rounded-2xl border border-white/10 bg-[#171B21] p-6"><h2 className="text-xl font-black text-off-white">Sua tentativa</h2><p className="mt-2 text-sm leading-6 text-[#AAB2BC]">Não existe frase mágica. Explique sua decisão, mostre as evidências que usaria e assuma os trade-offs.</p><form className="mt-5" onSubmit={submit}><textarea value={response} onChange={(event) => setResponse(event.target.value)} required minLength={80} maxLength={12000} rows={10} placeholder="Escreva sua análise..." className="field w-full resize-y font-normal" /><div className="mt-3 flex items-center justify-between gap-3"><span className="text-xs text-[#8B949E]">Mínimo de 80 caracteres · {response.length}/12000</span><button disabled={state !== "idle"} className="inline-flex h-10 items-center gap-2 rounded-lg bg-mint px-4 text-xs font-black text-[#101319] disabled:opacity-60">{state === "saving" ? <Loader2 className="size-4 animate-spin" /> : <Send className="size-4" />} Salvar tentativa</button></div></form>{error && <p role="alert" className="mt-4 text-sm text-coral">{error}</p>}<div className="mt-8 border-t border-white/10 pt-5"><h3 className="text-sm font-bold text-off-white">Tentativas anteriores</h3>{state === "loading" ? <Loader2 className="mt-4 size-4 animate-spin text-mint" /> : attempts.length === 0 ? <p className="mt-3 text-sm text-[#8B949E]">Ainda não há tentativa salva.</p> : <div className="mt-4 grid gap-3">{attempts.map((attempt) => <article key={attempt.id} className="rounded-xl border border-white/[.08] bg-[#101319] p-4"><p className="flex items-center gap-2 text-xs font-bold text-mint"><CheckCircle2 className="size-4" />{new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(attempt.created_at))}</p><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[#D9DEE4]">{attempt.response}</p></article>)}</div>}</div></section>;
}
