"use client";

import { useMemo, useRef, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowLeft, BarChart3, Check, ChevronDown, ClipboardCheck, Download, FileSearch, FileText, FlaskConical, Link2, ListChecks, Loader2, LockKeyhole, PlayCircle, Plus, Printer, Save, ShieldAlert, Trash2 } from "lucide-react";
import { addTestStep, createRequirement, createRisk, createTestCase, deleteRequirement, deleteRisk, deleteTestCase, deleteTestStep, saveTestPlan, updateRequirement, updateRisk, updateTestCase } from "../actions";
import type { CoverageLink, Requirement, Risk, TestCase, TestPlan, TestStep } from "../types";

type Tab = "overview" | "requirements" | "risks" | "cases" | "plan" | "coverage" | "export";
const tabs: { id: Tab; label: string; icon: typeof FileText }[] = [
  { id: "overview", label: "Visão geral", icon: BarChart3 }, { id: "requirements", label: "Requisitos", icon: FileSearch }, { id: "risks", label: "Riscos", icon: ShieldAlert }, { id: "cases", label: "Casos", icon: ListChecks }, { id: "plan", label: "Plano", icon: ClipboardCheck }, { id: "coverage", label: "Cobertura", icon: Link2 }, { id: "export", label: "Exportar", icon: Download },
];

export function StudioClient({ workspaceId, projectId, project, planName, requirements, risks, testCases, steps, coverageLinks, initialPlan }: { workspaceId: string; projectId: string; project: { title: string; description: string; color: string; objective: string }; planName: string; requirements: Requirement[]; risks: Risk[]; testCases: TestCase[]; steps: TestStep[]; coverageLinks: CoverageLink[]; initialPlan: TestPlan }) {
  const [tab, setTab] = useState<Tab>("overview"); const [showForm, setShowForm] = useState(false); const [plan, setPlan] = useState(initialPlan); const [saveState, setSaveState] = useState<"idle" | "saving" | "saved" | "error">("idle"); const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const coveredRequirementIds = useMemo(() => new Set(coverageLinks.filter((item) => item.requirement_id).map((item) => item.requirement_id)), [coverageLinks]);
  const coveredRiskIds = useMemo(() => new Set(coverageLinks.filter((item) => item.risk_id).map((item) => item.risk_id)), [coverageLinks]);
  const criticalRisks = risks.filter((risk) => risk.score >= 16); const uncoveredCritical = criticalRisks.filter((risk) => !coveredRiskIds.has(risk.id)); const coveragePercent = requirements.length ? Math.round((coveredRequirementIds.size / requirements.length) * 100) : 0;

  function updatePlan(field: keyof TestPlan, value: string) { const next = { ...plan, [field]: value }; setPlan(next); setSaveState("saving"); if (timer.current) clearTimeout(timer.current); timer.current = setTimeout(() => { void saveTestPlan(workspaceId, next).then(() => setSaveState("saved")).catch(() => setSaveState("error")); }, 900); }
  function download(name: string, content: string, type: string) { const url = URL.createObjectURL(new Blob([content], { type })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); }
  function printReport(title: string, content: string) { const report = window.open("", "_blank"); if (!report) return; report.opener = null; const escape = (value: string) => value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[character] ?? character); report.document.write(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>${escape(title)}</title><style>body{max-width:900px;margin:48px auto;padding:0 24px;color:#171b21;font:15px/1.65 system-ui,sans-serif}pre{white-space:pre-wrap;font:inherit}@media print{body{margin:0}}</style></head><body><pre>${escape(content)}</pre><script>window.onload=()=>window.print()<\/script></body></html>`); report.document.close(); }
  const markdown = buildMarkdown(project.title, plan, requirements, risks, testCases, steps, coverageLinks);
  const casesCsv = ["Título,Tipo,Prioridade,Camada,Status,Resultado esperado", ...testCases.map((item) => [item.title, item.case_type, item.priority, item.layer, item.status, item.expected_result].map(csv).join(","))].join("\n");
  const paid = planName === "pro" || planName === "team";

  return <div className="mx-auto max-w-[90rem] px-4 py-8 sm:px-6"><header className="mx-auto max-w-7xl"><Link href="/lab/studio" className="inline-flex items-center gap-1.5 text-xs text-[#8B949E] hover:text-mint"><ArrowLeft className="size-3.5" /> Studios</Link><div className="mt-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><span className="rounded-full border border-mint/25 bg-mint/10 px-2 py-1 text-[9px] font-bold uppercase tracking-wider text-mint">{planName}</span><span className="text-xs text-[#69737E]">Produto 02 · Test Design Studio</span></div><h1 className="mt-3 text-3xl font-black text-off-white sm:text-4xl">{project.title}</h1><p className="mt-2 max-w-2xl text-sm text-[#8B949E]">{project.objective || project.description || "Estruture a estratégia de qualidade deste projeto."}</p></div><div className="flex flex-col items-stretch gap-3"><div className="grid grid-cols-3 gap-2 text-center"><Mini value={requirements.length} label="Requisitos" /><Mini value={risks.length} label="Riscos" /><Mini value={testCases.length} label="Casos" /></div><Link href={`/lab/execution/${projectId}`} className="inline-flex h-9 items-center justify-center gap-2 rounded-lg bg-neon px-4 text-xs font-black text-[#101319]"><PlayCircle className="size-4" />Executar casos</Link></div></div></header>

    <div className="mx-auto mt-8 max-w-7xl overflow-x-auto border-b border-white/10"><nav className="flex min-w-max gap-1">{tabs.map(({ id, label, icon: Icon }) => <button key={id} type="button" onClick={() => { setTab(id); setShowForm(false); }} className={`inline-flex items-center gap-2 border-b-2 px-3 py-3 text-xs font-bold transition ${tab === id ? "border-mint text-mint" : "border-transparent text-[#69737E] hover:text-off-white"}`}><Icon className="size-3.5" />{label}</button>)}</nav></div>

    <main className="mx-auto mt-8 max-w-7xl">
      {tab === "overview" && <Overview requirements={requirements} risks={risks} testCases={testCases} coveragePercent={coveragePercent} uncoveredCritical={uncoveredCritical.length} onNavigate={setTab} />}
      {tab === "requirements" && <Requirements workspaceId={workspaceId} requirements={requirements} canCreate={planName !== "free" || requirements.length < 3} showForm={showForm} setShowForm={setShowForm} />}
      {tab === "risks" && <Risks workspaceId={workspaceId} requirements={requirements} risks={risks} showForm={showForm} setShowForm={setShowForm} />}
      {tab === "cases" && <Cases workspaceId={workspaceId} requirements={requirements} risks={risks} testCases={testCases} steps={steps} coverageLinks={coverageLinks} canCreate={planName !== "free" || testCases.length < 20} showForm={showForm} setShowForm={setShowForm} />}
      {tab === "plan" && <PlanEditor plan={plan} update={updatePlan} state={saveState} />}
      {tab === "coverage" && <Coverage requirements={requirements} risks={risks} testCases={testCases} links={coverageLinks} />}
      {tab === "export" && <ExportPanel paid={paid} markdown={() => download(`${slug(project.title)}-plano-de-teste.md`, markdown, "text/markdown;charset=utf-8")} csv={() => download(`${slug(project.title)}-casos.csv`, `\uFEFF${casesCsv}`, "text/csv;charset=utf-8")} print={() => printReport(project.title, markdown)} />}
    </main>
    <p className="mx-auto mt-10 max-w-7xl text-center text-[10px] text-[#56606B]">Projeto {projectId} · BDD reservado para integração futura com o gerador Python.</p>
  </div>;
}

function Overview({ requirements, risks, testCases, coveragePercent, uncoveredCritical, onNavigate }: { requirements: Requirement[]; risks: Risk[]; testCases: TestCase[]; coveragePercent: number; uncoveredCritical: number; onNavigate: (tab: Tab) => void }) { const issues = [requirements.filter((item) => !item.acceptance_criteria).length, risks.filter((item) => item.score >= 16).length, testCases.filter((item) => !item.expected_result).length]; return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Cobertura de requisitos" value={`${coveragePercent}%`} tone={coveragePercent === 100 ? "mint" : "coral"} /><Metric label="Riscos críticos sem teste" value={String(uncoveredCritical)} tone={uncoveredCritical ? "coral" : "mint"} /><Metric label="Casos prontos" value={String(testCases.filter((item) => item.status === "ready").length)} tone="neon" /><Metric label="Perguntas em aberto" value={String(requirements.filter((item) => item.open_questions).length)} tone="neutral" /></div><section className="rounded-2xl border border-white/10 bg-[#171B21] p-5"><h2 className="font-bold text-off-white">Sinais de qualidade</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><Signal count={issues[0]} text="requisitos sem critério de aceite" action={() => onNavigate("requirements")} /><Signal count={issues[1]} text="riscos com score crítico" action={() => onNavigate("risks")} /><Signal count={issues[2]} text="casos sem resultado esperado" action={() => onNavigate("cases")} /></div></section><section className="rounded-2xl border border-neon/20 bg-neon/[0.04] p-5"><FlaskConical className="size-5 text-neon" /><h2 className="mt-4 font-bold text-off-white">Integração BDD preservada</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#8B949E]">O Studio fornece requisitos, riscos e casos estruturados. Seu gerador Python poderá consumir esses artefatos depois, sem existir uma implementação BDD paralela aqui.</p></section></div>; }

function Requirements({ workspaceId, requirements, canCreate, showForm, setShowForm }: { workspaceId: string; requirements: Requirement[]; canCreate: boolean; showForm: boolean; setShowForm: (value: boolean) => void }) { return <section><Header title="Requisitos" description={canCreate ? "Regras, critérios e perguntas que orientam o teste." : "Limite Free de três requisitos atingido."} add={canCreate ? () => setShowForm(!showForm) : undefined} />{showForm && <RequirementForm workspaceId={workspaceId} action={createRequirement} />}<div className="mt-5 space-y-4">{requirements.map((item) => <details key={item.id} className="group rounded-xl border border-white/10 bg-[#171B21]"><summary className="flex cursor-pointer list-none items-center gap-4 p-5"><span className={`size-2 rounded-full ${item.status === "approved" ? "bg-neon" : item.status === "refinement" ? "bg-mint" : "bg-coral"}`} /><div className="min-w-0 flex-1"><h3 className="truncate font-bold text-off-white">{item.title}</h3><p className="mt-1 line-clamp-1 text-xs text-[#8B949E]">{item.description || "Sem descrição"}</p></div><span className="text-[9px] uppercase text-[#69737E]">{item.status}</span><ChevronDown className="size-4 text-[#69737E] transition group-open:rotate-180" /></summary><div className="border-t border-white/[0.08] p-5"><RequirementForm workspaceId={workspaceId} requirement={item} action={updateRequirement} /><form action={deleteRequirement} className="mt-3"><input type="hidden" name="id" value={item.id} /><button className="inline-flex items-center gap-1.5 text-xs text-[#69737E] hover:text-coral"><Trash2 className="size-3.5" /> Excluir requisito</button></form></div></details>)}</div>{!requirements.length && <Empty text="Cadastre o primeiro requisito para começar a rastreabilidade." />}</section>; }
function RequirementForm({ workspaceId, requirement, action }: { workspaceId: string; requirement?: Requirement; action: (formData: FormData) => void | Promise<void> }) { return <form action={action} className="space-y-3 rounded-xl border border-mint/15 bg-mint/[0.025] p-4"><input type="hidden" name="workspace_id" value={workspaceId} />{requirement && <input type="hidden" name="id" value={requirement.id} />}<div className="grid gap-3 sm:grid-cols-[1fr_auto]"><input name="title" required maxLength={140} defaultValue={requirement?.title} placeholder="Título do requisito" className="field" /><select name="status" defaultValue={requirement?.status ?? "draft"} className="field"><option value="draft">Rascunho</option><option value="refinement">Refinamento</option><option value="approved">Aprovado</option></select></div><textarea name="description" defaultValue={requirement?.description} rows={2} placeholder="Descrição e contexto" className="field w-full" /><div className="grid gap-3 md:grid-cols-2"><textarea name="acceptance_criteria" defaultValue={requirement?.acceptance_criteria} rows={3} placeholder="Critérios de aceite · um por linha" className="field" /><textarea name="business_rules" defaultValue={requirement?.business_rules} rows={3} placeholder="Regras de negócio" className="field" /></div><textarea name="open_questions" defaultValue={requirement?.open_questions} rows={2} placeholder="Perguntas e ambiguidades em aberto" className="field w-full" /><button className="inline-flex h-9 items-center gap-2 rounded-lg bg-mint px-4 text-xs font-black text-[#101319]"><Save className="size-3.5" />{requirement ? "Salvar alterações" : "Criar requisito"}</button></form>; }

function Risks({ workspaceId, requirements, risks, showForm, setShowForm }: { workspaceId: string; requirements: Requirement[]; risks: Risk[]; showForm: boolean; setShowForm: (value: boolean) => void }) { return <section><Header title="Matriz de riscos" description="Probabilidade × impacto define a ordem de investigação." add={() => setShowForm(!showForm)} />{showForm && <RiskForm workspaceId={workspaceId} requirements={requirements} />}<div className="mt-5 overflow-x-auto rounded-xl border border-white/10"><table className="w-full min-w-[680px] text-left text-xs"><thead className="bg-white/[0.035] text-[#69737E]"><tr><th className="p-3">Risco</th><th>Categoria</th><th>P</th><th>I</th><th>Score</th><th>Mitigação</th><th /></tr></thead><tbody>{risks.map((risk) => <tr key={risk.id} className="border-t border-white/[0.07]"><td className="p-3 font-semibold text-off-white">{risk.title}</td><td className="text-[#8B949E]">{risk.category}</td><td>{risk.probability}</td><td>{risk.impact}</td><td><span className={`rounded px-2 py-1 font-black ${risk.score >= 16 ? "bg-coral/15 text-coral" : risk.score >= 9 ? "bg-[#F0C040]/15 text-[#F0C040]" : "bg-mint/15 text-mint"}`}>{risk.score}</span></td><td className="max-w-xs truncate text-[#8B949E]">{risk.mitigation || "—"}</td><td><form action={deleteRisk}><input type="hidden" name="id" value={risk.id} /><button className="text-[#69737E] hover:text-coral" aria-label={`Excluir ${risk.title}`}><Trash2 className="size-3.5" /></button></form></td></tr>)}</tbody></table></div><div className="mt-4 space-y-2">{risks.map((risk) => <details key={risk.id} className="group rounded-xl border border-white/[0.08]"><summary className="flex cursor-pointer list-none items-center justify-between p-3 text-xs text-[#8B949E]"><span>Editar: <strong className="text-off-white">{risk.title}</strong></span><ChevronDown className="size-3.5 transition group-open:rotate-180" /></summary><div className="border-t border-white/[0.08] p-3"><RiskForm workspaceId={workspaceId} requirements={requirements} risk={risk} /></div></details>)}</div>{!risks.length && <Empty text="Mapeie riscos antes de decidir profundidade e prioridade dos testes." />}</section>; }

function RiskForm({ workspaceId, requirements, risk }: { workspaceId: string; requirements: Requirement[]; risk?: Risk }) { return <form action={risk ? updateRisk : createRisk} className="grid gap-3 rounded-xl border border-coral/15 bg-coral/[0.025] p-4 md:grid-cols-2"><input type="hidden" name="workspace_id" value={workspaceId} />{risk && <input type="hidden" name="id" value={risk.id} />}<input name="title" required maxLength={160} defaultValue={risk?.title} placeholder="Risco identificado" className="field md:col-span-2" /><select name="requirement_id" defaultValue={risk?.requirement_id ?? ""} className="field"><option value="">Sem requisito vinculado</option>{requirements.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><select name="category" defaultValue={risk?.category ?? "produto"} className="field"><option value="produto">Produto</option><option value="negocio">Negócio</option><option value="dados">Dados</option><option value="seguranca">Segurança</option><option value="performance">Performance</option><option value="acessibilidade">Acessibilidade</option><option value="integracao">Integração</option></select><label className="text-xs text-[#8B949E]">Probabilidade<select name="probability" defaultValue={risk?.probability ?? 3} className="field mt-1 w-full">{[1,2,3,4,5].map((n) => <option key={n}>{n}</option>)}</select></label><label className="text-xs text-[#8B949E]">Impacto<select name="impact" defaultValue={risk?.impact ?? 3} className="field mt-1 w-full">{[1,2,3,4,5].map((n) => <option key={n}>{n}</option>)}</select></label>{risk && <select name="status" defaultValue={risk.status} className="field"><option value="open">Aberto</option><option value="mitigated">Mitigado</option><option value="accepted">Aceito</option></select>}<textarea name="mitigation" defaultValue={risk?.mitigation} rows={2} placeholder="Mitigação ou abordagem de teste" className="field md:col-span-2" /><button className="h-9 rounded-lg bg-coral px-4 text-xs font-black text-[#101319] md:justify-self-start">{risk ? "Salvar risco" : "Adicionar risco"}</button></form>; }

function Cases({ workspaceId, requirements, risks, testCases, steps, coverageLinks, canCreate, showForm, setShowForm }: { workspaceId: string; requirements: Requirement[]; risks: Risk[]; testCases: TestCase[]; steps: TestStep[]; coverageLinks: CoverageLink[]; canCreate: boolean; showForm: boolean; setShowForm: (value: boolean) => void }) {
  return <section><Header title="Casos de teste" description={canCreate ? "Casos rastreáveis com dados, passos e resultados." : "Limite Free de vinte casos atingido."} add={canCreate ? () => setShowForm(!showForm) : undefined} />
    {showForm && <TestCaseForm workspaceId={workspaceId} requirements={requirements} risks={risks} />}
    <div className="mt-5 space-y-3">{testCases.map((testCase) => { const caseSteps = steps.filter((item) => item.test_case_id === testCase.id); const links = coverageLinks.filter((item) => item.test_case_id === testCase.id); return <details key={testCase.id} className="group rounded-xl border border-white/10 bg-[#171B21]"><summary className="flex cursor-pointer list-none items-center gap-3 p-4"><span className={`rounded px-2 py-1 text-[9px] font-bold uppercase ${testCase.priority === "critical" ? "bg-coral/15 text-coral" : "bg-white/5 text-[#8B949E]"}`}>{testCase.priority}</span><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-bold text-off-white">{testCase.title}</h3><p className="mt-1 text-[10px] uppercase text-[#69737E]">{testCase.case_type} · {testCase.layer} · {links.length} vínculo(s)</p></div><ChevronDown className="size-4 text-[#69737E] transition group-open:rotate-180" /></summary><div className="border-t border-white/[0.08] p-4"><div className="grid gap-3 text-xs md:grid-cols-2"><Info label="Objetivo" value={testCase.objective} /><Info label="Pré-condições" value={testCase.preconditions} /><Info label="Dados" value={testCase.test_data} /><Info label="Resultado esperado" value={testCase.expected_result} /></div><ol className="mt-4 space-y-2">{caseSteps.map((step) => <li key={step.id} className="grid items-start gap-2 rounded-lg bg-white/[0.03] p-3 text-xs sm:grid-cols-[2rem_1fr_1fr_auto]"><span className="font-mono text-mint">{step.position}.</span><span>{step.action}</span><span className="text-[#8B949E]">{step.expected_result || "Sem resultado do passo"}</span><form action={deleteTestStep}><input type="hidden" name="id" value={step.id} /><button aria-label={`Excluir passo ${step.position}`} className="text-[#69737E] hover:text-coral"><Trash2 className="size-3.5" /></button></form></li>)}</ol><form action={addTestStep} className="mt-3 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input type="hidden" name="test_case_id" value={testCase.id} /><input name="action" required placeholder="Novo passo" className="field" /><input name="expected_result" placeholder="Resultado esperado" className="field" /><button className="rounded-lg border border-mint/25 px-3 text-xs font-bold text-mint">Adicionar</button></form><details className="mt-4 rounded-lg border border-white/[0.08]"><summary className="cursor-pointer list-none p-3 text-xs font-bold text-[#8B949E]">Editar caso e vínculos</summary><div className="border-t border-white/[0.08] p-3"><TestCaseForm workspaceId={workspaceId} requirements={requirements} risks={risks} testCase={testCase} links={links} /></div></details><form action={deleteTestCase} className="mt-4"><input type="hidden" name="id" value={testCase.id} /><button className="inline-flex items-center gap-1.5 text-xs text-[#69737E] hover:text-coral"><Trash2 className="size-3.5" /> Excluir caso</button></form></div></details>; })}</div>
    {!testCases.length && <Empty text="Crie casos a partir dos riscos e critérios que realmente importam." />}
  </section>;
}

function TestCaseForm({ workspaceId, requirements, risks, testCase, links = [] }: { workspaceId: string; requirements: Requirement[]; risks: Risk[]; testCase?: TestCase; links?: CoverageLink[] }) {
  const link = links[0];
  return <form action={testCase ? updateTestCase : createTestCase} className="mt-4 space-y-3 rounded-xl border border-neon/15 bg-neon/[0.025] p-4"><input type="hidden" name="workspace_id" value={workspaceId} />{testCase && <input type="hidden" name="id" value={testCase.id} />}<input name="title" required maxLength={180} defaultValue={testCase?.title} placeholder="Título do caso" className="field w-full" /><div className="grid gap-3 md:grid-cols-3"><select name="case_type" defaultValue={testCase?.case_type ?? "positive"} className="field"><option value="positive">Positivo</option><option value="negative">Negativo</option><option value="boundary">Limite</option><option value="regression">Regressão</option><option value="exploratory">Exploratório</option></select><select name="priority" defaultValue={testCase?.priority ?? "medium"} className="field"><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option><option value="critical">Crítica</option></select><select name="layer" defaultValue={testCase?.layer ?? "ui"} className="field"><option value="ui">UI</option><option value="api">API</option><option value="integration">Integração</option><option value="e2e">E2E</option><option value="unit">Unitário</option><option value="manual">Manual</option></select></div><div className="grid gap-3 md:grid-cols-2"><textarea name="objective" rows={2} defaultValue={testCase?.objective} placeholder="Objetivo" className="field" /><textarea name="preconditions" rows={2} defaultValue={testCase?.preconditions} placeholder="Pré-condições" className="field" /><textarea name="test_data" rows={2} defaultValue={testCase?.test_data} placeholder="Dados de teste" className="field" /><textarea name="expected_result" rows={2} defaultValue={testCase?.expected_result} placeholder="Resultado final esperado" className="field" /></div><div className="grid gap-3 md:grid-cols-2"><select name="requirement_id" defaultValue={link?.requirement_id ?? ""} className="field"><option value="">Sem requisito vinculado</option>{requirements.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><select name="risk_id" defaultValue={link?.risk_id ?? ""} className="field"><option value="">Sem risco vinculado</option>{risks.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></div>{testCase ? <select name="status" defaultValue={testCase.status} className="field"><option value="draft">Rascunho</option><option value="ready">Pronto</option><option value="deprecated">Descontinuado</option></select> : <div className="grid gap-3 md:grid-cols-2"><input name="step_action" placeholder="Primeiro passo" className="field" /><input name="step_expected" placeholder="Resultado do passo" className="field" /></div>}<button className="h-9 rounded-lg bg-neon px-4 text-xs font-black text-[#101319]">{testCase ? "Salvar caso" : "Criar caso"}</button></form>;
}

function PlanEditor({ plan, update, state }: { plan: TestPlan; update: (field: keyof TestPlan, value: string) => void; state: string }) { const fields: { key: keyof TestPlan; label: string; placeholder: string }[] = [{ key:"objective",label:"Objetivo",placeholder:"O que este plano precisa demonstrar?"},{key:"scope",label:"Escopo",placeholder:"Fluxos, plataformas e comportamentos cobertos"},{key:"out_of_scope",label:"Fora de escopo",placeholder:"O que não será validado nesta rodada"},{key:"strategy",label:"Estratégia",placeholder:"Abordagens, camadas e tipos de teste"},{key:"environments",label:"Ambientes",placeholder:"Ambientes, dispositivos e configurações"},{key:"tools",label:"Ferramentas",placeholder:"Ferramentas de apoio e automação"},{key:"entry_criteria",label:"Critérios de entrada",placeholder:"Condições para iniciar"},{key:"exit_criteria",label:"Critérios de saída",placeholder:"Condições para encerrar"},{key:"dependencies",label:"Dependências e riscos",placeholder:"Bloqueios, integrações e premissas"},{key:"responsibilities",label:"Responsáveis",placeholder:"Papéis e responsabilidades"},{key:"schedule",label:"Cronograma",placeholder:"Janelas, marcos e timeboxes"}]; return <section><div className="flex items-end justify-between"><div><h2 className="text-xl font-black text-off-white">Plano de teste</h2><p className="mt-1 text-sm text-[#8B949E]">Salvamento automático após cada alteração.</p></div><span className={`inline-flex items-center gap-1.5 text-xs ${state === "error" ? "text-coral" : "text-mint"}`}>{state === "saving" ? <Loader2 className="size-3.5 animate-spin" /> : state === "saved" ? <Check className="size-3.5" /> : null}{state === "saving" ? "Salvando" : state === "saved" ? "Salvo" : state === "error" ? "Erro ao salvar" : ""}</span></div><div className="mt-5 grid gap-4 md:grid-cols-2">{fields.map((field) => <label key={field.key} className={`block text-xs font-bold text-[#AAB2BC] ${["strategy","scope","out_of_scope"].includes(field.key) ? "md:col-span-2" : ""}`}>{field.label}<textarea value={plan[field.key]} onChange={(event) => update(field.key, event.target.value)} rows={field.key === "strategy" ? 5 : 3} placeholder={field.placeholder} className="field mt-2 w-full resize-y font-normal" /></label>)}</div></section>; }

function Coverage({ requirements, risks, testCases, links }: { requirements: Requirement[]; risks: Risk[]; testCases: TestCase[]; links: CoverageLink[] }) { return <section><h2 className="text-xl font-black text-off-white">Rastreabilidade e cobertura</h2><p className="mt-1 text-sm text-[#8B949E]">Cobertura é calculada pelos vínculos criados nos casos de teste.</p><div className="mt-5 overflow-x-auto rounded-xl border border-white/10"><table className="w-full min-w-[720px] text-left text-xs"><thead className="bg-white/[0.035] text-[#69737E]"><tr><th className="p-3">Requisito</th><th>Riscos</th><th>Casos vinculados</th><th>Cobertura</th></tr></thead><tbody>{requirements.map((requirement) => { const relatedRisks = risks.filter((risk) => risk.requirement_id === requirement.id); const caseIds = new Set(links.filter((link) => link.requirement_id === requirement.id || (link.risk_id && relatedRisks.some((risk) => risk.id === link.risk_id))).map((link) => link.test_case_id)); return <tr key={requirement.id} className="border-t border-white/[0.07]"><td className="p-3 font-semibold text-off-white">{requirement.title}</td><td>{relatedRisks.length}</td><td>{caseIds.size}</td><td><span className={`rounded px-2 py-1 font-bold ${caseIds.size ? "bg-mint/15 text-mint" : "bg-coral/15 text-coral"}`}>{caseIds.size ? "Coberto" : "Sem cobertura"}</span></td></tr>; })}</tbody></table></div>{!requirements.length && <Empty text="A matriz aparece quando houver requisitos cadastrados." />}<div className="mt-6 grid gap-3 md:grid-cols-2">{risks.filter((risk) => risk.score >= 16 && !links.some((link) => link.risk_id === risk.id)).map((risk) => <div key={risk.id} className="flex gap-3 rounded-xl border border-coral/20 bg-coral/[0.04] p-4"><AlertTriangle className="size-4 shrink-0 text-coral" /><div><p className="text-sm font-bold text-off-white">Risco crítico sem caso</p><p className="mt-1 text-xs text-[#8B949E]">{risk.title} · score {risk.score}</p></div></div>)}</div><p className="mt-6 text-xs text-[#69737E]">{testCases.length} casos no total · {links.length} vínculos de cobertura.</p></section>; }
function ExportPanel({ paid, markdown, csv, print }: { paid: boolean; markdown: () => void; csv: () => void; print: () => void }) { return <section><h2 className="text-xl font-black text-off-white">Exportar artefatos</h2><p className="mt-1 text-sm text-[#8B949E]">Arquivos gerados localmente no navegador; nenhum conteúdo é enviado para terceiros.</p><div className="mt-5 grid gap-4 md:grid-cols-3"><button type="button" onClick={markdown} className="rounded-2xl border border-white/10 bg-[#171B21] p-6 text-left hover:border-mint/30"><FileText className="size-5 text-mint" /><h3 className="mt-6 font-bold text-off-white">Plano completo em Markdown</h3><p className="mt-2 text-xs leading-5 text-[#8B949E]">Requisitos, riscos, casos, passos, plano e rastreabilidade em um documento.</p></button><button type="button" onClick={csv} className="rounded-2xl border border-white/10 bg-[#171B21] p-6 text-left hover:border-neon/30"><Download className="size-5 text-neon" /><h3 className="mt-6 font-bold text-off-white">Casos em CSV</h3><p className="mt-2 text-xs leading-5 text-[#8B949E]">Planilha compatível com Excel, Google Sheets e ferramentas de gestão.</p></button><button type="button" onClick={paid ? print : undefined} disabled={!paid} className="rounded-2xl border border-white/10 bg-[#171B21] p-6 text-left enabled:hover:border-coral/30 disabled:cursor-not-allowed disabled:opacity-55">{paid ? <Printer className="size-5 text-coral" /> : <LockKeyhole className="size-5 text-[#69737E]" />}<h3 className="mt-6 font-bold text-off-white">Relatório para impressão</h3><p className="mt-2 text-xs leading-5 text-[#8B949E]">{paid ? "Abra uma versão limpa para imprimir ou salvar como PDF." : "Disponível nos planos Pro e Team."}</p></button></div></section>; }

function Header({ title, description, add }: { title: string; description: string; add?: () => void }) { return <div className="flex items-end justify-between gap-4"><div><h2 className="text-xl font-black text-off-white">{title}</h2><p className="mt-1 text-sm text-[#8B949E]">{description}</p></div>{add && <button type="button" onClick={add} className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-mint/25 px-3 text-xs font-bold text-mint hover:bg-mint/10"><Plus className="size-3.5" />Adicionar</button>}</div>; }
function Metric({ label, value, tone }: { label: string; value: string; tone: "mint" | "coral" | "neon" | "neutral" }) { const color = tone === "coral" ? "text-coral" : tone === "neon" ? "text-neon" : tone === "mint" ? "text-mint" : "text-off-white"; return <div className="rounded-xl border border-white/10 bg-[#171B21] p-4"><p className={`text-2xl font-black ${color}`}>{value}</p><p className="mt-1 text-xs text-[#69737E]">{label}</p></div>; }
function Signal({ count, text, action }: { count: number; text: string; action: () => void }) { return <button type="button" onClick={action} className="flex items-center gap-3 rounded-xl bg-white/[0.03] p-4 text-left hover:bg-white/[0.05]"><span className={`flex size-8 items-center justify-center rounded-full text-xs font-black ${count ? "bg-coral/15 text-coral" : "bg-mint/15 text-mint"}`}>{count}</span><span className="text-xs leading-5 text-[#AAB2BC]">{text}</span></button>; }
function Mini({ value, label }: { value: number; label: string }) { return <div className="rounded-lg border border-white/10 px-3 py-2"><p className="font-black text-off-white">{value}</p><p className="text-[9px] text-[#69737E]">{label}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="mt-5 rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-[#69737E]">{text}</div>; }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-[9px] font-bold uppercase tracking-wider text-[#69737E]">{label}</p><p className="mt-1 whitespace-pre-wrap leading-5 text-[#AAB2BC]">{value || "—"}</p></div>; }
function csv(value: string) { return `"${String(value ?? "").replaceAll('"', '""')}"`; }
function slug(value: string) { return value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "studio"; }
function buildMarkdown(title: string, plan: TestPlan, requirements: Requirement[], risks: Risk[], cases: TestCase[], steps: TestStep[], links: CoverageLink[]) { return [`# Plano de Teste — ${title}`,"",`## Objetivo\n${plan.objective || "Não definido."}`,`## Escopo\n${plan.scope || "Não definido."}`,`## Fora de escopo\n${plan.out_of_scope || "Não definido."}`,`## Estratégia\n${plan.strategy || "Não definida."}`,`## Ambientes e ferramentas\n${plan.environments}\n\n${plan.tools}`,`## Critérios de entrada\n${plan.entry_criteria}`,`## Critérios de saída\n${plan.exit_criteria}`,`## Dependências\n${plan.dependencies}`,`## Responsáveis e cronograma\n${plan.responsibilities}\n\n${plan.schedule}`,"## Requisitos",...requirements.flatMap((item) => [`### ${item.title}`,item.description,`**Critérios:**\n${item.acceptance_criteria}`,`**Regras:**\n${item.business_rules}`,`**Perguntas:**\n${item.open_questions}`,""]),"## Riscos",...risks.map((item) => `- **${item.title}** — ${item.category}, P${item.probability} × I${item.impact} = ${item.score}. ${item.mitigation}`),"","## Casos de teste",...cases.flatMap((item) => { const caseSteps = steps.filter((step) => step.test_case_id === item.id); const caseLinks = links.filter((link) => link.test_case_id === item.id); return [`### ${item.title}`,`Tipo: ${item.case_type} · Prioridade: ${item.priority} · Camada: ${item.layer}`,`**Objetivo:** ${item.objective}`,`**Pré-condições:** ${item.preconditions}`,`**Dados:** ${item.test_data}`,...caseSteps.map((step) => `${step.position}. ${step.action} → ${step.expected_result}`),`**Resultado esperado:** ${item.expected_result}`,`Vínculos: ${caseLinks.length}`,""]; })].join("\n\n"); }
