// Packs de regressão dos ambientes de prática.
//
// A matriz é a mesma para os quatro ambientes — 35 verificações, das camadas de
// UI e validação até acessibilidade, resiliência, segurança e governança — mas
// cada cenário é escrito contra o ambiente de verdade: a pré-condição fala da
// massa de teste do seed, os passos citam o registro que existe lá e o oráculo
// diz o que aquele domínio deveria fazer.
//
// `bugId` liga o cenário ao desvio plantado que costuma cair nele. É usado no
// modo instrutor; o aluno não vê essa relação.
//
// Módulo puro: a home lê daqui para calcular cobertura e o executor de packs
// renderiza daqui.

import { practiceApps, type PracticeAppId } from "./product/apps";

export type RegressionScenario = {
  id: string;
  /** Posição na matriz de 35 verificações, igual nos quatro ambientes. */
  number: number;
  title: string;
  layer: string;
  precondition: string;
  steps: string[];
  expected: string;
  /** Onde executar: rota do ambiente, com âncora da seção quando houver. */
  route: string;
  /** Desvio plantado que este cenário costuma pegar. */
  bugId?: string;
};

type Draft = {
  title: string;
  layer: string;
  precondition: string;
  steps: string[];
  expected: string;
  at?: string;
  bugId?: string;
};

// Pré-condição padrão: todo cenário parte da massa restaurada, senão o
// resultado deixa de ser repetível.
const fresh = "Massa de teste restaurada e perfil de teste Administrador ativo.";

const financas: Draft[] = [
  { title: "Acesso inicial", layer: "UI", precondition: "Sessão nova, sem massa criada ainda.", steps: ["Abra /financas pela primeira vez com a conta recém-criada.", "Observe se a massa inicial é criada sozinha.", "Confira os três cartões do topo contra a lista de lançamentos."], expected: "O ambiente abre com a massa do seed e saldo, receitas e despesas coerentes com a lista.", at: "" },
  { title: "Carregamento da página", layer: "UI", precondition: fresh, steps: ["Atualize a página com o cache desabilitado.", "Observe o intervalo até os dados aparecerem.", "Confira se algum bloco fica vazio ou pisca com valor errado antes de estabilizar."], expected: "Os dados chegam prontos do servidor, sem estado intermediário exibindo total zerado.", at: "" },
  { title: "Estado vazio", layer: "UI", precondition: fresh, steps: ["Exclua todos os lançamentos, um a um.", "Observe a lista, os totais e o bloco de gastos por categoria.", "Restaure a massa de teste ao final."], expected: "A lista mostra a mensagem de lista vazia, os totais vão a R$ 0,00 e nada quebra.", at: "#lancamentos" },
  { title: "Busca por texto", layer: "UI", precondition: fresh, steps: ["Busque por \"Mercado\" no campo de busca de lançamentos.", "Busque por \"alimentacao\", sem acento e em minúsculas.", "Busque por \"xyz\", que não existe."], expected: "A busca ignora acento e caixa, encontra pela descrição e pela categoria, e informa quando não há resultado.", at: "#lancamentos" },
  { title: "Filtro combinado", layer: "UI", precondition: fresh, steps: ["Filtre por tipo Despesa e categoria Moradia.", "Confira o contador de registros exibido.", "Limpe os filtros pelo botão."], expected: "Os dois filtros se somam (Aluguel e Internet), o contador acompanha e limpar devolve a lista completa.", at: "#lancamentos" },
  { title: "Ordenação", layer: "UI", precondition: fresh, steps: ["Ordene por Valor (maior).", "Ordene por Data (mais antiga).", "Volte para Data (mais recente)."], expected: "Cada ordenação reordena a lista inteira, não só a página visível, e não perde nenhum registro.", at: "#lancamentos" },
  { title: "Paginação", layer: "UI", precondition: fresh, steps: ["Ajuste itens por página para 5.", "Navegue até a última página e volte.", "Aplique um filtro estando na página 2."], expected: "A navegação respeita o total de páginas e filtrar volta para a primeira página, sem tela vazia.", at: "#lancamentos" },
  { title: "Criar registro válido", layer: "Fluxo", precondition: fresh, steps: ["Cadastre a despesa \"Academia\", R$ 120,00, categoria Saúde, data 2026-08-16.", "Confira a linha criada na lista.", "Confira o total de despesas e o uso do orçamento de Saúde."], expected: "O lançamento aparece na lista, o total de despesas sobe R$ 120,00 e o orçamento de Saúde reflete o gasto.", at: "#lancamentos" },
  { title: "Campo obrigatório", layer: "Validação", precondition: fresh, steps: ["Envie o formulário de lançamento vazio.", "Preencha só a descrição e envie de novo.", "Confira a mensagem apresentada em cada campo."], expected: "Cada campo obrigatório recebe \"Campo obrigatório.\", nada é gravado e o foco continua utilizável.", at: "#lancamentos" },
  { title: "Formato inválido", layer: "Validação", precondition: fresh, steps: ["Informe \"abc\" no valor e envie.", "Informe uma data fora do formato AAAA-MM-DD.", "Repita enviando direto para a API por DevTools."], expected: "A interface e a API recusam com a mesma mensagem de formato; a API responde 422 com o erro por campo.", at: "#lancamentos" },
  { title: "Valor limite", layer: "Validação", precondition: fresh, steps: ["Cadastre um lançamento de R$ 0,00 e outro de R$ 9.999.999,00.", "Tente R$ -1,00 e R$ 10.000.000,00.", "Confira se o saldo do topo bate com a soma da lista depois de cada operação."], expected: "Zero e o máximo são aceitos, valores fora do intervalo são recusados e o saldo continua batendo com a lista.", at: "#lancamentos", bugId: "financas.total-ignora-recorrente" },
  { title: "Duplicidade", layer: "Validação", precondition: fresh, steps: ["Cadastre um orçamento para a categoria Moradia, que já existe.", "Repita usando \" moradia \", com espaços e minúsculas.", "Cadastre uma conta com o nome \"Poupança\", que já existe."], expected: "As três tentativas são recusadas com aviso de duplicidade no campo, sem criar registro repetido.", at: "#orcamentos" },
  { title: "Cancelar operação", layer: "Fluxo", precondition: fresh, steps: ["Comece a editar o lançamento Aluguel e altere o valor.", "Clique em Cancelar.", "Peça a exclusão de um lançamento e cancele na confirmação."], expected: "Nenhuma das duas operações canceladas altera os dados nem os totais.", at: "#lancamentos" },
  { title: "Editar registro", layer: "Fluxo", precondition: fresh, steps: ["Edite o lançamento Mercado para R$ 530,90.", "Salve e confira a linha e o total de despesas.", "Recarregue a página."], expected: "A alteração persiste depois do recarregamento e o total de despesas acompanha a diferença.", at: "#lancamentos" },
  { title: "Excluir/cancelar registro", layer: "Fluxo", precondition: fresh, steps: ["Peça a exclusão do lançamento Farmácia.", "Confirme na segunda etapa.", "Confira lista, total de despesas e gastos por categoria."], expected: "A exclusão só acontece após a confirmação e some da lista e dos três cálculos.", at: "#lancamentos" },
  { title: "Persistência", layer: "Dados", precondition: fresh, steps: ["Crie um lançamento e um orçamento novos.", "Faça logout e login de novo.", "Abra /financas em outra aba ou navegador com a mesma conta."], expected: "Os dois registros continuam lá: o backend é a fonte de verdade, não a aba.", at: "" },
  { title: "Navegação por teclado", layer: "Acessibilidade", precondition: fresh, steps: ["Percorra o formulário de lançamento só com Tab.", "Envie com Enter a partir do último campo.", "Abra a edição de uma linha e volte com Escape ou pelo botão Cancelar."], expected: "Toda ação é alcançável pelo teclado, com foco visível e ordem que segue a leitura da tela.", at: "#lancamentos" },
  { title: "Rótulos acessíveis", layer: "Acessibilidade", precondition: fresh, steps: ["Inspecione cada campo do formulário e confirme o label associado.", "Provoque um erro e confirme aria-invalid e aria-describedby.", "Confira o nome acessível dos botões de editar e excluir da tabela."], expected: "Todo campo tem rótulo programático, o erro é associado ao campo e os ícones têm nome acessível.", at: "#lancamentos" },
  { title: "Leitor de tela", layer: "Acessibilidade", precondition: fresh, steps: ["Com o leitor de tela ativo, crie um lançamento válido.", "Provoque um erro de validação.", "Confira o anúncio das barras de orçamento e de meta."], expected: "Sucesso e erro são anunciados por aria-live e as barras informam o percentual em texto, não só na cor.", at: "#orcamentos" },
  { title: "Mobile", layer: "Responsividade", precondition: fresh, steps: ["Abra o ambiente em viewport de 375px.", "Execute o cadastro de um lançamento até o fim.", "Percorra a tabela na horizontal."], expected: "Nenhum conteúdo é cortado, a tabela rola dentro do próprio container e a página não rola na horizontal.", at: "" },
  { title: "Tablet", layer: "Responsividade", precondition: fresh, steps: ["Abra o ambiente em viewport de 768px.", "Confira o empilhamento das colunas e dos cartões do topo.", "Execute uma edição em linha."], expected: "O layout se reorganiza sem sobreposição e a edição em linha continua utilizável.", at: "" },
  { title: "Desktop", layer: "Responsividade", precondition: fresh, steps: ["Abra o ambiente em viewport de 1440px.", "Confira as duas colunas e o alinhamento dos cartões.", "Execute o fluxo de cadastro."], expected: "As duas colunas ficam alinhadas, sem espaço morto nem quebra de leitura.", at: "" },
  { title: "Recarregamento no fluxo", layer: "Resiliência", precondition: fresh, steps: ["Preencha o formulário de lançamento sem enviar.", "Recarregue a página.", "Repita recarregando logo depois de enviar."], expected: "O formulário volta limpo (nada foi gravado) e o lançamento enviado antes do recarregamento está lá.", at: "#lancamentos" },
  { title: "Duplo clique", layer: "Resiliência", precondition: fresh, steps: ["Preencha um lançamento válido.", "Clique em Adicionar duas vezes rapidamente.", "Confira a lista e o total."], expected: "O botão fica indisponível durante o envio e apenas um lançamento é criado.", at: "#lancamentos" },
  { title: "Offline/erro de rede", layer: "Resiliência", precondition: fresh, steps: ["Coloque o navegador em modo offline pelo DevTools.", "Tente criar um lançamento.", "Volte para online e tente de novo."], expected: "A falha aparece como mensagem de erro legível, nada some da tela e a nova tentativa funciona.", at: "#lancamentos" },
  { title: "Permissão de usuário", layer: "Segurança", precondition: fresh, steps: ["Troque o perfil de teste para Somente leitura.", "Tente criar, editar e excluir um lançamento.", "Repita chamando /api/v1/practice/financas.transactions direto."], expected: "As três ações são recusadas com 403 pelo servidor — esconder o botão não é o que protege.", at: "" },
  { title: "Dados sensíveis", layer: "Segurança", precondition: "Duas contas de aluno diferentes, ambas com massa criada.", steps: ["Anote o id de um lançamento da conta A.", "Logado como conta B, tente ler e alterar esse id pela API.", "Confira o que a resposta devolve."], expected: "A conta B não enxerga nem altera dados da conta A: o isolamento é por linha, no banco.", at: "" },
  { title: "Injeção de texto", layer: "Segurança", precondition: fresh, steps: ["Cadastre um lançamento com a descrição <b>teste</b>.", "Cadastre outro com \"; drop table --\" na categoria.", "Confira a lista, o filtro de categoria e o CSV exportado."], expected: "O conteúdo aparece como texto puro em todos os lugares, sem executar marcação nem quebrar o CSV.", at: "#lancamentos" },
  { title: "Performance de lista", layer: "Performance", precondition: fresh, steps: ["Crie 60 lançamentos pela API em sequência.", "Filtre, ordene e navegue entre páginas.", "Meça o tempo de resposta de cada interação."], expected: "A lista continua respondendo rápido e a paginação limita o que é renderizado.", at: "#lancamentos" },
  { title: "Performance de envio", layer: "Performance", precondition: fresh, steps: ["Envie um lançamento com a rede limitada a 3G lento.", "Observe o estado do botão durante o envio.", "Confira o resultado ao final."], expected: "Há indicação de carregamento enquanto salva e o resultado só aparece depois da confirmação do servidor.", at: "#lancamentos" },
  { title: "Auditoria", layer: "Governança", precondition: fresh, steps: ["Exclua um lançamento e um orçamento.", "Procure na interface algum histórico dessas ações.", "Registre o que encontrou."], expected: "O ambiente ainda não guarda histórico de alterações: o esperado é provar isso e registrar como lacuna, com impacto.", at: "" },
  { title: "Exportação", layer: "Dados", precondition: fresh, steps: ["Aplique o filtro de tipo Despesa.", "Exporte o CSV de lançamentos.", "Abra o arquivo e compare linha a linha com a tela."], expected: "O CSV traz exatamente as linhas filtradas, com os mesmos rótulos e a mesma formatação de valor da tela.", at: "#lancamentos" },
  { title: "Conflito de dados", layer: "Dados", precondition: fresh, steps: ["Abra o mesmo lançamento em duas abas.", "Edite o valor na aba 1 e salve.", "Edite o mesmo campo na aba 2 e salve."], expected: "A última gravação vence sem erro silencioso; documente se o aluno da aba 2 tem como perceber que sobrescreveu.", at: "#lancamentos" },
  { title: "Recuperação após erro", layer: "Resiliência", precondition: fresh, steps: ["Envie um lançamento com valor inválido e receba o erro.", "Corrija apenas o campo destacado.", "Envie de novo."], expected: "Os demais campos preenchidos são preservados, o erro some ao corrigir e o envio conclui.", at: "#lancamentos" },
  { title: "Smoke final", layer: "Regressão", precondition: fresh, steps: ["Crie um orçamento, registre despesas até estourá-lo e confira o alerta.", "Edite uma meta até alcançá-la.", "Confira saldo, gastos por categoria e o CSV exportado."], expected: "Orçamento estourado alerta, meta alcançada é sinalizada e os três totais continuam coerentes entre si.", at: "#orcamentos", bugId: "financas.orcamento-sem-alerta" },
];

const agendamentos: Draft[] = [
  { title: "Acesso inicial", layer: "UI", precondition: "Sessão nova, sem massa criada ainda.", steps: ["Abra /agendamentos pela primeira vez.", "Confira a grade do dia 18/08/2026.", "Compare os agendamentos da agenda com os horários marcados como ocupados."], expected: "A grade abre no dia da massa, com 10:00 e 14:00 ocupados e o restante livre.", at: "#grade" },
  { title: "Carregamento da página", layer: "UI", precondition: fresh, steps: ["Atualize a página com cache desabilitado.", "Observe a grade e os cartões do topo enquanto carregam.", "Confira se algum horário aparece livre antes de virar ocupado."], expected: "A grade chega pronta do servidor, sem exibir horário livre que na verdade está ocupado.", at: "#grade" },
  { title: "Estado vazio", layer: "UI", precondition: fresh, steps: ["Exclua todas as faixas de disponibilidade.", "Volte para a grade do dia.", "Restaure a massa ao final."], expected: "Sem faixa configurada, a grade fica vazia com mensagem explicando, e nenhum horário pode ser agendado.", at: "#disponibilidade" },
  { title: "Busca por texto", layer: "UI", precondition: fresh, steps: ["Busque por \"Ana\" na agenda.", "Busque por \"consulta\", em minúsculas.", "Busque por um nome inexistente."], expected: "A busca encontra por cliente e por serviço, ignora caixa e acento, e informa quando não há resultado.", at: "#agenda" },
  { title: "Filtro combinado", layer: "UI", precondition: fresh, steps: ["Filtre a agenda por situação Cancelado.", "Combine com uma busca por cliente.", "Limpe os filtros."], expected: "Só Carla Nunes aparece no filtro de cancelados, a busca refina ainda mais e limpar devolve tudo.", at: "#agenda" },
  { title: "Ordenação", layer: "UI", precondition: fresh, steps: ["Ordene a agenda por Cliente (A–Z).", "Ordene por Data (mais recentes).", "Volte para Data (próximos)."], expected: "Cada ordenação reordena a lista completa e mantém a contagem de registros.", at: "#agenda" },
  { title: "Paginação", layer: "UI", precondition: fresh, steps: ["Ajuste itens por página para 5.", "Crie agendamentos até passar de uma página.", "Navegue entre as páginas e filtre estando na segunda."], expected: "A navegação respeita o total de páginas e filtrar volta para a primeira, sem página vazia.", at: "#agenda" },
  { title: "Criar registro válido", layer: "Fluxo", precondition: fresh, steps: ["Escolha o horário livre 11:00 do dia 18/08/2026 na grade.", "Preencha cliente \"Diego Alves\" e serviço \"Retorno\".", "Agende e confira a grade e a agenda."], expected: "O agendamento é criado, o horário passa a aparecer ocupado na grade e entra no resumo por dia.", at: "#grade" },
  { title: "Campo obrigatório", layer: "Validação", precondition: fresh, steps: ["Envie a nova reserva com o formulário vazio.", "Preencha só o cliente e envie de novo.", "Confira a mensagem de cada campo."], expected: "Cliente, serviço, data, horário e situação exigem valor, com mensagem por campo e nada gravado.", at: "#nova-reserva" },
  { title: "Formato inválido", layer: "Validação", precondition: fresh, steps: ["Envie um horário fora do formato HH:MM pela API.", "Envie uma data inválida como 2026-13-40.", "Compare o erro da API com o da interface."], expected: "Os dois lados recusam com a mesma mensagem de formato e a API responde 422 com o campo.", at: "#nova-reserva" },
  { title: "Valor limite", layer: "Validação", precondition: fresh, steps: ["Agende exatamente no primeiro horário da faixa (09:00).", "Tente agendar no horário de fechamento (18:00).", "Tente um serviço com duração 10 e outro com 500 minutos."], expected: "A abertura é aceita, o fechamento é recusado por ficar fora da faixa e a duração respeita o intervalo de 15 a 480.", at: "#nova-reserva" },
  { title: "Duplicidade", layer: "Validação", precondition: fresh, steps: ["Tente agendar outro cliente às 10:00 do dia 18/08/2026, já ocupado por Ana Costa.", "Tente o mesmo horário em 25/08/2026, que está livre.", "Cadastre um serviço com nome já existente."], expected: "O horário ocupado é recusado citando quem o ocupa, outra data é aceita e o serviço repetido é barrado.", at: "#nova-reserva", bugId: "agendamentos.conflito-permitido" },
  { title: "Cancelar operação", layer: "Fluxo", precondition: fresh, steps: ["Comece a editar um agendamento e mude o cliente.", "Clique em Cancelar.", "Peça a exclusão de outro agendamento e cancele na confirmação."], expected: "Nem a edição nem a exclusão canceladas mudam a agenda.", at: "#agenda" },
  { title: "Editar registro", layer: "Fluxo", precondition: fresh, steps: ["Reagende Bruno Dias de 14:00 para 15:00 no mesmo dia.", "Confira a grade antes e depois.", "Recarregue a página."], expected: "14:00 fica livre, 15:00 fica ocupado e o reagendamento persiste após o recarregamento.", at: "#agenda" },
  { title: "Excluir/cancelar registro", layer: "Fluxo", precondition: fresh, steps: ["Cancele o agendamento de Ana Costa pelo resumo por dia.", "Confira o horário 10:00 na grade.", "Tente agendar outro cliente nesse horário."], expected: "Cancelar libera o horário: a grade mostra livre e o novo agendamento é aceito.", at: "#por-dia", bugId: "agendamentos.cancelado-ocupa-horario" },
  { title: "Persistência", layer: "Dados", precondition: fresh, steps: ["Crie um agendamento e uma faixa de disponibilidade.", "Faça logout e login de novo.", "Abra a agenda em outro navegador com a mesma conta."], expected: "Agendamento e faixa continuam lá, com a grade refletindo os dois.", at: "" },
  { title: "Navegação por teclado", layer: "Acessibilidade", precondition: fresh, steps: ["Percorra a grade de horários só com Tab.", "Escolha um horário com Enter ou espaço.", "Complete a reserva sem usar o mouse."], expected: "Cada horário é um controle alcançável, com foco visível, e o horário escolhido chega ao formulário.", at: "#grade" },
  { title: "Rótulos acessíveis", layer: "Acessibilidade", precondition: fresh, steps: ["Inspecione o nome acessível de um horário livre e de um ocupado.", "Provoque um conflito e confira a associação do erro ao campo.", "Confira o rótulo do seletor de dia."], expected: "Horário ocupado anuncia de quem é, o erro é associado ao campo horário e o seletor de dia tem rótulo.", at: "#grade" },
  { title: "Leitor de tela", layer: "Acessibilidade", precondition: fresh, steps: ["Com o leitor ativo, crie um agendamento válido.", "Provoque um conflito de horário.", "Cancele um agendamento pelo resumo por dia."], expected: "Sucesso e erro são anunciados por aria-live, e o estado do agendamento é dito em texto, não só por ícone.", at: "#nova-reserva" },
  { title: "Mobile", layer: "Responsividade", precondition: fresh, steps: ["Abra em viewport de 375px.", "Percorra a grade de horários.", "Complete uma reserva até o fim."], expected: "A grade quebra em várias linhas sem cortar horário e o fluxo conclui sem rolagem horizontal da página.", at: "" },
  { title: "Tablet", layer: "Responsividade", precondition: fresh, steps: ["Abra em viewport de 768px.", "Confira o empilhamento da grade e do painel lateral.", "Execute um cancelamento."], expected: "As seções se reorganizam sem sobreposição e as ações continuam alcançáveis.", at: "" },
  { title: "Desktop", layer: "Responsividade", precondition: fresh, steps: ["Abra em viewport de 1440px.", "Confira grade, agenda e painel de configuração juntos.", "Execute uma reserva completa."], expected: "As duas colunas ficam alinhadas e a grade cabe sem quebra estranha.", at: "" },
  { title: "Recarregamento no fluxo", layer: "Resiliência", precondition: fresh, steps: ["Escolha um horário na grade e preencha o cliente sem enviar.", "Recarregue a página.", "Confira a grade e a agenda."], expected: "Nada foi reservado: o horário continua livre e o formulário volta limpo.", at: "#nova-reserva" },
  { title: "Duplo clique", layer: "Resiliência", precondition: fresh, steps: ["Preencha uma reserva válida.", "Clique em Agendar duas vezes rapidamente.", "Confira a agenda e a grade."], expected: "Só um agendamento é criado; a segunda tentativa é impedida pelo estado do botão ou pelo conflito.", at: "#nova-reserva" },
  { title: "Offline/erro de rede", layer: "Resiliência", precondition: fresh, steps: ["Fique offline pelo DevTools.", "Tente agendar.", "Volte para online e repita."], expected: "O erro é exibido de forma legível, a grade não muda e a nova tentativa conclui.", at: "#nova-reserva" },
  { title: "Permissão de usuário", layer: "Segurança", precondition: fresh, steps: ["Troque o perfil para Operador.", "Tente excluir um serviço e depois um agendamento.", "Troque para Somente leitura e tente agendar."], expected: "O Operador não exclui e só mexe na operação do dia; o Somente leitura recebe 403 em qualquer escrita.", at: "" },
  { title: "Dados sensíveis", layer: "Segurança", precondition: "Duas contas de aluno com agenda criada.", steps: ["Anote o id de um agendamento da conta A.", "Logado como conta B, tente lê-lo e alterá-lo pela API.", "Confira a resposta."], expected: "A agenda de uma conta não é visível nem editável pela outra.", at: "" },
  { title: "Injeção de texto", layer: "Segurança", precondition: fresh, steps: ["Agende um cliente chamado <script>alert(1)</script>.", "Confira a grade, a agenda e o resumo por dia.", "Exporte o CSV e abra o arquivo."], expected: "O nome aparece como texto puro em todas as superfícies, inclusive no rótulo acessível do horário e no CSV.", at: "#nova-reserva" },
  { title: "Performance de lista", layer: "Performance", precondition: fresh, steps: ["Crie 60 agendamentos distribuídos em várias datas pela API.", "Filtre, ordene e navegue entre páginas.", "Abra a grade de um dia cheio."], expected: "Agenda e grade continuam respondendo rápido e a paginação limita o que é renderizado.", at: "#agenda" },
  { title: "Performance de envio", layer: "Performance", precondition: fresh, steps: ["Agende com a rede limitada a 3G lento.", "Observe o estado do botão.", "Confira quando a grade é atualizada."], expected: "O botão indica carregamento e a grade só muda depois da confirmação do servidor.", at: "#nova-reserva" },
  { title: "Auditoria", layer: "Governança", precondition: fresh, steps: ["Cancele e depois exclua um agendamento.", "Procure algum histórico dessas ações na interface.", "Registre o que encontrou."], expected: "Não há trilha de auditoria: o esperado é provar a ausência e registrar o impacto para um negócio com agenda.", at: "" },
  { title: "Exportação", layer: "Dados", precondition: fresh, steps: ["Filtre a agenda por Confirmado.", "Exporte o CSV.", "Compare o arquivo com a tela, inclusive datas e horários."], expected: "O CSV traz as linhas filtradas com data em dd/mm/aaaa e horário em HH:MM, iguais à tela.", at: "#agenda" },
  { title: "Conflito de dados", layer: "Dados", precondition: fresh, steps: ["Abra a agenda em duas abas.", "Reserve o horário 11:00 na aba 1.", "Reserve o mesmo horário na aba 2, cuja grade ainda o mostra livre."], expected: "A segunda tentativa é recusada pelo servidor com a mensagem de conflito, mesmo com a grade desatualizada na tela.", at: "#grade", bugId: "agendamentos.conflito-permitido" },
  { title: "Recuperação após erro", layer: "Resiliência", precondition: fresh, steps: ["Tente agendar em um horário ocupado e receba o erro.", "Escolha outro horário na grade.", "Envie de novo."], expected: "Cliente e serviço continuam preenchidos, o erro some ao trocar o horário e a reserva conclui.", at: "#nova-reserva" },
  { title: "Smoke final", layer: "Regressão", precondition: fresh, steps: ["Configure uma faixa nova de atendimento no sábado.", "Agende, reagende e cancele um cliente nesse dia.", "Confira grade, resumo por dia e cartões do topo a cada passo."], expected: "As três superfícies contam a mesma história em todos os passos, e o horário cancelado volta a ficar livre.", at: "#disponibilidade" },
];

const crm: Draft[] = [
  { title: "Acesso inicial", layer: "UI", precondition: "Sessão nova, sem massa criada ainda.", steps: ["Abra /crm pela primeira vez.", "Confira o funil, com cinco colunas.", "Compare o valor do pipeline com a soma das colunas sem a de perdidos."], expected: "O funil abre com as cinco oportunidades da massa e o pipeline soma R$ 194.000,00, excluindo a perdida.", at: "#funil", bugId: "crm.pipeline-soma-perdidos" },
  { title: "Carregamento da página", layer: "UI", precondition: fresh, steps: ["Atualize com cache desabilitado.", "Observe os cartões do topo e o funil.", "Confira se algum valor aparece zerado antes de estabilizar."], expected: "Pipeline, ganhos e taxa chegam prontos do servidor, sem estado intermediário incorreto.", at: "" },
  { title: "Estado vazio", layer: "UI", precondition: fresh, steps: ["Exclua todas as oportunidades.", "Confira as cinco colunas do funil e os cartões do topo.", "Restaure a massa ao final."], expected: "Cada coluna mostra \"Vazio\", o pipeline vai a R$ 0,00 e a taxa de ganho fica em 0% sem divisão por zero.", at: "#funil" },
  { title: "Busca por texto", layer: "UI", precondition: fresh, steps: ["Busque \"Marina\" nos contatos.", "Busque \"Antonio\", sem acento — o contato cadastrado é \"Antônio Ribeiro\".", "Busque por um domínio de e-mail, como \"orbitsaas\"."], expected: "A busca encontra nos três casos: nome com e sem acento, e trecho do e-mail.", at: "#contatos", bugId: "crm.busca-ignora-acentos" },
  { title: "Filtro combinado", layer: "UI", precondition: fresh, steps: ["Filtre as oportunidades por estágio Proposta e empresa Norte Digital.", "Confira o contador.", "Limpe os filtros."], expected: "Só a oportunidade do módulo fiscal aparece, o contador acompanha e limpar devolve as cinco.", at: "#oportunidades" },
  { title: "Ordenação", layer: "UI", precondition: fresh, steps: ["Ordene as oportunidades por Valor (maior).", "Ordene por Título (A–Z).", "Volte para Valor (maior)."], expected: "A renovação anual (R$ 96.000,00) lidera na ordenação por valor e a ordem alfabética respeita acentuação.", at: "#oportunidades" },
  { title: "Paginação", layer: "UI", precondition: fresh, steps: ["Ajuste itens por página para 5.", "Crie oportunidades até passar de uma página.", "Navegue e depois filtre estando na página 2."], expected: "A navegação respeita o total de páginas e filtrar volta para a primeira, sem tela vazia.", at: "#oportunidades" },
  { title: "Criar registro válido", layer: "Fluxo", precondition: fresh, steps: ["Cadastre a oportunidade \"Integração fiscal\", Norte Digital, R$ 25.000,00, estágio Novo.", "Confira a coluna Novo do funil.", "Confira o valor do pipeline."], expected: "O card aparece na coluna Novo e o pipeline sobe exatamente R$ 25.000,00.", at: "#oportunidades" },
  { title: "Campo obrigatório", layer: "Validação", precondition: fresh, steps: ["Envie o formulário de contato vazio.", "Preencha só o nome e envie.", "Repita no formulário de oportunidade."], expected: "Cada campo obrigatório recebe a mensagem própria; o cargo, que é opcional, não bloqueia o envio.", at: "#contatos" },
  { title: "Formato inválido", layer: "Validação", precondition: fresh, steps: ["Cadastre um contato com e-mail \"marina\", sem arroba.", "Cadastre uma oportunidade com valor \"abc\".", "Repita os dois pela API."], expected: "O valor não numérico é recusado nos dois lados; investigue e registre se o e-mail sem formato válido passa.", at: "#contatos" },
  { title: "Valor limite", layer: "Validação", precondition: fresh, steps: ["Cadastre uma oportunidade de R$ 0,00 e outra de R$ 9.999.999,00.", "Tente R$ -1,00 e R$ 10.000.000,00.", "Confira o pipeline após cada operação."], expected: "Zero e o máximo entram, o restante é recusado e o pipeline acompanha cada valor aceito.", at: "#oportunidades" },
  { title: "Duplicidade", layer: "Validação", precondition: fresh, steps: ["Cadastre um contato com o e-mail marina@nortedigital.com, que já existe.", "Repita com o mesmo e-mail em maiúsculas.", "Cadastre uma empresa chamada \"Orbit SaaS\", que já existe."], expected: "As três tentativas são recusadas por duplicidade, e a comparação de e-mail ignora a caixa.", at: "#contatos" },
  { title: "Cancelar operação", layer: "Fluxo", precondition: fresh, steps: ["Comece a editar um contato e altere o cargo.", "Clique em Cancelar.", "Peça a exclusão de uma empresa e cancele na confirmação."], expected: "Nenhuma das duas operações canceladas altera os dados.", at: "#contatos" },
  { title: "Editar registro", layer: "Fluxo", precondition: fresh, steps: ["Mude a oportunidade \"Piloto de automação\" de Novo para Proposta pelo seletor do card.", "Confira as colunas de origem e destino.", "Recarregue a página."], expected: "O card muda de coluna, os totais das duas colunas acompanham e a mudança persiste.", at: "#funil" },
  { title: "Excluir/cancelar registro", layer: "Fluxo", precondition: fresh, steps: ["Peça a exclusão do contato Pedro Lima.", "Confirme na segunda etapa.", "Confira a lista e a contagem exibida."], expected: "A exclusão só acontece após a confirmação e a contagem acompanha.", at: "#contatos" },
  { title: "Persistência", layer: "Dados", precondition: fresh, steps: ["Crie uma oportunidade e mova outra de estágio.", "Faça logout e login de novo.", "Abra /crm em outro navegador com a mesma conta."], expected: "As duas alterações continuam lá, com o pipeline recalculado a partir do banco.", at: "" },
  { title: "Navegação por teclado", layer: "Acessibilidade", precondition: fresh, steps: ["Percorra os cards do funil só com Tab.", "Mude o estágio de uma oportunidade usando apenas o teclado.", "Complete um cadastro de contato sem mouse."], expected: "O seletor de estágio é operável pelo teclado, com foco visível, e o cadastro conclui.", at: "#funil" },
  { title: "Rótulos acessíveis", layer: "Acessibilidade", precondition: fresh, steps: ["Confira o nome acessível do seletor de estágio de cada card.", "Provoque um erro de duplicidade e confira a associação com o campo.", "Confira o nome dos botões de editar e excluir da tabela."], expected: "O seletor diz de qual oportunidade é, o erro é associado ao campo e os ícones têm nome acessível.", at: "#funil" },
  { title: "Leitor de tela", layer: "Acessibilidade", precondition: fresh, steps: ["Com o leitor ativo, busque um contato.", "Mude o estágio de uma oportunidade.", "Provoque um erro de duplicidade."], expected: "A contagem de resultados da busca é anunciada por aria-live e o erro é lido ao aparecer.", at: "#contatos" },
  { title: "Mobile", layer: "Responsividade", precondition: fresh, steps: ["Abra em viewport de 375px.", "Percorra as cinco colunas do funil.", "Complete um cadastro de oportunidade."], expected: "As colunas empilham sem cortar conteúdo e a página não rola na horizontal.", at: "#funil" },
  { title: "Tablet", layer: "Responsividade", precondition: fresh, steps: ["Abra em viewport de 768px.", "Confira o funil em três colunas.", "Execute uma mudança de estágio."], expected: "O funil se reorganiza sem sobreposição e a ação continua utilizável.", at: "#funil" },
  { title: "Desktop", layer: "Responsividade", precondition: fresh, steps: ["Abra em viewport de 1440px.", "Confira as cinco colunas lado a lado.", "Execute o fluxo completo de cadastro."], expected: "As cinco colunas cabem alinhadas e os cards mantêm altura legível.", at: "#funil" },
  { title: "Recarregamento no fluxo", layer: "Resiliência", precondition: fresh, steps: ["Preencha o formulário de oportunidade sem enviar.", "Recarregue a página.", "Repita recarregando logo depois de mudar um estágio."], expected: "O formulário volta limpo e a mudança de estágio já enviada permanece.", at: "#oportunidades" },
  { title: "Duplo clique", layer: "Resiliência", precondition: fresh, steps: ["Preencha uma oportunidade válida.", "Clique em Adicionar duas vezes rapidamente.", "Confira o funil e o pipeline."], expected: "Apenas uma oportunidade é criada e o pipeline sobe uma única vez.", at: "#oportunidades" },
  { title: "Offline/erro de rede", layer: "Resiliência", precondition: fresh, steps: ["Fique offline pelo DevTools.", "Mude o estágio de uma oportunidade.", "Volte para online e repita."], expected: "O erro aparece de forma legível, o card não muda de coluna sem confirmação e a nova tentativa funciona.", at: "#funil" },
  { title: "Permissão de usuário", layer: "Segurança", precondition: fresh, steps: ["Troque o perfil para Operador.", "Tente excluir uma empresa e depois uma oportunidade.", "Troque para Somente leitura e tente mover um card."], expected: "O Operador não exclui e não mexe em empresas; o Somente leitura recebe 403 em qualquer escrita.", at: "" },
  { title: "Dados sensíveis", layer: "Segurança", precondition: "Duas contas de aluno com CRM criado.", steps: ["Anote o id de um contato da conta A.", "Logado como conta B, tente lê-lo e alterá-lo pela API.", "Confira a resposta e o corpo devolvido."], expected: "Os contatos de uma conta não vazam para a outra, nem o e-mail.", at: "" },
  { title: "Injeção de texto", layer: "Segurança", precondition: fresh, steps: ["Cadastre um contato com nome <img src=x onerror=alert(1)>.", "Confira a lista, a busca e os filtros de empresa.", "Exporte o CSV e abra o arquivo."], expected: "O texto aparece literal em todas as superfícies, sem executar nada e sem quebrar colunas do CSV.", at: "#contatos" },
  { title: "Performance de lista", layer: "Performance", precondition: fresh, steps: ["Crie 60 oportunidades pela API.", "Filtre, ordene e navegue entre páginas.", "Observe o funil com muitas colunas cheias."], expected: "Lista e funil continuam respondendo rápido, com a paginação limitando a tabela.", at: "#oportunidades" },
  { title: "Performance de envio", layer: "Performance", precondition: fresh, steps: ["Mude o estágio com a rede limitada a 3G lento.", "Observe o estado do seletor durante o envio.", "Confira quando o pipeline é recalculado."], expected: "O seletor fica indisponível durante o envio e o total só muda após a confirmação do servidor.", at: "#funil" },
  { title: "Auditoria", layer: "Governança", precondition: fresh, steps: ["Mude uma oportunidade para Perdido e depois exclua um contato.", "Procure histórico dessas ações fora das atividades cadastradas à mão.", "Registre o que encontrou."], expected: "Não há trilha automática: o esperado é provar a ausência e registrar o risco para um funil comercial.", at: "" },
  { title: "Exportação", layer: "Dados", precondition: fresh, steps: ["Filtre as oportunidades pelo estágio Ganho.", "Exporte o CSV.", "Compare o arquivo com a tela, inclusive o rótulo do estágio."], expected: "O CSV traz as linhas filtradas, com o estágio pelo rótulo exibido e o valor formatado como na tela.", at: "#oportunidades" },
  { title: "Conflito de dados", layer: "Dados", precondition: fresh, steps: ["Abra o CRM em duas abas.", "Mova a mesma oportunidade para Ganho na aba 1.", "Mova a mesma para Perdido na aba 2."], expected: "A última gravação vence; registre se a aba 2 tem como perceber que sobrescreveu a decisão da aba 1.", at: "#funil" },
  { title: "Recuperação após erro", layer: "Resiliência", precondition: fresh, steps: ["Tente cadastrar um contato com e-mail já existente.", "Corrija apenas o e-mail.", "Envie de novo."], expected: "Nome, empresa e cargo são preservados, o erro some ao corrigir e o cadastro conclui.", at: "#contatos" },
  { title: "Smoke final", layer: "Regressão", precondition: fresh, steps: ["Cadastre empresa, contato e oportunidade ligados entre si.", "Registre uma atividade e mova a oportunidade até Ganho.", "Depois mova outra para Perdido e confira os três cartões do topo."], expected: "Pipeline, ganhos e taxa de ganho acompanham cada movimento — inclusive a queda ao marcar como perdida.", at: "#funil", bugId: "crm.pipeline-soma-perdidos" },
];

const qaLab: Draft[] = [
  { title: "Acesso inicial", layer: "UI", precondition: "Loja aberta em sessão nova, sem carrinho.", steps: ["Abra a loja pela primeira vez.", "Confira se o catálogo aparece já na primeira tela.", "Percorra a navegação até carrinho e pedidos."], expected: "A loja abre no catálogo e todas as áreas são alcançáveis em um clique.", at: "" },
  { title: "Carregamento da página", layer: "UI", precondition: "Catálogo disponível.", steps: ["Atualize /shop/products com cache desabilitado.", "Observe imagens, preços e filtros enquanto carregam.", "Confira se algum preço aparece divergente antes de estabilizar."], expected: "O catálogo carrega sem exibir preço ou estoque intermediário incorreto.", at: "/shop/products" },
  { title: "Estado vazio", layer: "UI", precondition: "Catálogo disponível.", steps: ["Busque por um termo sem resultado no catálogo.", "Confira a mensagem e as ações oferecidas.", "Abra o carrinho vazio."], expected: "Busca sem resultado e carrinho vazio têm mensagem própria e caminho de volta.", at: "/shop/products" },
  { title: "Busca por texto", layer: "UI", precondition: "Catálogo disponível.", steps: ["Busque por um produto existente.", "Busque com caixa diferente e com acento.", "Busque por um trecho parcial do nome."], expected: "A busca encontra por trecho, ignorando caixa e acento, e informa quando não há resultado.", at: "/shop/products" },
  { title: "Filtro combinado", layer: "UI", precondition: "Catálogo disponível.", steps: ["Aplique filtro de categoria e de faixa de preço juntos.", "Confira a contagem de resultados.", "Limpe os dois filtros."], expected: "Os filtros se somam, a contagem acompanha e limpar devolve o catálogo completo.", at: "/shop/products" },
  { title: "Ordenação", layer: "UI", precondition: "Catálogo disponível.", steps: ["Ordene por preço crescente e decrescente.", "Ordene por nome.", "Confira o primeiro e o último item de cada ordenação."], expected: "A ordenação vale para o catálogo inteiro e não perde itens entre as trocas.", at: "/shop/products" },
  { title: "Paginação", layer: "UI", precondition: "Catálogo disponível.", steps: ["Navegue entre as páginas do catálogo.", "Altere itens por página.", "Aplique um filtro estando em uma página além da primeira."], expected: "A navegação respeita o total de páginas e filtrar volta para a primeira.", at: "/shop/products" },
  { title: "Criar registro válido", layer: "Fluxo", precondition: "Carrinho vazio.", steps: ["Adicione um produto ao carrinho.", "Ajuste a quantidade para 2.", "Confira o subtotal do item e o total do carrinho."], expected: "Quantidade, subtotal e total do carrinho ficam coerentes entre si.", at: "/shop/cart" },
  { title: "Campo obrigatório", layer: "Validação", precondition: "Carrinho com ao menos um item.", steps: ["Vá ao checkout e envie o endereço em branco.", "Preencha só o CEP e envie de novo.", "Confira a mensagem de cada campo."], expected: "Cada campo obrigatório tem mensagem própria e o pedido não é criado.", at: "/shop/checkout" },
  { title: "Formato inválido", layer: "Validação", precondition: "Carrinho com ao menos um item.", steps: ["Informe um CEP com letras.", "Informe um e-mail sem arroba.", "Informe um cartão com menos dígitos que o esperado."], expected: "Cada formato inválido é recusado com mensagem específica, antes de qualquer cobrança simulada.", at: "/shop/checkout" },
  { title: "Valor limite", layer: "Validação", precondition: "Carrinho vazio.", steps: ["Deixe a quantidade de um item em 0.", "Suba a quantidade além do estoque disponível.", "Confira desconto, frete e imposto no total exibido em cada passo."], expected: "Quantidade zero e acima do estoque são tratadas, e o total do checkout bate com o resumo do pedido.", at: "/shop/checkout", bugId: "qa-lab.wrong-total" },
  { title: "Duplicidade", layer: "Validação", precondition: "Carrinho com um item.", steps: ["Adicione o mesmo produto de novo.", "Aplique o cupom QA10 duas vezes.", "Confira quantidade, itens e desconto."], expected: "O item repetido soma quantidade em vez de duplicar a linha, e o cupom não acumula.", at: "/shop/cart" },
  { title: "Cancelar operação", layer: "Fluxo", precondition: "Carrinho com itens.", steps: ["Comece o checkout e volte para o carrinho.", "Inicie a remoção de um item e cancele.", "Confira o carrinho."], expected: "Voltar do checkout preserva o carrinho e a remoção cancelada não altera nada.", at: "/shop/cart" },
  { title: "Editar registro", layer: "Fluxo", precondition: "Carrinho com dois itens.", steps: ["Altere a quantidade de um item.", "Remova o outro.", "Confira o total após cada alteração."], expected: "O total recalcula na hora e o carrinho reflete exatamente o que foi alterado.", at: "/shop/cart" },
  { title: "Excluir/cancelar registro", layer: "Fluxo", precondition: "Pedido criado.", steps: ["Abra o pedido e solicite o cancelamento.", "Confirme a ação.", "Confira a linha do tempo de status."], expected: "O cancelamento pede confirmação e aparece na linha do tempo com data.", at: "/shop/orders" },
  { title: "Persistência", layer: "Dados", precondition: "Carrinho com itens.", steps: ["Recarregue a página com itens no carrinho.", "Feche e reabra o navegador.", "Confira o carrinho e os pedidos."], expected: "O carrinho sobrevive ao recarregamento e o histórico de pedidos continua acessível.", at: "/shop/cart" },
  { title: "Navegação por teclado", layer: "Acessibilidade", precondition: "Catálogo disponível.", steps: ["Percorra o catálogo só com Tab.", "Adicione ao carrinho com Enter.", "Complete o checkout sem mouse."], expected: "Todo o fluxo de compra é operável por teclado, com foco visível e ordem previsível.", at: "/shop/products" },
  { title: "Rótulos acessíveis", layer: "Acessibilidade", precondition: "Checkout disponível.", steps: ["Confira o label de cada campo do checkout.", "Provoque um erro e confira aria-invalid e a associação da mensagem.", "Confira o texto alternativo das imagens do catálogo."], expected: "Campos rotulados, erros associados e imagens com alternativa textual significativa.", at: "/shop/checkout" },
  { title: "Leitor de tela", layer: "Acessibilidade", precondition: "Carrinho com itens.", steps: ["Com o leitor ativo, adicione um item ao carrinho.", "Provoque um erro no checkout.", "Conclua um pedido."], expected: "Adição ao carrinho, erro e confirmação do pedido são anunciados por aria-live.", at: "/shop/cart" },
  { title: "Mobile", layer: "Responsividade", precondition: "Catálogo disponível.", steps: ["Abra em viewport de 375px.", "Percorra catálogo, carrinho e checkout.", "Conclua um pedido."], expected: "O fluxo inteiro conclui em 375px sem corte de conteúdo nem rolagem horizontal.", at: "/shop/products" },
  { title: "Tablet", layer: "Responsividade", precondition: "Catálogo disponível.", steps: ["Abra em viewport de 768px.", "Confira a grade do catálogo e o resumo do pedido.", "Conclua um pedido."], expected: "A grade se reorganiza e o resumo permanece visível durante o checkout.", at: "/shop/products" },
  { title: "Desktop", layer: "Responsividade", precondition: "Catálogo disponível.", steps: ["Abra em viewport de 1440px.", "Confira catálogo, filtros e resumo lado a lado.", "Conclua um pedido."], expected: "O layout usa a largura sem espaço morto e mantém o resumo alinhado ao formulário.", at: "/shop/products" },
  { title: "Recarregamento no fluxo", layer: "Resiliência", precondition: "Checkout preenchido.", steps: ["Preencha o checkout sem confirmar.", "Recarregue a página.", "Confira carrinho e pedidos."], expected: "Nenhum pedido é criado e o carrinho continua íntegro.", at: "/shop/checkout" },
  { title: "Duplo clique", layer: "Resiliência", precondition: "Checkout preenchido.", steps: ["Preencha o checkout.", "Clique em confirmar duas vezes rapidamente.", "Confira o histórico de pedidos."], expected: "Apenas um pedido é criado.", at: "/shop/checkout" },
  { title: "Offline/erro de rede", layer: "Resiliência", precondition: "Checkout preenchido.", steps: ["Fique offline pelo DevTools.", "Confirme o pedido.", "Volte para online e repita."], expected: "A falha é comunicada, nada é cobrado em duplicidade e a nova tentativa conclui.", at: "/shop/checkout" },
  { title: "Permissão de usuário", layer: "Segurança", precondition: "Central de operação disponível.", steps: ["Abra /shop/operations sem estar logado.", "Tente executar uma ação de governança.", "Compare com o comportamento logado."], expected: "Ações restritas são recusadas no servidor, não apenas escondidas na interface.", at: "/shop/operations" },
  { title: "Dados sensíveis", layer: "Segurança", precondition: "Pedido criado.", steps: ["Abra o detalhe de um pedido e inspecione a resposta da rede.", "Procure dados de pagamento no armazenamento local.", "Tente abrir o pedido de outro identificador."], expected: "Nenhum dado sensível é exposto no armazenamento local nem pelo identificador de outro pedido.", at: "/shop/orders" },
  { title: "Injeção de texto", layer: "Segurança", precondition: "Checkout disponível.", steps: ["Envie <b>teste</b> no nome do destinatário.", "Envie caracteres especiais no complemento do endereço.", "Confira o resumo do pedido e o comprovante."], expected: "O conteúdo aparece como texto puro em resumo e comprovante.", at: "/shop/checkout" },
  { title: "Performance de lista", layer: "Performance", precondition: "Catálogo disponível.", steps: ["Carregue o catálogo completo.", "Filtre e ordene em sequência.", "Meça o tempo de cada interação."], expected: "Filtro e ordenação respondem sem travar a rolagem.", at: "/shop/products" },
  { title: "Performance de envio", layer: "Performance", precondition: "Checkout preenchido.", steps: ["Confirme o pedido com a rede limitada a 3G lento.", "Observe o estado do botão.", "Confira quando a confirmação aparece."], expected: "Há indicação de carregamento e a confirmação só aparece após a resposta.", at: "/shop/checkout" },
  { title: "Auditoria", layer: "Governança", precondition: "Central de operação disponível.", steps: ["Execute uma ação crítica na operação, como alterar uma regra de preço.", "Abra o painel de auditoria.", "Confira data, ação e responsável."], expected: "A ação crítica gera registro de auditoria com data e descrição.", at: "/shop/operations" },
  { title: "Exportação", layer: "Dados", precondition: "Pedido criado.", steps: ["Abra o pedido e gere a nota fiscal simulada.", "Compare os valores do documento com o resumo do pedido.", "Confira o total com desconto e frete."], expected: "O documento reproduz exatamente os valores do pedido, inclusive desconto e frete.", at: "/shop/orders", bugId: "qa-lab.wrong-total" },
  { title: "Conflito de dados", layer: "Dados", precondition: "Carrinho com itens em duas abas.", steps: ["Abra o carrinho em duas abas.", "Altere a quantidade na aba 1.", "Finalize a compra pela aba 2, com o carrinho desatualizado."], expected: "O pedido usa o estado íntegro do carrinho; documente qualquer divergência entre as abas.", at: "/shop/cart" },
  { title: "Recuperação após erro", layer: "Resiliência", precondition: "Checkout disponível.", steps: ["Envie o checkout com CEP inválido.", "Corrija apenas o CEP.", "Confirme o pedido."], expected: "Os demais campos são preservados, o erro some ao corrigir e o pedido conclui.", at: "/shop/checkout" },
  { title: "Smoke final", layer: "Regressão", precondition: "Sessão nova.", steps: ["Percorra catálogo, carrinho, cupom, frete e checkout.", "Conclua o pedido e abra o detalhe dele.", "Confira o total em cada tela do caminho."], expected: "O valor cobrado é o mesmo do carrinho, do resumo e do detalhe do pedido, sem divergência em nenhum passo.", at: "/shop/checkout", bugId: "qa-lab.wrong-total" },
];

const drafts: Record<PracticeAppId, Draft[]> = { "qa-lab": qaLab, financas, agendamentos, crm };

export const regressionPacks = practiceApps.map((app) => ({
  ...app,
  scenarios: (drafts[app.id] ?? []).map((draft, index): RegressionScenario => ({
    id: `${app.id}-${String(index + 1).padStart(2, "0")}`,
    number: index + 1,
    title: draft.title,
    layer: draft.layer,
    precondition: draft.precondition,
    steps: draft.steps,
    expected: draft.expected,
    // Âncora que começa com "/" é uma rota própria (o QA Lab tem várias telas);
    // as demais são seções dentro do ambiente.
    route: !draft.at ? app.route : draft.at.startsWith("/") ? draft.at : `${app.route}${draft.at}`,
    bugId: draft.bugId,
  })),
}));

/** Camadas presentes nos packs, na ordem em que aparecem na matriz. */
export const regressionLayers = [...new Set(qaLab.map((draft) => draft.layer))];

export function findRegressionPack(appId: string) {
  return regressionPacks.find((pack) => pack.id === appId);
}

/** Cenários que costumam pegar um desvio plantado. Usado no modo instrutor. */
export function scenariosForBug(bugId: string) {
  return regressionPacks.flatMap((pack) => pack.scenarios.filter((scenario) => scenario.bugId === bugId).map((scenario) => ({ pack, scenario })));
}
