"use client";

import Link from "next/link";
import { motion } from "motion/react";
import { ArrowRight, CheckCircle2, FileCheck2, ScanSearch } from "lucide-react";
import { Button } from "@/components/ui/button";

export function LabsHome() {
  return <main className="qa-challenge"><div className="mx-auto max-w-6xl px-5 py-10 sm:px-8 lg:py-14"><section className="qa-challenge-hero"><p className="qa-challenge-number" aria-hidden="true">QA</p><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .45 }} className="relative z-10 max-w-3xl"><p className="qa-eyebrow">QA Lab System</p><h1 className="mt-7 text-4xl font-semibold tracking-[-0.055em] sm:text-6xl">Pratique qualidade em produtos que respondem.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-muted-foreground">Cenários reais, riscos reais e entregas que viram evidência. Escolha um desafio, investigue e registre o que encontrou.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild size="lg"><Link href="/labs/desafios">Explorar 100 desafios <ArrowRight className="size-4" /></Link></Button><Button asChild size="lg" variant="outline"><Link href="/shop/products">Abrir produto de teste</Link></Button></div></motion.div></section><section className="mt-10 grid gap-4 md:grid-cols-3"><CopyCard icon={ScanSearch} index="01" title="Encontre o risco" text="Cada Lab parte de uma funcionalidade, limite ou falha que vale investigar." /><CopyCard icon={CheckCircle2} index="02" title="Teste com intenção" text="Use dados, oráculo e critérios claros para decidir o que passou ou falhou." /><CopyCard icon={FileCheck2} index="03" title="Deixe evidência" text="Registre resultado, reprodução e impacto para fechar o desafio." /></section></div></main>;
}

function CopyCard({ icon: Icon, index, title, text }: { icon: typeof ScanSearch; index: string; title: string; text: string }) { return <motion.article initial={{ opacity: 0, y: 12 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: .35, delay: Number(index) * .06 }} className="qa-process"><div className="flex items-center justify-between"><Icon className="size-4 text-primary" /><span className="font-mono text-xs text-muted-foreground">{index}</span></div><h2 className="mt-6 font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></motion.article>; }
