"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ExternalLink, Search, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { systemChallenges, type SystemChallenge } from "@/lib/system-challenges";

const progressKey = "qa-system-challenge-evidence";
type Evidence = { actual: string; reproduction: string; severity: string; submittedAt: string };
const read = (): Record<string, Evidence> => typeof window === "undefined" ? {} : JSON.parse(localStorage.getItem(progressKey) ?? "{}");

export function SystemChallenges() {
  const [query, setQuery] = useState(""); const [area, setArea] = useState("Todos"); const [evidence, setEvidence] = useState<Record<string, Evidence>>({});
  useEffect(() => setEvidence(read()), []);
  const shown = useMemo(() => systemChallenges.filter((item) => (area === "Todos" || item.area === area) && item.title.toLowerCase().includes(query.toLowerCase())), [area, query]);
  const areas = ["Todos", ...new Set(systemChallenges.map((item) => item.area))];
  return <main className="qa-system"><div className="mx-auto max-w-6xl px-5 py-10 sm:px-8"><p className="qa-eyebrow">Trilha pratica verificavel</p><h1 className="mt-2 text-4xl font-semibold">100 desafios de QA</h1><p className="mt-3 text-muted-foreground">Cada desafio exige evidencia: resultado real, reproducao e severidade. Marcar como concluido sem registrar isso nao e possivel.</p><div className="mt-6 rounded-md border p-4 text-sm"><strong>{Object.keys(evidence).length}/100 evidencias registradas</strong><div className="mt-2 h-2 overflow-hidden rounded bg-muted"><div className="h-full bg-primary" style={{ width: `${Object.keys(evidence).length}%` }} /></div></div><div className="mt-7 grid gap-3 md:grid-cols-[1fr_190px]"><label className="relative"><Search className="absolute left-3 top-3 size-4 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} className="pl-9" aria-label="Buscar desafio" placeholder="Buscar desafio" /></label><select className="input" aria-label="Filtrar area" value={area} onChange={(event) => setArea(event.target.value)}>{areas.map((item) => <option key={item}>{item}</option>)}</select></div><div className="mt-6 grid gap-3 md:grid-cols-2">{shown.map((challenge) => <ChallengeCard key={challenge.id} challenge={challenge} completed={Boolean(evidence[challenge.id])} />)}</div></div></main>;
}

export function ChallengeDetail({ challenge }: { challenge: SystemChallenge }) {
  const [saved, setSaved] = useState<Evidence | undefined>(); const [message, setMessage] = useState("");
  const surfaceRoute = challenge.area === "Clientes" ? "/shop/account" : challenge.area === "Pedidos" ? "/shop/orders" : ["Atendimento", "Operacao", "Relatorios", "Governanca"].includes(challenge.area) ? "/shop/operations" : challenge.route;
  useEffect(() => setSaved(read()[challenge.id]), [challenge.id]);
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const actual = String(form.get("actual") ?? "").trim(); const reproduction = String(form.get("reproduction") ?? "").trim(); const severity = String(form.get("severity") ?? ""); if (actual.length < 20 || reproduction.length < 20 || !severity) return setMessage("Registre ao menos 20 caracteres para resultado e reproducao, e escolha a severidade."); const entry = { actual, reproduction, severity, submittedAt: new Date().toISOString() }; const next = { ...read(), [challenge.id]: entry }; localStorage.setItem(progressKey, JSON.stringify(next)); setSaved(entry); setMessage("Evidencia salva. Desafio concluido."); }
  return <main className="qa-system"><div className="mx-auto max-w-3xl px-5 py-10 sm:px-8"><Link href="/labs/desafios" className="text-sm text-primary">← Todos os desafios</Link><Card className="mt-6"><CardHeader><CardDescription>Desafio {String(challenge.number).padStart(3, "0")} · {challenge.area} · {challenge.difficulty} · {challenge.mode}</CardDescription><CardTitle className="text-2xl">{challenge.title}</CardTitle></CardHeader><CardContent><p>{challenge.objective}</p><Brief label="Dados de teste" value={challenge.testData} /><Brief label="Oraculo" value={challenge.expected} /><Brief label="Pista de investigacao" value={challenge.plantedBug} /><h2 className="mt-7 font-semibold">Roteiro de execucao</h2><ol className="mt-3 grid gap-3">{challenge.steps.map((step, index) => <li key={step} className="rounded border p-3 text-sm"><strong>{index + 1}.</strong> {step}</li>)}</ol><h2 className="mt-7 font-semibold">Criterios para concluir</h2><ul className="mt-3 grid gap-2 text-sm">{challenge.acceptance.map((item) => <li key={item} className="rounded border p-3">{item}</li>)}</ul><Button asChild className="mt-6"><Link href={surfaceRoute}>Abrir superficie do desafio <ExternalLink className="size-4" /></Link></Button></CardContent></Card><Card className="mt-5"><CardHeader><CardTitle>Entrega de evidencia</CardTitle><CardDescription>Preencha com o que voce observou; esta entrega e o que contabiliza o desafio.</CardDescription></CardHeader><CardContent><form className="grid gap-4" onSubmit={submit}><label className="grid gap-2 text-sm font-medium">Resultado obtido<Textarea name="actual" minLength={20} required defaultValue={saved?.actual} placeholder="O que a aplicacao exibiu ou fez? Inclua valores e mensagens." /></label><label className="grid gap-2 text-sm font-medium">Passos de reproducao<Textarea name="reproduction" minLength={20} required defaultValue={saved?.reproduction} placeholder="1. ... 2. ... 3. ..." /></label><label className="grid gap-2 text-sm font-medium">Severidade<select name="severity" className="input" required defaultValue={saved?.severity ?? ""}><option value="" disabled>Selecione</option><option>Baixa</option><option>Media</option><option>Alta</option><option>Critica</option></select></label><Button><Send className="size-4" /> Salvar evidencia</Button></form>{message && <p role="status" aria-live="polite" className="mt-4 text-sm text-primary">{message}</p>}</CardContent></Card></div></main>;
}

function Brief({ label, value }: { label: string; value: string }) { return <div className="mt-5 rounded-md border bg-muted/40 p-3 text-sm"><strong>{label}</strong><p className="mt-1 text-muted-foreground">{value}</p></div>; }
function ChallengeCard({ challenge, completed }: { challenge: SystemChallenge; completed: boolean }) { return <Card><CardHeader><CardDescription>#{String(challenge.number).padStart(3, "0")} · {challenge.area} · {challenge.difficulty}</CardDescription><CardTitle className="text-lg">{challenge.title}</CardTitle></CardHeader><CardContent className="flex items-center justify-between gap-3"><span className="text-sm text-muted-foreground">{completed ? "Evidencia registrada" : challenge.mode === "fluxo" ? "Validacao de fluxo" : "Teste investigativo"}</span><Button asChild size="sm" variant={completed ? "outline" : "default"}><Link href={`/labs/desafios/${challenge.id}`}>{completed ? "Revisar" : "Executar"}</Link></Button></CardContent></Card>; }
