"use client";

import { useState } from "react";
import { Download, LockKeyhole, Plus, Save, Send, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { SystemModule } from "@/lib/lab-system";

const store = (key: string, value: unknown) => localStorage.setItem(`qa-system-${key}`, JSON.stringify(value));

export function SystemModuleClient({ module }: { module: SystemModule }) {
  const [notice, setNotice] = useState("");
  const [tickets, setTickets] = useState([{ id: "TK-104", title: "Pagamento duplicado", priority: "Alta", sla: "01:42" }]);
  const [messages, setMessages] = useState(["Cliente relata uma cobranca em duplicidade."]);
  const [mfa, setMfa] = useState(false); const [stock, setStock] = useState(3); const [checkoutV2, setCheckoutV2] = useState(false);
  const say = (message: string) => { store(module.slug, { message, updatedAt: new Date().toISOString() }); setNotice(message); };
  if (module.slug === "clientes") return <Workspace module={module} notice={notice}><form className="grid gap-3 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); const email = String(new FormData(event.currentTarget).get("email")); if (!email.includes("@")) return setNotice("Informe um e-mail valido."); say(`Conta de ${email} atualizada.`); }}><label className="grid gap-1 text-sm">E-mail<Input name="email" type="email" required placeholder="qa@exemplo.com" /></label><label className="grid gap-1 text-sm">Nova senha<Input name="password" type="password" minLength={8} placeholder="Minimo de 8 caracteres" /></label><label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" /> Receber comunicacoes sobre pedidos</label><Button className="w-fit"><Save className="size-4" /> Salvar perfil</Button></form><div className="mt-5 flex flex-wrap gap-2 border-t pt-4"><Button variant="outline" onClick={() => { setMfa(!mfa); say(mfa ? "MFA desativado." : "MFA ativado: codigo 123456."); }}><LockKeyhole className="size-4" /> MFA {mfa ? "ativo" : "inativo"}</Button><Button variant="outline" onClick={() => say("Exportacao de dados pessoais preparada.")}><Download className="size-4" /> Exportar dados</Button><Button variant="outline" onClick={() => say("Sessoes remotas encerradas.")}>Encerrar sessoes</Button></div></Workspace>;
  if (module.slug === "suporte") return <Workspace module={module} notice={notice}><form className="flex flex-wrap gap-3" onSubmit={(event) => { event.preventDefault(); const title = String(new FormData(event.currentTarget).get("title")); if (title) { setTickets([{ id: `TK-${105 + tickets.length}`, title, priority: "Media", sla: "04:00" }, ...tickets]); say("Ticket aberto com sucesso."); event.currentTarget.reset(); } }}><Input name="title" required aria-label="Assunto do ticket" placeholder="Descreva o problema" className="max-w-md" /><Button><Plus className="size-4" /> Abrir ticket</Button></form><div className="mt-5 grid gap-2">{tickets.map((ticket) => <div key={ticket.id} className="flex flex-wrap justify-between gap-2 rounded-md border p-3 text-sm"><span><strong>{ticket.id}</strong> — {ticket.title}</span><span>{ticket.priority} · SLA {ticket.sla}</span></div>)}</div><form className="mt-5 flex gap-2" onSubmit={(event) => { event.preventDefault(); const message = String(new FormData(event.currentTarget).get("message")); if (message) { setMessages([...messages, message]); say("Resposta enviada."); event.currentTarget.reset(); } }}><Input name="message" aria-label="Mensagem de atendimento" placeholder="Escreva uma resposta" /><Button><Send className="size-4" /> Enviar</Button></form><div className="mt-3 rounded-md bg-muted p-3 text-sm">{messages.map((message, index) => <p key={index}>{message}</p>)}</div></Workspace>;
  if (module.slug === "operacao") return <Workspace module={module} notice={notice}><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm">Estoque do Caderno Bug Report<Input type="number" min="0" value={stock} onChange={(event) => setStock(Number(event.target.value))} /></label><div className="rounded-md border p-3 text-sm"><strong className={stock < 5 ? "text-destructive" : "text-primary"}>{stock < 5 ? "Alerta: estoque minimo" : "Estoque saudavel"}</strong><p className="mt-1 text-muted-foreground">Limite configurado: 5 unidades.</p></div><label className="grid gap-1 text-sm">Fornecedor<Input placeholder="Nome do fornecedor" /></label><label className="grid gap-1 text-sm">Inicio da promocao<Input type="date" /></label></div><div className="mt-5 flex flex-wrap gap-2"><Button onClick={() => say("Alteracao de estoque registrada.")}><Save className="size-4" /> Salvar estoque</Button><Button variant="outline" onClick={() => say("Nova regra de preco enviada para aprovacao.")}>Solicitar aprovacao</Button></div></Workspace>;
  return <Workspace module={module} notice={notice}>{module.slug === "relatorios" ? <><div className="flex flex-wrap gap-3"><label className="grid gap-1 text-sm">Periodo<select className="input"><option>7 dias</option><option>30 dias</option><option>Este trimestre</option></select></label><Button variant="outline" onClick={() => say("Relatorio exportado em CSV.")}><Download className="size-4" /> Exportar CSV</Button></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[["Pedidos", "128"], ["SLA atendido", "94%"], ["Conversao", "3,8%"]].map(([label, value]) => <div key={label} className="rounded-md border p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</div></> : <div className="grid gap-4"><label className="flex items-center justify-between rounded-md border p-3 text-sm">Checkout V2 <input type="checkbox" checked={checkoutV2} onChange={() => { setCheckoutV2(!checkoutV2); say(`Feature flag Checkout V2 ${!checkoutV2 ? "ativada" : "desativada"}.`); }} /></label><div className="rounded-md bg-muted p-3 text-sm"><ShieldCheck className="mr-2 inline size-4" /> Auditoria: admin alterou feature flags agora.</div></div>}</Workspace>;
}

function Workspace({ module, notice, children }: { module: SystemModule; notice: string; children: React.ReactNode }) { return <section className="mt-8 grid gap-5"><div><h2 className="text-xl font-semibold">Ambiente interativo</h2><p className="mt-1 text-sm text-muted-foreground">Dados simulados persistem neste navegador para testes repetiveis.</p></div><Card><CardHeader><CardTitle>{module.name}</CardTitle><CardDescription>{module.features.join(" · ")}</CardDescription></CardHeader><CardContent>{children}</CardContent></Card>{notice && <p role="status" aria-live="polite" className="rounded-md border border-primary/30 bg-primary/5 p-3 text-sm">{notice}</p>}</section>; }
