export type EnrichedChallengeContent = {
  concept: string;
  example: string;
  steps: string[];
  evidence: string[];
  commonMistakes: string[];
};

const base: Record<number, EnrichedChallengeContent> = {
  1: { concept: "Qualidade é a capacidade de um produto atender necessidades reais com segurança, eficácia e uma experiência adequada — não apenas não apresentar defeitos.", example: "Um checkout pode calcular o total certo e ainda ter qualidade ruim se demora 20 segundos, não informa o erro do cartão ou não funciona no celular.", steps: ["Liste quem usa o produto e qual resultado espera.", "Separe dimensões relevantes: funcionalidade, desempenho, acessibilidade, segurança e operação.", "Relacione cada dimensão a um risco observável.", "Tome uma posição e declare o que ainda não foi validado."], evidence: ["Tabela dimensão → risco → evidência", "Exemplos de impacto para usuário e negócio"], commonMistakes: ["Reduzir qualidade a quantidade de bugs", "Confundir conformidade com utilidade", "Dar opinião sem explicar o impacto"] },
  2: { concept: "QA participa da prevenção e da aprendizagem sobre qualidade durante todo o ciclo; não é apenas a pessoa que executa testes no fim.", example: "No refinamento, QA pode descobrir que a regra de recuperação de senha não define expiração do link antes de qualquer código existir.", steps: ["Separe atividades de prevenção, detecção e aprendizagem.", "Identifique onde QA colabora com produto, dev e design.", "Explique o valor gerado por cada atividade.", "Marque limites: QA não substitui a responsabilidade do time."], evidence: ["Tabela atividade → papel → risco reduzido", "Uma pergunta de refinement que evita retrabalho"], commonMistakes: ["Tratar QA como gatekeeper", "Listar ferramentas em vez de responsabilidades", "Assumir que automação é sinônimo de QA"] },
  3: { concept: "Quality Assurance (QA) é prevenção e melhoria do processo; Quality Control (QC) é avaliação do produto para encontrar desvios. Os dois se complementam.", example: "Definir critérios de aceite é QA; executar cenários do checkout e registrar uma falha é QC.", steps: ["Classifique cada ação pelo momento em que acontece.", "Explique se ela previne, detecta ou aprende com um problema.", "Mostre como uma ação de QC pode gerar melhoria de QA.", "Evite transformar a distinção em silos de responsabilidade."], evidence: ["Matriz QA/QC com justificativa", "Risco coberto por cada ação"], commonMistakes: ["Dizer que QA só acontece antes e QC só depois", "Usar a sigla sem explicar o efeito", "Ignorar a responsabilidade compartilhada"] },
  4: { concept: "Testar verifica comportamentos escolhidos; qualidade inclui também valor, uso, confiança, operação e consequências que um teste isolado pode não revelar.", example: "Uma busca pode passar nos casos funcionais e ainda ser inútil porque não tolera acentos ou retorna resultados sem relevância.", steps: ["Liste o que um teste funcional confirmaria.", "Procure riscos de experiência, dados, operação e contexto.", "Escolha uma evidência para cada risco importante.", "Explique o que continuaria desconhecido após os testes."], evidence: ["Mapa comportamento → dimensão de qualidade", "Risco residual explícito"], commonMistakes: ["Usar 'não testado' como sinônimo de 'quebrado'", "Confundir cobertura com confiança", "Esquecer o usuário"] },
  5: { concept: "O custo de um defeito cresce quando ele é descoberto tarde, alcança mais pessoas ou afeta dados e dinheiro. Prioridade precisa considerar impacto e contexto.", example: "Um erro de cobrança em produção normalmente merece investigação antes de um desalinhamento visual numa tela interna.", steps: ["Estime alcance e impacto do problema.", "Considere reversibilidade e urgência do momento.", "Compare com os demais riscos disponíveis.", "Registre a decisão e o risco aceito."], evidence: ["Ranking com critérios", "Impacto, alcance e reversibilidade por item"], commonMistakes: ["Priorizar pelo barulho do solicitante", "Confundir severidade com prioridade", "Não registrar o que ficou para depois"] },
  6: { concept: "Erro é uma ação ou decisão humana; defeito é a imperfeição introduzida no artefato; falha é o comportamento incorreto observado. Bug é um termo informal que pode cobrir a cadeia.", example: "Uma regra mal interpretada (erro) gera uma fórmula incorreta (defeito) e o cliente vê um total errado (falha).", steps: ["Reconstrua a sequência causal.", "Classifique cada evento sem usar bug para tudo.", "Indique a evidência que prova o comportamento observado.", "Sugira uma prevenção para a origem."], evidence: ["Linha do tempo erro → defeito → falha", "Evidência do resultado incorreto"], commonMistakes: ["Culpar uma pessoa em vez de analisar o sistema", "Tratar causa e sintoma como a mesma coisa", "Usar terminologia sem exemplo"] },
  7: { concept: "Qualidade é responsabilidade compartilhada; cada papel contribui com decisões e evidências diferentes, e o QA ajuda o time a tornar o risco visível.", example: "Produto esclarece valor, dev controla implementação, design cuida da experiência e QA investiga riscos — ninguém consegue garantir qualidade sozinho.", steps: ["Identifique os papéis envolvidos.", "Distribua responsabilidades por etapa.", "Mostre onde existe colaboração e revisão.", "Proponha uma ação concreta para o time."], evidence: ["Matriz papel → contribuição → saída", "Mensagem profissional sem tom defensivo"], commonMistakes: ["Responder culpando ou absolvendo um papel", "Confundir responsabilidade com execução isolada", "Não propor mudança de processo"] },
  8: { concept: "Quality Engineering amplia a qualidade para o desenho do sistema, feedback rápido, automação adequada, observabilidade e prevenção de falhas.", example: "Em vez de apenas testar uma API instável, o time pode melhorar contrato, dados de teste, telemetria e isolamento do ambiente.", steps: ["Descreva o fluxo atual e seus pontos de falha.", "Escolha uma melhoria preventiva e uma de feedback.", "Defina como medir se a melhoria funcionou.", "Considere custo de manutenção."], evidence: ["Fluxo antes/depois", "Métrica ou sinal de melhoria"], commonMistakes: ["Tratar QE como nome novo para automação", "Propor ferramenta sem problema", "Ignorar custo operacional"] },
  9: { concept: "SDLC é o ciclo de vida do desenvolvimento. A contribuição de QA começa na descoberta e continua após a entrega, não fica concentrada na execução final.", example: "Uma mudança de login pode gerar perguntas no discovery, critérios no refinement, testes durante o desenvolvimento e monitoramento após o deploy.", steps: ["Liste as etapas do ciclo.", "Associe uma ação de QA a cada etapa.", "Defina o artefato ou decisão produzida.", "Priorize ações que reduzam retrabalho."], evidence: ["Mapa etapa → ação → resultado", "Risco prevenido em cada ponto"], commonMistakes: ["Colocar QA apenas antes da release", "Listar atividades sem saída verificável", "Esquecer operação e aprendizado"] },
  10: { concept: "STLC organiza o trabalho de teste: análise, planejamento, desenho, ambiente, execução, defeitos e encerramento. Ele dá visibilidade ao que foi e não foi coberto.", example: "Para recuperação de senha, a análise identifica expiração e abuso; o planejamento define escopo; a execução gera evidências e defeitos.", steps: ["Defina objetivo e riscos.", "Escolha cobertura e dados.", "Prepare casos e ambiente.", "Execute, registre desvios e encerre com risco residual."], evidence: ["Plano em etapas", "Critérios de entrada e saída", "Resumo de execução"], commonMistakes: ["Confundir STLC com uma lista de cliques", "Começar sem entender o risco", "Encerrar sem declarar limitações"] },
  11: { concept: "Shift Left significa antecipar perguntas, exemplos e verificações para reduzir o custo de descobrir problemas tarde.", example: "Perguntar como um e-mail já usado deve ser tratado no refinement evita implementação, teste e retrabalho desnecessários.", steps: ["Leia a história como uma especificação incompleta.", "Liste ambiguidades e riscos antes do código.", "Transforme perguntas em critérios ou exemplos.", "Explique qual defeito cada pergunta previne."], evidence: ["Perguntas priorizadas", "Critério de aceite ou exemplo resultante"], commonMistakes: ["Fazer perguntas cosméticas", "Confundir antecipação com burocracia", "Não conectar pergunta a risco"] },
  12: { concept: "Shift Right usa sinais de produção para aprender sobre comportamento real, detectar regressões e decidir se uma liberação deve avançar, pausar ou voltar.", example: "Uma liberação gradual de login deve acompanhar erro, conversão, latência e chamados antes de atingir toda a base.", steps: ["Escolha sinais técnicos e de negócio.", "Defina baseline e limiares.", "Associe cada sinal a uma ação.", "Inclua comparação antes/depois."], evidence: ["Painel mínimo de sinais", "Regra de decisão para avançar ou reverter"], commonMistakes: ["Monitorar só disponibilidade", "Escolher métrica sem ação", "Confundir ausência de alerta com ausência de risco"] },
  13: { concept: "Continuous Testing distribui feedback de qualidade ao longo do pipeline, escolhendo a camada mais barata capaz de detectar cada risco.", example: "Uma regra de desconto pode ser validada em unidade, contrato e poucos fluxos E2E, em vez de repetir tudo na tela.", steps: ["Classifique riscos por camada.", "Defina gatilho e duração de cada teste.", "Escolha gates proporcionais ao risco.", "Planeje dados, isolamento e manutenção."], evidence: ["Pipeline por etapas", "Quality gate e justificativa", "Risco residual"], commonMistakes: ["Rodar tudo em todos os commits", "Medir quantidade de testes", "Ignorar flakiness e tempo de feedback"] },
};

const remaining: Record<number, EnrichedChallengeContent> = {
  14: { concept: "Quality Engineering transforma qualidade em uma propriedade do sistema e do processo, usando prevenção, feedback rápido e melhoria contínua.", example: "Um time que só testa no fim pode antecipar exemplos, contratos, dados confiáveis e telemetria para reduzir retrabalho.", steps: ["Descreva o fluxo atual.", "Encontre uma causa de reatividade.", "Proponha uma prevenção e um feedback rápido.", "Defina como medir a mudança."], evidence: ["Fluxo antes/depois", "Métrica de melhoria"], commonMistakes: ["Propor ferramenta sem problema", "Confundir QE com automação"] },
  15: { concept: "No SDLC, QA ajuda a tornar risco e qualidade visíveis desde a descoberta até a operação.", example: "Uma alteração de login precisa de perguntas no discovery, critérios no refinement, testes durante a implementação e sinais após release.", steps: ["Liste as fases do ciclo.", "Associe uma ação de QA a cada fase.", "Defina a saída de cada ação.", "Priorize prevenção."], evidence: ["Mapa fase → ação → saída", "Risco coberto"], commonMistakes: ["Concentrar tudo no fim", "Esquecer pós-produção"] },
  16: { concept: "STLC organiza análise, planejamento, desenho, preparação, execução, defeitos e encerramento para que a cobertura seja explícita.", example: "Em recuperação de senha, o fluxo precisa incluir expiração, abuso, mensagens e confirmação de mudança.", steps: ["Defina objetivo e risco.", "Escolha cobertura e dados.", "Execute e registre evidências.", "Encerre declarando limitações."], evidence: ["Plano de teste", "Resumo de execução", "Risco residual"], commonMistakes: ["Confundir etapas com cliques", "Não declarar o que ficou fora"] },
  17: { concept: "Shift Left antecipa perguntas e exemplos para evitar que ambiguidades virem código e defeitos caros.", example: "Perguntar o que acontece com um e-mail já cadastrado evita uma regra incompleta no backend.", steps: ["Leia a história como uma especificação incompleta.", "Liste ambiguidades.", "Transforme-as em exemplos ou critérios.", "Relacione cada uma ao risco prevenido."], evidence: ["Perguntas priorizadas", "Critérios resultantes"], commonMistakes: ["Perguntas sem impacto", "Burocratizar o refinement"] },
  18: { concept: "Um bom refinement produz entendimento compartilhado e critérios testáveis antes da implementação.", example: "Para alterar e-mail, pergunte sobre confirmação, sessão, duplicidade, notificações e rollback.", steps: ["Separe regra, exceção e estado.", "Pergunte pelos casos de erro.", "Peça exemplos concretos.", "Registre decisões e pendências."], evidence: ["Checklist de perguntas", "Exemplos Given/When/Then"], commonMistakes: ["Perguntar só sobre happy path", "Não registrar a decisão"] },
  19: { concept: "Shift Right usa sinais reais para aprender após a liberação e decidir se o produto deve avançar, pausar ou reverter.", example: "Uma liberação gradual de login deve acompanhar erro, latência, conversão e suporte.", steps: ["Escolha sinais técnicos e de negócio.", "Defina baseline e limiares.", "Associe sinal a ação.", "Compare antes e depois."], evidence: ["Painel mínimo", "Regra de decisão"], commonMistakes: ["Métrica sem ação", "Monitorar só disponibilidade"] },
  20: { concept: "Continuous Testing distribui testes por camadas e momentos, dando feedback rápido sem repetir a mesma verificação cara.", example: "Uma regra de desconto pode ter teste unitário, contrato e poucos fluxos E2E representativos.", steps: ["Classifique o risco por camada.", "Defina gatilho e duração.", "Escolha gates proporcionais.", "Planeje isolamento e manutenção."], evidence: ["Pipeline desenhado", "Quality gates", "Risco residual"], commonMistakes: ["Rodar tudo sempre", "Medir volume em vez de confiança", "Ignorar testes instáveis"] },
};

export function getBaseChallengeContent(order: number) { return base[order] ?? remaining[order] ?? null; }
