import type { EnrichedChallengeContent } from "./base-content";

const modules: Record<string, EnrichedChallengeContent> = {
  "1.1": { concept: "Princípios de teste orientam decisões: testes mostram presença de defeitos, não provam ausência; testes exaustivos são inviáveis; contexto e risco definem a melhor cobertura.", example: "Um cadastro com 30 combinações não precisa de todas as combinações se classes equivalentes, limites e riscos forem cobertos com intenção.", steps: ["Identifique o princípio envolvido.", "Relacione-o ao risco do cenário.", "Escolha uma técnica ou decisão proporcional.", "Declare o que ficará fora e por quê."], evidence: ["Relação princípio → decisão → risco", "Exemplos representativos"], commonMistakes: ["Citar o princípio sem aplicar", "Prometer cobertura total", "Confundir muitos testes com boa cobertura"] },
  "1.2": { concept: "Técnicas de teste reduzem o espaço de combinações e tornam a seleção justificável: equivalência, limites, decisão, estados, pairwise, exploratório e risco.", example: "Para um campo de idade de 18 a 65, testar 18, 19, 64, 65, 17 e 66 informa mais que escolher valores aleatórios.", steps: ["Descreva a regra e suas fronteiras.", "Separe comportamentos diferentes.", "Escolha valores ou transições representativas.", "Explique por que cada caso existe."], evidence: ["Tabela da técnica aplicada", "Casos derivados com justificativa"], commonMistakes: ["Aplicar técnica sem entender a regra", "Duplicar casos equivalentes", "Esquecer inválidos e transições"] },
  "1.3": { concept: "Cenário descreve uma intenção de cobertura; caso de teste detalha pré-condição, dados, passos e oráculo. A granularidade precisa permitir execução e revisão.", example: "‘Comprar com cupom válido’ é cenário; preparar carrinho, aplicar QA10 e conferir total são detalhes do caso.", steps: ["Defina objetivo e pré-condição.", "Escolha dados controlados.", "Escreva passos observáveis.", "Defina resultado esperado verificável."], evidence: ["Casos positivos e negativos", "Oráculo e dados explícitos"], commonMistakes: ["Escrever passos sem objetivo", "Usar ‘funciona’ como oráculo", "Misturar vários comportamentos num caso"] },
  "1.4": { concept: "Requisitos testáveis são claros, completos, consistentes e verificáveis. QA ajuda a revelar ambiguidades antes que virem interpretação divergente.", example: "‘Login rápido’ precisa de uma medida, contexto e limite; sem isso não há resultado esperado auditável.", steps: ["Separe regra, exceção e condição.", "Procure termos subjetivos e lacunas.", "Faça perguntas de negócio e dados.", "Converta respostas em critérios observáveis."], evidence: ["Checklist de testabilidade", "Perguntas e critérios revisados"], commonMistakes: ["Aceitar adjetivos vagos", "Testar requisito que ninguém decidiu", "Confundir critério com implementação"] },
  "1.5": { concept: "BDD usa exemplos compartilhados para conectar comportamento de negócio, desenvolvimento e teste. Given/When/Then descreve intenção, não detalhes frágeis de UI.", example: "Dado um carrinho acima de R$200, quando aplico QA10, então o desconto reduz o subtotal e o frete segue a regra.", steps: ["Escreva o comportamento pelo valor entregue.", "Defina contexto mínimo.", "Descreva ação e resultado observável.", "Use exemplos para remover ambiguidades."], evidence: ["Cenários Gherkin", "Exemplos de regra e exceção"], commonMistakes: ["Transformar BDD em script de clique", "Usar Given gigante", "Esconder regra no Then"] },
  "1.6": { concept: "Um bug report útil permite reproduzir, avaliar impacto e decidir. Título, ambiente, passos, esperado, atual e evidência precisam formar uma história verificável.", example: "‘Checkout falha’ é fraco; ‘PIX retorna 500 ao pagar pedido com cupom QA10 em Safari 17’ orienta investigação.", steps: ["Confirme o comportamento e o alcance.", "Isole passos mínimos.", "Registre ambiente e dados.", "Explique impacto, evidência e hipótese sem prescrever correção."], evidence: ["Bug report reproduzível", "Screenshot, vídeo, request ou log adequado"], commonMistakes: ["Misturar vários defeitos", "Usar severidade como impacto vazio", "Escrever solução em vez de comportamento"] },
  "1.7": { concept: "Testar Web envolve comportamento, navegador, rede, viewport, sessão, cache, acessibilidade e interação entre cliente e servidor.", example: "Uma tela pode mostrar 200 no Network e ainda renderizar dados antigos por estado ou cache no cliente.", steps: ["Reproduza em viewport e navegador definidos.", "Observe UI, Console e Network.", "Compare request, response e estado renderizado.", "Teste recuperação, teclado e responsividade quando relevante."], evidence: ["Matriz browser/viewport", "Request/response e screenshot"], commonMistakes: ["Testar só o caminho feliz", "Ignorar console e rede", "Confundir problema visual com API"] },
  "1.8": { concept: "Teste de API valida contrato, estado, autenticação, autorização, dados, idempotência e erros — independentemente da tela.", example: "Um POST de pedido precisa rejeitar payload inválido, impedir acesso a pedido de outro usuário e persistir o estado correto.", steps: ["Leia método, schema e status esperados.", "Cubra sucesso, validação e falha.", "Varie credenciais e propriedade do recurso.", "Confirme estado antes e depois."], evidence: ["Requests reproduzíveis", "Response, status e estado persistido"], commonMistakes: ["Validar só status 200", "Ignorar autorização", "Deixar massa residual"] },
  "1.9": { concept: "Testes de banco verificam persistência, integridade, transação, isolamento, consistência e consultas — sem depender apenas do que a UI exibe.", example: "A tela confirma exclusão, mas a consulta revela registros órfãos ou dados ainda acessíveis por outra conta.", steps: ["Identifique entidades e relações.", "Observe estado antes da ação.", "Execute o fluxo e consulte o estado.", "Verifique rollback, duplicidade e isolamento."], evidence: ["Consulta de verificação", "Estado antes/depois", "Resultado de integridade"], commonMistakes: ["Alterar produção sem controle", "Usar banco como única prova", "Ignorar cleanup e concorrência"] },
  "1.10": { concept: "Git faz parte da qualidade por rastrear mudanças, revisão, isolamento e reversão. QA precisa entender diff, branch, commit e histórico suficiente para investigar.", example: "Um diff pequeno que muda uma condição de desconto pode justificar regressão focada mesmo sem alterar a tela.", steps: ["Leia a mudança e seu contexto.", "Relacione arquivos a riscos.", "Escolha testes proporcionais ao diff.", "Registre commit e evidência da validação."], evidence: ["Diff analisado", "Matriz mudança → risco → teste"], commonMistakes: ["Testar só o título da PR", "Confundir tamanho do diff com risco", "Não registrar versão validada"] },
  "1.11": { concept: "Automação deve dar feedback confiável, rápido e sustentável. A camada escolhida precisa combinar custo, estabilidade, manutenção e valor do risco.", example: "Uma regra de cálculo é candidata a teste de unidade; a jornada crítica de pagamento merece poucos E2E estáveis.", steps: ["Escolha um comportamento estável e valioso.", "Defina dados e oráculo determinístico.", "Isole dependências quando possível.", "Planeje diagnóstico e manutenção da falha."], evidence: ["Teste executável", "Relatório de execução", "Justificativa da camada"], commonMistakes: ["Automatizar fluxo instável", "Usar sleep como sincronização", "Medir quantidade em vez de confiança"] },
  "1.12": { concept: "CI/CD deve entregar feedback e segurança em etapas: validações rápidas cedo, testes de integração e gates de risco antes do deploy.", example: "Lint e unidade bloqueiam o commit; contrato e integração rodam na PR; smoke e monitoramento protegem a produção.", steps: ["Desenhe estágios e gatilhos.", "Associe teste e gate a um risco.", "Defina artefatos e logs úteis.", "Planeje retry, flakiness e rollback."], evidence: ["Pipeline YAML ou diagrama", "Quality gates", "Estratégia de falha"], commonMistakes: ["Pipeline sem gate real", "Rodar tudo serialmente", "Esconder falha com retry infinito"] },
  "1.13": { concept: "Performance é comportamento sob carga, tempo e recursos. O teste precisa definir cenário, métrica, baseline, percentis e limite aceitável.", example: "Média de 300ms pode esconder p95 de 4s; usuários sentem a cauda, não apenas a média.", steps: ["Defina jornada e perfil de carga.", "Escolha métricas e baseline.", "Execute de forma controlada.", "Investigue gargalo e declare limite."], evidence: ["Plano de carga", "p50/p95/p99, erro e throughput", "Comparação com baseline"], commonMistakes: ["Testar só uma requisição", "Olhar apenas média", "Gerar carga sem autorização"] },
  "1.14": { concept: "Segurança em QA inclui autenticação, autorização, entrada, exposição de dados, sessão e abuso. O objetivo é encontrar risco sem explorar irresponsavelmente.", example: "Um usuário autenticado conseguir consultar o pedido de outra conta é falha de autorização horizontal.", steps: ["Mapeie dado e ação sensíveis.", "Varie identidade, papel e entrada.", "Observe resposta e efeitos colaterais.", "Registre impacto e forma segura de reproduzir."], evidence: ["Request/response sanitizada", "Matriz papel → recurso → ação"], commonMistakes: ["Testar em dados reais", "Confundir login com autorização", "Expor segredo na evidência"] },
  "1.15": { concept: "Acessibilidade deve ser testada como operabilidade: nome, foco, teclado, contraste, semântica, mensagens e tecnologia assistiva.", example: "Um erro só em vermelho pode ser invisível para quem não percebe cor; o campo precisa de nome e mensagem associados.", steps: ["Percorra o fluxo só com teclado.", "Verifique foco e ordem de leitura.", "Inspecione nome, estado e mensagem.", "Confirme contraste e zoom."], evidence: ["Checklist por critério", "Vídeo de teclado ou árvore acessível", "Contraste medido"], commonMistakes: ["Tratar acessibilidade como screenshot", "Usar cor como único feedback", "Consertar sem testar leitor de tela"] },
  "1.16": { concept: "Mobile combina viewport, touch, rede variável, orientação, permissões, teclado virtual, interrupção e diferenças de plataforma.", example: "Um formulário pode ficar impossível quando o teclado cobre o botão ou quando a conexão cai durante o upload.", steps: ["Defina dispositivos e orientações representativos.", "Teste touch, teclado e rolagem.", "Interrompa rede, app e permissões.", "Compare comportamento e evidência por plataforma."], evidence: ["Matriz device/orientação", "Vídeo do fluxo", "Condições de rede"], commonMistakes: ["Reduzir mobile a largura", "Ignorar interrupções", "Testar só em emulador sem declarar"] },
  "1.17": { concept: "Métricas de QA devem apoiar decisões: risco coberto, defeitos escapados, tempo de feedback, estabilidade e resultado para usuário — não vaidade.", example: "Contar casos executados não revela qualidade se os cenários não cobrem riscos e os testes vivem quebrados.", steps: ["Defina a decisão que a métrica apoiará.", "Escolha medida e fonte confiáveis.", "Combine volume com contexto e tendência.", "Defina ação quando o sinal mudar."], evidence: ["Métrica com fórmula e fonte", "Dashboard ou tabela", "Ação associada ao limiar"], commonMistakes: ["Usar 100% como objetivo cego", "Comparar times sem contexto", "Medir o que é fácil em vez do que importa"] },
};

export function getFundamentalsContent(module: string) {
  const key = module.match(/^(1\.\d+)/)?.[1];
  return key ? modules[key] ?? null : null;
}
