export type RoadmapChallengeType = "INVESTIGATE" | "TEST" | "BUILD" | "DECIDE" | "COMMUNICATE";

export type RoadmapChallenge = {
  id: string;
  order: number;
  module: string;
  title: string;
  type: RoadmapChallengeType;
  context: string;
  prompt: string;
  deliverable: string;
  rubric: string[];
};

/** Roteiro visível no desafio. A missão continua autoral; esta estrutura dá
 * apoio sem entregar a resposta pronta. */
export function challengeInstructions(challenge: RoadmapChallenge) {
  const byType: Record<RoadmapChallengeType, string[]> = {
    INVESTIGATE: ["Leia o contexto e separe fatos de suposições.", "Liste hipóteses ou lacunas antes de concluir.", "Registre a evidência que sustentaria sua conclusão."],
    TEST: ["Defina o comportamento e a pré-condição.", "Escolha dados que cubram o risco descrito.", "Escreva resultado esperado observável, não genérico."],
    BUILD: ["Escolha uma estrutura simples para o artefato.", "Preencha-a usando somente as regras do contexto.", "Revise se outra pessoa conseguiria executar ou discutir sua entrega."],
    DECIDE: ["Identifique as opções e o risco de cada uma.", "Defina o critério que pesa mais neste contexto.", "Tome uma posição e declare o risco residual."],
    COMMUNICATE: ["Comece pelo fato e pelo impacto.", "Use linguagem clara para o público do cenário.", "Feche com uma ação ou pedido objetivo."],
  };
  return byType[challenge.type];
}

// Primeira fatia autoral do roadmap. Cada item tem um contexto e uma régua
// próprios; não é uma variação automática do mesmo briefing.
export const qaDoZeroChallenges: RoadmapChallenge[] = [
  { id: "qz-001-qualidade-percebida", order: 1, module: "Base — entendendo qualidade", title: "Qualidade não é só ausência de bug", type: "DECIDE", context: "Um app de delivery conclui todos os pedidos, mas abre lentamente, tem contraste ruim e faz usuários desistirem antes de pagar.", prompt: "Você aprovaria a afirmação de que o app tem alta qualidade porque quase não há bugs funcionais? Decida e justifique pelos impactos para usuário e negócio.", deliverable: "Decisão escrita com ao menos três dimensões de qualidade.", rubric: ["Diferencia comportamento correto de experiência útil.", "Considera usuário e negócio.", "Explicita o critério usado para decidir."] },
  { id: "qz-002-papel-qa", order: 2, module: "Base — entendendo qualidade", title: "QA não é só testar", type: "DECIDE", context: "Um time lista estas tarefas: revisar requisito, clicar na tela pronta, automatizar regressão, definir métrica de incidente e aprovar paleta visual.", prompt: "Classifique quais tarefas fazem parte do papel de QA e explique onde existe colaboração com produto, dev ou design.", deliverable: "Tabela de classificação com justificativa por tarefa.", rubric: ["Não reduz QA a execução manual.", "Reconhece responsabilidade compartilhada.", "Justifica fronteiras sem transformar papéis em silos."] },
  { id: "qz-003-qa-qc-checkout", order: 3, module: "Base — entendendo qualidade", title: "Prevenir e detectar no checkout", type: "TEST", context: "Uma nova regra de cupom será liberada no checkout de um e-commerce em duas semanas.", prompt: "Proponha uma ação de Quality Assurance e uma de Quality Control antes da release. Diga quando acontecem e que risco reduzem.", deliverable: "Duas ações com momento, responsável sugerido e risco coberto.", rubric: ["Separa prevenção de detecção.", "Conecta cada ação a um risco real.", "Propõe ações executáveis no ciclo de entrega."] },
  { id: "qz-004-custo-do-bug", order: 4, module: "Base — entendendo qualidade", title: "Priorize pelo impacto, não pelo barulho", type: "DECIDE", context: "Você tem: falha que cobra duas vezes, texto desalinhado, e-mail de confirmação atrasado, busca sem acento e cálculo errado em relatório interno.", prompt: "Defina uma ordem de investigação e explique o impacto, o alcance e a reversibilidade de cada decisão.", deliverable: "Ranking de cinco bugs com justificativa de risco.", rubric: ["Diferencia severidade de prioridade.", "Considera usuários afetados e reversibilidade.", "Evita priorizar só pela facilidade de corrigir."] },
  { id: "qz-005-erro-defeito-falha", order: 5, module: "Base — entendendo qualidade", title: "Erro, defeito ou falha?", type: "DECIDE", context: "Uma regra de arredondamento foi entendida errado por quem programou; o código foi para produção; clientes visualizaram um total incorreto.", prompt: "Classifique cada ponto da sequência como erro humano, defeito no software ou falha observável. Explique a relação entre eles.", deliverable: "Linha do tempo com a classificação e uma frase por etapa.", rubric: ["Usa a terminologia de forma consistente.", "Mostra relação de causa e efeito.", "Não chama toda a cadeia apenas de bug."] },
  { id: "qz-006-responsabilidade", order: 6, module: "Base — entendendo qualidade", title: "Quem é responsável pela qualidade?", type: "COMMUNICATE", context: "Em uma retrospectiva, alguém diz: “qualidade é responsabilidade do QA; se o bug chegou, QA falhou”.", prompt: "Responda à frase como você responderia em um time profissional: sem defensividade, mas deixando papéis e responsabilidades claros.", deliverable: "Mensagem curta para a retrospectiva.", rubric: ["Defende qualidade como responsabilidade compartilhada.", "Mantém tom colaborativo.", "Propõe uma ação concreta de melhoria."] },
  { id: "qz-007-processo-preventivo", order: 7, module: "Base — entendendo qualidade", title: "Do reativo ao preventivo", type: "BUILD", context: "O time só chama QA quando a feature está pronta; os bugs importantes aparecem perto da release.", prompt: "Desenhe um fluxo mínimo que mova a qualidade para antes do código sem criar burocracia inútil.", deliverable: "Fluxo com refinement, critérios de aceite, estratégia e feedback pós-release.", rubric: ["Inclui prevenção antes da implementação.", "Define saídas concretas de cada etapa.", "Mantém o processo proporcional ao time."] },
  { id: "qz-008-sdlc", order: 8, module: "Base — entendendo qualidade", title: "QA ao longo do SDLC", type: "DECIDE", context: "Uma feature passa por descoberta, refinamento, desenvolvimento, revisão, deploy e monitoramento.", prompt: "Indique a contribuição de QA em cada etapa. Priorize ações que reduzem retrabalho.", deliverable: "Mapa SDLC → ação de QA → resultado esperado.", rubric: ["Cobre o ciclo inteiro.", "Evita concentrar QA no final.", "Relaciona ação a prevenção ou evidência."] },
  { id: "qz-009-stlc", order: 9, module: "Base — entendendo qualidade", title: "Planeje um ciclo de testes", type: "BUILD", context: "Uma feature de recuperação de senha será liberada nesta sprint.", prompt: "Monte o STLC da feature, da análise ao encerramento, incluindo critérios de entrada e saída.", deliverable: "Plano em etapas com artefato gerado em cada uma.", rubric: ["Começa por análise e risco.", "Inclui execução, evidência e encerramento.", "Define critérios verificáveis."] },
  { id: "qz-010-shift-left", order: 10, module: "Base — entendendo qualidade", title: "Perguntas que evitam bug", type: "COMMUNICATE", context: "No refinement, a história diz apenas: “como usuário, quero alterar meu e-mail”.", prompt: "Escreva as perguntas que você levaria para o refinement antes de qualquer pessoa desenvolver.", deliverable: "Lista priorizada de perguntas de negócio, segurança e comportamento.", rubric: ["Identifica ambiguidades relevantes.", "Inclui casos de segurança e confirmação.", "Formula perguntas objetivas e acionáveis."] },
  { id: "qz-011-shift-right", order: 11, module: "Base — entendendo qualidade", title: "O que observar depois da release", type: "DECIDE", context: "Uma mudança no login foi liberada gradualmente para 10% da base.", prompt: "Escolha sinais para decidir se a liberação deve avançar, pausar ou reverter.", deliverable: "Painel mínimo de sinais, limiares e ação associada.", rubric: ["Combina sinais técnicos e de jornada.", "Define ação para cada sinal.", "Considera comparação antes/depois da release."] },
  { id: "qz-012-continuous-testing", order: 12, module: "Base — entendendo qualidade", title: "Testes contínuos com intenção", type: "BUILD", context: "O time tem testes unitários, API, E2E e um deploy automatizado, mas roda tudo em toda alteração e o pipeline demora demais.", prompt: "Desenhe onde cada tipo de teste deve rodar e quais falhas devem bloquear a entrega.", deliverable: "Pipeline em etapas, com gatilho e quality gate por camada.", rubric: ["Distribui testes por custo e confiança.", "Define gates proporcionais ao risco.", "Prevê feedback rápido para pull request."] },
  { id: "qz-013-principios", order: 13, module: "Fundamentos de teste", title: "Mais testes não são automaticamente melhor teste", type: "COMMUNICATE", context: "Uma liderança pede “100% de cobertura de todos os fluxos, em todos os navegadores, até sexta”.", prompt: "Explique por que testar tudo é impossível e proponha como transformar o pedido em uma estratégia defensável.", deliverable: "Resposta curta com limites, riscos e alternativa de cobertura.", rubric: ["Explica limites sem soar como recusa vazia.", "Prioriza por risco e valor.", "Distingue cobertura de confiança."] },
  { id: "qz-014-niveis-login", order: 14, module: "Fundamentos de teste", title: "A camada certa para o risco", type: "DECIDE", context: "No login existem: máscara de e-mail, validação de senha, chamada de autenticação, armazenamento de sessão e redirecionamento após entrar.", prompt: "Escolha o nível de teste mais adequado para cada comportamento: unitário, integração, sistema ou aceitação.", deliverable: "Mapa comportamento → nível → justificativa.", rubric: ["Evita usar E2E para toda regra.", "Diferencia integração de comportamento isolado.", "Justifica pelo risco e custo do feedback."] },
  { id: "qz-015-estrategia-login", order: 15, module: "Fundamentos de teste", title: "Cobertura em camadas para login", type: "BUILD", context: "Você vai desenhar a cobertura de login de uma aplicação com web, API de autenticação e banco de usuários.", prompt: "Monte uma estratégia de cobertura por nível, indicando o que não vale duplicar em E2E.", deliverable: "Pirâmide de cobertura com cenários por camada.", rubric: ["Distribui regra, integração e jornada.", "Evita duplicação de cenários caros.", "Inclui falhas de autenticação e sessão."] },
  { id: "qz-016-tipos-ecommerce", order: 16, module: "Fundamentos de teste", title: "Plano de teste não é lista de tipos", type: "TEST", context: "Uma pequena release altera busca, carrinho, checkout e o aviso de privacidade de um e-commerce.", prompt: "Monte um plano que combine pelo menos cinco tipos de teste. Para cada tipo, diga qual risco cobre.", deliverable: "Plano enxuto com tipo, cenário e risco coberto.", rubric: ["Usa tipos com propósito.", "Inclui aspectos funcionais e não funcionais.", "Conecta seleção a uma mudança da release."] },
  { id: "qz-017-regressao-ou-sanity", order: 17, module: "Fundamentos de teste", title: "Smoke, sanity ou regressão?", type: "DECIDE", context: "Após um hotfix no cupom, há 15 minutos antes de liberar. A suite completa leva duas horas.", prompt: "Decida qual recorte de teste executar agora e o que fica como risco residual.", deliverable: "Decisão de cobertura com tempo, escopo e risco residual.", rubric: ["Diferencia objetivo de smoke, sanity e regressão.", "Protege o fluxo crítico alterado.", "Comunica o que não será validado."] },
  { id: "qz-018-positivo-negativo", order: 18, module: "Fundamentos de teste", title: "Cadastro além do caminho feliz", type: "TEST", context: "O cadastro exige nome, e-mail único, senha de 8 caracteres e aceite de termos.", prompt: "Crie casos positivos e negativos representativos, incluindo pelo menos dois limites e uma falha de regra de negócio.", deliverable: "Conjunto de casos com pré-condição, entrada e resultado esperado.", rubric: ["Cobre sucesso e recusa.", "Usa limites relevantes.", "Espera mensagens e estado coerentes."] },
  { id: "qz-019-compra-interrompida", order: 19, module: "Fundamentos de teste", title: "Happy path não é o produto inteiro", type: "TEST", context: "Uma compra comum vai de catálogo a confirmação. No meio do caminho, o usuário pode perder internet, voltar página ou ter cartão recusado.", prompt: "Mapeie o happy path e os principais unhappy paths que merecem cobertura antes da release.", deliverable: "Fluxo principal e mapa de interrupções priorizadas.", rubric: ["Descreve caminho principal com clareza.", "Considera interrupções e recuperação.", "Prioriza os unhappy paths por impacto."] },
  { id: "qz-020-equivalencia", order: 20, module: "Técnicas de teste", title: "Reduza dezenas de valores sem perder risco", type: "TEST", context: "Um campo de idade aceita números inteiros entre 18 e 65. O time propôs testar todos os 48 valores possíveis.", prompt: "Crie classes de equivalência e escolha valores representativos para cada uma.", deliverable: "Classes válidas/inválidas e valores escolhidos.", rubric: ["Separa classes de comportamento distinto.", "Inclui inválidos abaixo e acima do intervalo.", "Evita exemplos redundantes."] },
  { id: "qz-021-valor-limite", order: 21, module: "Técnicas de teste", title: "A borda onde a regra quebra", type: "TEST", context: "Um campo aceita valor de 1 a 100, inclusive.", prompt: "Defina os casos de valor limite e os resultados esperados. Explique por que cada valor existe.", deliverable: "Tabela de entradas 0, 1, 2, 99, 100 e 101 com resultado.", rubric: ["Testa dentro e fora da fronteira.", "Explicita inclusão dos extremos.", "Mantém resultado esperado verificável."] },
  { id: "qz-022-tabela-decisao", order: 22, module: "Técnicas de teste", title: "Frete e cupom sem chute", type: "BUILD", context: "Frete é grátis acima de R$ 200; cupom QA10 dá 10% exceto em itens promocionais; entrega expressa nunca é grátis.", prompt: "Construa uma tabela de decisão que torne as combinações de regra testáveis.", deliverable: "Tabela de condições, ações e cenários derivados.", rubric: ["Modela condições independentes.", "Expõe conflito entre regras.", "Gera cenários executáveis a partir da tabela."] },
  { id: "qz-023-transicao-estados", order: 23, module: "Técnicas de teste", title: "Conta ativa, bloqueada, suspensa e encerrada", type: "BUILD", context: "Uma conta pode ficar ativa, bloqueada por tentativas, suspensa por análise ou encerrada pelo usuário.", prompt: "Modele transições válidas e inválidas e derive cenários de teste desse modelo.", deliverable: "Diagrama/lista de transições e casos derivados.", rubric: ["Define estados e eventos claramente.", "Inclui transições proibidas.", "Deriva testes que verificam estado final e mensagens."] },
  { id: "qz-024-risco", order: 24, module: "Técnicas de teste", title: "Priorize antes de testar", type: "DECIDE", context: "Uma release inclui avatar, exportação CSV, alteração de senha, desconto e dashboard de métricas. O tempo caiu pela metade.", prompt: "Crie uma priorização por probabilidade × impacto e defina o que será testado profundamente, superficialmente ou aceito como risco.", deliverable: "Matriz de risco com plano de cobertura.", rubric: ["Usa critérios consistentes.", "Protege fluxos de maior impacto.", "Declara risco residual sem escondê-lo."] },
  { id: "qz-025-cenarios-checkout", order: 25, module: "Casos e cenários de teste", title: "Cenários de alto nível para checkout", type: "BUILD", context: "O checkout permite produto físico, cupom, endereço, frete e pagamento por cartão ou PIX.", prompt: "Crie cenários de alto nível que ajudem uma pessoa a enxergar a cobertura antes de detalhar passos.", deliverable: "Lista organizada por fluxo, validação, pagamento e recuperação de erro.", rubric: ["Não confunde cenário com passo de clique.", "Cobre regra, variação e interrupção.", "Organiza a cobertura de forma navegável."] },
  { id: "qz-026-caso-completo", order: 26, module: "Casos e cenários de teste", title: "Do cenário ao caso executável", type: "BUILD", context: "A regra diz: cupom QA10 aplica 10% a pedidos acima de R$ 100 e não acumula com promoção.", prompt: "Escreva um caso de teste completo para uma combinação válida e outro para uma combinação recusada.", deliverable: "Casos com pré-condição, dados, passos e resultado esperado.", rubric: ["Torna regra e dados explícitos.", "Mantém passos reproduzíveis.", "Distingue esperado de observação."] },
  { id: "qz-027-pre-condicoes", order: 27, module: "Casos e cenários de teste", title: "O teste que falha antes de começar", type: "TEST", context: "Um caso diz “cancele um pedido e valide o reembolso”, mas não informa estado do pedido, meio de pagamento nem permissões do usuário.", prompt: "Identifique as pré-condições ausentes e reescreva o início do caso.", deliverable: "Lista de pré-condições e caso corrigido.", rubric: ["Diferencia dado, permissão e estado do sistema.", "Remove ambiguidade de execução.", "Evita pressupostos escondidos."] },
  { id: "qz-028-evidencia-adequada", order: 28, module: "Casos e cenários de teste", title: "A prova certa para cada falha", type: "COMMUNICATE", context: "Você encontrou: cálculo divergente, erro 500 na API, foco perdido no modal e dado persistido incorretamente.", prompt: "Escolha a evidência mais útil para cada achado e explique o que ela prova.", deliverable: "Mapa falha → evidência → motivo.", rubric: ["Escolhe prova proporcional ao problema.", "Não depende só de screenshot.", "Facilita reprodução por outra pessoa."] },
  { id: "qz-029-formato-ideal", order: 29, module: "Casos e cenários de teste", title: "Caso formal, checklist ou exploração?", type: "DECIDE", context: "Você precisa testar um hotfix simples, validar uma regra crítica de pagamento e investigar uma tela nova sem requisito detalhado.", prompt: "Escolha o formato de teste ideal para cada situação e justifique.", deliverable: "Decisão por situação com trade-off de velocidade e rastreabilidade.", rubric: ["Usa caso formal quando rastreabilidade importa.", "Usa checklist para repetição rápida.", "Reserva exploração para incerteza real."] },
  { id: "qz-030-suite-regressao", order: 30, module: "Casos e cenários de teste", title: "Organize uma suite que o time consiga usar", type: "BUILD", context: "Trinta casos misturam login, catálogo, checkout, pedidos e acessibilidade sem tags ou prioridade.", prompt: "Defina suites, tags e ordem de execução para regressão normal e smoke pós-deploy.", deliverable: "Estrutura de suite com critério de agrupamento.", rubric: ["Agrupa por objetivo e fluxo.", "Permite recorte rápido de smoke.", "Expõe prioridade e dependências."] },
  { id: "qz-031-requisito-funcional", order: 31, module: "Requisitos", title: "Derive testes de um requisito funcional", type: "TEST", context: "“Como cliente, quero agendar uma consulta para escolher o melhor horário disponível.”", prompt: "Derive cenários de teste sem inventar regra que a história não informa. Marque o que precisa ser perguntado.", deliverable: "Cenários derivados e perguntas abertas.", rubric: ["Extrai comportamento explícito.", "Identifica lacunas sem preencher no chute.", "Inclui casos positivos e negativos possíveis."] },
  { id: "qz-032-nfr-ausente", order: 32, module: "Requisitos", title: "O requisito não funcional que ninguém escreveu", type: "DECIDE", context: "Uma história de exportação permite baixar relatório de vendas em CSV, mas não fala de volume, tempo, permissão ou dados sensíveis.", prompt: "Identifique os NFRs ausentes e priorize os que bloqueiam a entrega.", deliverable: "Lista priorizada de NFRs com pergunta de clarificação.", rubric: ["Vai além de performance.", "Considera segurança e confiabilidade.", "Conecta NFR a um risco do negócio."] },
  { id: "qz-033-criterios-aceite", order: 33, module: "Requisitos", title: "Critérios de aceite que podem ser testados", type: "BUILD", context: "História: “como assinante, quero pausar minha assinatura para não ser cobrado no próximo ciclo”.", prompt: "Escreva critérios de aceite claros para pausa, confirmação, efeito na cobrança e retomada.", deliverable: "Critérios verificáveis, sem linguagem vaga.", rubric: ["Descreve condição e resultado.", "Cobre estados e comunicação ao usuário.", "Evita termos como rápido ou correto sem medida."] },
  { id: "qz-034-ambiguidade", order: 34, module: "Requisitos", title: "Perguntas antes do código", type: "INVESTIGATE", context: "O requisito diz: “o sistema deve mostrar os pedidos recentes do usuário rapidamente”.", prompt: "Aponte as ambiguidades e formule perguntas que tornem o requisito testável.", deliverable: "Trechos ambíguos, risco e pergunta correspondente.", rubric: ["Identifica termos subjetivos.", "Questiona escopo e regra de negócio.", "Transforma ambiguidade em decisão possível."] },
  { id: "qz-035-gherkin", order: 35, module: "BDD", title: "Gherkin que descreve comportamento", type: "BUILD", context: "A regra de recuperação de senha exige e-mail cadastrado, link de uso único e expiração em 15 minutos.", prompt: "Escreva cenários Given/When/Then claros para sucesso, e-mail inexistente e link expirado.", deliverable: "Feature com cenários independentes.", rubric: ["Descreve comportamento, não implementação.", "Mantém Given, When e Then com papéis claros.", "Cobre falhas relevantes da regra."] },
  { id: "qz-036-outline", order: 36, module: "BDD", title: "Quando transformar em Scenario Outline", type: "BUILD", context: "Três cenários validam a mesma regra de limite de transferência com valores 0, 1 e 50.001.", prompt: "Decida se Scenario Outline faz sentido e escreva Examples representativos, sem esconder comportamento distinto em uma tabela gigante.", deliverable: "Cenário ou Outline justificado, com exemplos.", rubric: ["Evita repetição sem forçar abstração.", "Escolhe dados representativos.", "Mantém saída esperada legível por exemplo."] },
  { id: "qz-037-bug-ou-melhoria", order: 37, module: "Bugs", title: "Bug, melhoria ou requisito ausente?", type: "DECIDE", context: "Uma tela mostra data em formato americano; o requisito não define formato. Um botão abre uma página diferente do rótulo. Um usuário pede modo escuro.", prompt: "Classifique cada situação e diga que evidência ou conversa é necessária antes de abrir ticket.", deliverable: "Tabela situação → classificação → próximo passo.", rubric: ["Não chama toda insatisfação de bug.", "Distingue comportamento divergente de requisito ausente.", "Pede esclarecimento quando falta oráculo."] },
  { id: "qz-038-bug-report", order: 38, module: "Bugs", title: "Bug report que outra pessoa consegue reproduzir", type: "BUILD", context: "Ao aplicar cupom QA10 em um carrinho de R$ 150, o resumo mostra desconto de R$ 10 em vez de R$ 15.", prompt: "Escreva um bug report completo para o problema, incluindo ambiente, dados, passos, esperado, atual e impacto.", deliverable: "Bug report pronto para triagem.", rubric: ["Título descreve sintoma e contexto.", "Passos são mínimos e reproduzíveis.", "Separa esperado, atual e impacto."] },
  { id: "qz-039-titulo-objetivo", order: 39, module: "Bugs", title: "Título que ajuda na busca e triagem", type: "COMMUNICATE", context: "O ticket foi aberto como “checkout quebrado urgente”. O problema real ocorre somente ao usar PIX depois de alterar o endereço.", prompt: "Reescreva o título e explique por que ele é mais útil para time e histórico.", deliverable: "Título revisado e justificativa curta.", rubric: ["Inclui comportamento e condição relevante.", "Evita julgamento vago como quebrado ou urgente.", "Permite localizar duplicidade depois."] },
  { id: "qz-040-expected-actual", order: 40, module: "Bugs", title: "Esperado e atual sem ruído", type: "COMMUNICATE", context: "Um reporte diz: “deu erro, deveria funcionar”. O console mostra 401 e a tela deixa o usuário em loading infinito após expirar sessão.", prompt: "Reescreva esperado e atual para que alguém entenda o problema sem assistir à execução.", deliverable: "Campos Expected e Actual revisados.", rubric: ["Descreve comportamento observável.", "Inclui contexto de sessão expirada.", "Não sugere solução dentro do resultado atual."] },
  { id: "qz-041-evidencia-bug", order: 41, module: "Bugs", title: "Screenshot, vídeo, log ou request?", type: "DECIDE", context: "Você encontrou um desalinhamento visual, uma resposta 500 intermitente, um cálculo divergente e uma requisição enviada duas vezes.", prompt: "Escolha a evidência principal e complementar para cada caso.", deliverable: "Mapa defeito → evidência → o que ela comprova.", rubric: ["Escolhe evidência adequada à camada do defeito.", "Combina provas quando necessário.", "Evita anexos que não ajudam a reprodução."] },
  { id: "qz-042-severidade", order: 42, module: "Bugs", title: "Severidade pelo dano técnico", type: "DECIDE", context: "Compare: texto cortado em mobile; todos os pagamentos PIX recusados; exportação CSV perde colunas opcionais; painel admin abre para usuário comum.", prompt: "Defina severidade para cada achado e justifique pelo impacto no sistema e nos dados.", deliverable: "Classificação de severidade com critério objetivo.", rubric: ["Diferencia cosmético, alto impacto e bloqueante.", "Considera segurança e alcance.", "Não confunde urgência comercial com severidade."] },
  { id: "qz-043-prioridade", order: 43, module: "Bugs", title: "Prioridade depende do contexto", type: "DECIDE", context: "Há um bug crítico em uma área interna usada uma vez por mês e uma falha média no checkout durante campanha de Black Friday.", prompt: "Defina prioridade de correção, explique a diferença para severidade e comunique o risco de cada escolha.", deliverable: "Decisão de prioridade com contexto de negócio.", rubric: ["Separa dano técnico de urgência.", "Usa contexto temporal e alcance.", "Declara trade-off e mitigação."] },
  { id: "qz-044-triagem", order: 44, module: "Bugs", title: "Triagem com tempo limitado", type: "DECIDE", context: "Você tem 20 minutos e oito tickets novos: duplicado provável, pagamento duplicado, erro visual, falha sem repro, possível vazamento, lentidão e dois regressivos.", prompt: "Defina a ordem de triagem e quais informações precisa obter antes de decidir correção.", deliverable: "Fila priorizada com pergunta/ação por ticket.", rubric: ["Contém risco crítico primeiro.", "Não fecha conclusão sem evidência.", "Identifica duplicidade e necessidade de reprodução."] },
  { id: "qz-045-nao-reproduz", order: 45, module: "Bugs", title: "Cannot reproduce não encerra investigação", type: "INVESTIGATE", context: "Suporte relata que o aplicativo fechou ao anexar foto; QA não reproduz no próprio aparelho e não há vídeo.", prompt: "Monte um plano de investigação antes de marcar o ticket como não reproduzível.", deliverable: "Hipóteses, dados a coletar e testes de isolamento.", rubric: ["Pede versão, dispositivo e contexto necessários.", "Cria hipóteses testáveis.", "Evita culpar usuário ou encerrar cedo."] },
  { id: "qz-046-duplicidade", order: 46, module: "Bugs", title: "Dois tickets, um defeito?", type: "INVESTIGATE", context: "Um ticket diz que desconto some ao atualizar a página; outro diz que total volta ao valor cheio depois de trocar endereço.", prompt: "Defina como investigar se são duplicados, relacionados ou defeitos independentes.", deliverable: "Comparação de sintomas, passos, causa provável e decisão.", rubric: ["Compara condições e não só título.", "Distingue causa comum de sintoma parecido.", "Registra vínculo entre tickets quando necessário."] },
  { id: "qz-047-wont-fix", order: 47, module: "Bugs", title: "Quando aceitar um defeito", type: "DECIDE", context: "Um filtro secundário falha em navegador antigo que representa 0,4% da base; corrigir pode atrasar uma correção de fraude.", prompt: "Decida entre corrigir, mitigar, adiar ou aceitar. Registre as condições para revisitar a decisão.", deliverable: "Decisão de trade-off com plano de acompanhamento.", rubric: ["Avalia impacto, alcance e custo.", "Não trata won't fix como abandono.", "Propõe mitigação e gatilho de revisão."] },
  { id: "qz-048-rca", order: 48, module: "Bugs", title: "RCA sem caça às bruxas", type: "INVESTIGATE", context: "Uma alteração de imposto chegou à produção com cálculo errado. Havia requisito ambíguo, teste manual no fim e nenhuma validação automatizada da regra.", prompt: "Faça uma análise de causa raiz que diferencie causa, fatores contribuintes e ações preventivas.", deliverable: "RCA com linha do tempo, causas e plano de prevenção.", rubric: ["Vai além de apontar uma pessoa.", "Conecta processo, requisito e cobertura.", "Propõe ações verificáveis de prevenção."] },
  { id: "qz-049-origem-da-falha", order: 49, module: "Web", title: "A falha nasceu onde?", type: "DECIDE", context: "Usuário vê botão habilitado, mas a API retorna 403. Em outro caso, a API retorna 200 com total correto, mas a tela mostra valor antigo. Em um terceiro, request nem aparece na aba Network.", prompt: "Indique a origem mais provável de cada falha e a primeira evidência que você procuraria.", deliverable: "Mapa sintoma → hipótese de camada → evidência inicial.", rubric: ["Diferencia cliente, rede e servidor.", "Trata hipótese como hipótese, não certeza.", "Escolhe uma verificação barata antes de escalar."] },
  { id: "qz-050-http-https", order: 50, module: "Web", title: "Transporte também é qualidade", type: "INVESTIGATE", context: "O login funciona em homologação, mas um navegador alerta que a página contém conteúdo misto quando carrega uma imagem de perfil.", prompt: "Explique o risco de HTTP dentro de uma página HTTPS e defina como investigaria a origem.", deliverable: "Hipótese, impacto e passos de investigação.", rubric: ["Explica impacto de conteúdo misto.", "Usa DevTools ou resposta de rede como evidência.", "Distingue página, recurso e cookie seguro."] },
  { id: "qz-051-request-response", order: 51, module: "Web", title: "Leia a conversa entre cliente e servidor", type: "TEST", context: "O login envia e-mail e senha; em caso válido deve receber token e perfil, em caso inválido deve informar erro sem vazar se o e-mail existe.", prompt: "Defina o que validar na request e na response dos dois cenários.", deliverable: "Checklist de request/response para login válido e inválido.", rubric: ["Valida método, payload e status.", "Confere corpo e ausência de dados sensíveis.", "Diferencia autenticação bem-sucedida de erro controlado."] },
  { id: "qz-052-headers", order: 52, module: "Web", title: "O que os headers contam", type: "INVESTIGATE", context: "Uma API responde JSON como texto, uma página exibe conteúdo antigo após deploy e uma chamada autenticada funciona só para alguns usuários.", prompt: "Diga quais headers inspecionar em cada caso e o que cada um pode revelar.", deliverable: "Cenário → headers → interpretação possível.", rubric: ["Inclui content-type, cache e authorization quando relevante.", "Relaciona header a sintoma.", "Evita assumir token válido só porque ele existe."] },
  { id: "qz-053-sessao", order: 53, module: "Web", title: "Sessão não pode sobreviver para sempre", type: "TEST", context: "O produto usa cookie de sessão e mantém uma preferência visual em localStorage. Após uma hora, a sessão deve expirar sem apagar a preferência.", prompt: "Desenhe os testes de persistência, expiração, logout e reabertura do navegador.", deliverable: "Matriz de testes para cookie, sessão e localStorage.", rubric: ["Distingue autenticação de preferência local.", "Valida limpeza no logout.", "Cobre expiração com mensagem e redirecionamento coerentes."] },
  { id: "qz-054-status-codes", order: 54, module: "Web", title: "Status code comunica contrato", type: "DECIDE", context: "Uma API recebe: cadastro duplicado, requisição sem token, recurso inexistente, validação inválida e erro inesperado no banco.", prompt: "Escolha status HTTP adequado para cada situação e justifique do ponto de vista de quem consome a API.", deliverable: "Tabela situação → status → resposta esperada.", rubric: ["Diferencia erro de cliente e servidor.", "Evita devolver 200 para erro de domínio.", "Mantém resposta útil sem vazar detalhe interno."] },
  { id: "qz-055-crud", order: 55, module: "Web", title: "CRUD é mais que quatro verbos", type: "TEST", context: "Uma API de endereço permite criar, consultar, editar parcialmente e excluir endereço do usuário.", prompt: "Crie uma sequência de validação CRUD incluindo autorização e comportamento após exclusão.", deliverable: "Roteiro com chamadas, dados e verificações de estado.", rubric: ["Usa método coerente para cada ação.", "Valida persistência após alteração.", "Tenta acessar recurso de outro usuário."] },
  { id: "qz-056-devtools", order: 56, module: "Web", title: "Investigue antes de abrir bug", type: "INVESTIGATE", context: "Ao salvar perfil, a tela mostra sucesso mas, ao recarregar, o nome antigo volta. Não há erro visível.", prompt: "Descreva o roteiro de investigação usando Network e Console antes de concluir se é UI, API ou persistência.", deliverable: "Passos de DevTools e hipótese por resultado possível.", rubric: ["Inspeciona request e response.", "Compara estado visual com estado retornado.", "Usa console para erros não exibidos pela UI."] },
  { id: "qz-057-cache", order: 57, module: "Web", title: "Quando o deploy parece não ter acontecido", type: "INVESTIGATE", context: "Após corrigir um preço, alguns usuários continuam vendo o valor antigo até fazer hard refresh.", prompt: "Formule hipóteses de cache e proponha experimentos seguros para confirmar onde está a retenção.", deliverable: "Plano de investigação de cache com evidências esperadas.", rubric: ["Considera navegador, CDN e API.", "Usa headers como evidência.", "Evita limpar cache como única explicação."] },
  { id: "qz-058-responsividade", order: 58, module: "Web", title: "O fluxo precisa caber no celular", type: "TEST", context: "Uma tela de checkout foi desenhada em desktop e deve funcionar de 320px a 1440px.", prompt: "Monte uma estratégia de responsividade que teste fluxo, conteúdo, teclado e orientação — não só screenshots.", deliverable: "Matriz de viewport, cenário e oráculo.", rubric: ["Cobre breakpoints representativos.", "Verifica ausência de corte e rolagem horizontal.", "Mantém ação crítica operável em touch e teclado."] },
  { id: "qz-059-cross-browser", order: 59, module: "Web", title: "Compatibilidade com intenção", type: "TEST", context: "O público usa Chrome, Safari mobile, Firefox corporativo e Edge. Há upload de arquivo e um componente de data novo.", prompt: "Defina uma matriz de navegadores proporcional ao risco e explique o que será smoke e o que terá cobertura completa.", deliverable: "Matriz browser × plataforma × cenários críticos.", rubric: ["Baseia seleção em uso e risco.", "Prioriza recursos sensíveis a browser.", "Evita tentar testar tudo igualmente."] },
  { id: "qz-060-acessibilidade-web", order: 60, module: "Web", title: "Feedback que todos conseguem usar", type: "TEST", context: "Um formulário mostra erro em vermelho abaixo do campo e abre modal de confirmação após salvar.", prompt: "Defina verificações para rótulo, foco, teclado, contraste e anúncio de mensagens.", deliverable: "Checklist de acessibilidade do fluxo.", rubric: ["Não usa cor como único sinal.", "Verifica foco ao abrir e fechar modal.", "Inclui associação de erro e leitura por tecnologia assistiva."] },
  { id: "qz-061-api-rest", order: 61, module: "APIs", title: "Explique a API pelo fluxo, não pela sigla", type: "COMMUNICATE", context: "Um aplicativo de finanças lista lançamentos, cria uma despesa e exibe o novo saldo no dashboard.", prompt: "Explique como cliente, API e servidor colaboram nesse fluxo usando linguagem que uma pessoa de produto entenda.", deliverable: "Explicação curta do fluxo com request e response.", rubric: ["Diferencia interface de contrato.", "Usa exemplo de recurso e ação.", "Evita jargão sem explicação."] },
  { id: "qz-062-endpoints-fluxo", order: 62, module: "APIs", title: "Quais endpoints sustentam a jornada?", type: "TEST", context: "Um usuário faz login, lista produtos, adiciona item ao carrinho, paga pedido e consulta o histórico.", prompt: "Mapeie endpoints prováveis e a dependência entre eles para testar essa jornada.", deliverable: "Mapa do fluxo com método, endpoint e dado que atravessa cada etapa.", rubric: ["Identifica dependência de autenticação.", "Inclui leitura e mudança de estado.", "Não inventa endpoint como se fosse certeza; marca suposições."] },
  { id: "qz-063-json-payload", order: 63, module: "APIs", title: "Payload válido, inválido e malformado", type: "INVESTIGATE", context: "A criação de usuário espera nome, e-mail, data de nascimento e preferências opcionais em JSON.", prompt: "Encontre os erros nos payloads: chave com nome errado, vírgula extra, data inválida, tipo numérico no e-mail e preferência desconhecida.", deliverable: "Classificação de payloads e resposta esperada.", rubric: ["Diferencia JSON inválido de dado inválido.", "Considera tipo, formato e campo desconhecido.", "Espera erro específico sem expor stack trace."] },
  { id: "qz-064-parametros", order: 64, module: "APIs", title: "Path, query e body têm responsabilidades", type: "TEST", context: "Você precisa buscar pedido 123, filtrar pedidos por status e período, e criar um novo pedido com itens e endereço.", prompt: "Monte as chamadas usando path params, query params e body corretamente.", deliverable: "Três requests documentadas com objetivo de cada parâmetro.", rubric: ["Usa identificador de recurso no path.", "Usa query para filtro/paginação.", "Mantém dados de criação no body."] },
  { id: "qz-065-autenticacao", order: 65, module: "APIs", title: "Sem credencial também é cenário", type: "TEST", context: "A API exige Bearer token para ver perfil e atualizar endereço.", prompt: "Crie uma bateria de testes para token ausente, inválido, expirado e válido.", deliverable: "Casos de autenticação com status e mensagem esperados.", rubric: ["Cobre ausência, formato e expiração.", "Não confunde 401 com permissão insuficiente.", "Verifica que a operação não altera estado em erro."] },
  { id: "qz-066-autorizacao", order: 66, module: "APIs", title: "Autenticado não significa autorizado", type: "TEST", context: "Usuário A e usuário B têm pedidos próprios; um operador pode ver todos, mas não editar dados de pagamento.", prompt: "Crie testes de autorização horizontal e vertical para os recursos.", deliverable: "Matriz papel × recurso × ação × resultado esperado.", rubric: ["Testa acesso a recurso de outra pessoa.", "Diferencia papel e identidade.", "Inclui tentativa de mutação proibida."] },
  { id: "qz-067-jwt", order: 67, module: "APIs", title: "O token carrega contexto", type: "INVESTIGATE", context: "Um chamado relata que o usuário continua acessando área premium depois de baixar de plano. O JWT tem claims de role, plan e expiração.", prompt: "Defina o que inspecionar no token e quais hipóteses explicariam o acesso indevido.", deliverable: "Hipóteses por claim, expiração e validação de servidor.", rubric: ["Não trata token decodificado como confiável por si só.", "Considera expiração e revogação.", "Relaciona claim a decisão de acesso."] },
  { id: "qz-068-openapi", order: 68, module: "APIs", title: "Leia contrato antes de atacar endpoint", type: "TEST", context: "A documentação OpenAPI declara POST /payments, campos obrigatórios, enum de método e respostas 201, 400 e 409.", prompt: "Derive cenários de teste da documentação sem olhar implementação.", deliverable: "Casos de contrato para sucesso, validação e conflito.", rubric: ["Usa schema, required e enum.", "Valida códigos documentados.", "Identifica lacunas da documentação."] },
  { id: "qz-069-schema", order: 69, module: "APIs", title: "Contrato também quebra silenciosamente", type: "TEST", context: "Um endpoint deveria devolver `total` numérico e `items` como array; uma release passou a enviar total como texto e omitir items vazio.", prompt: "Defina validações de schema que detectem a regressão antes de chegar à UI.", deliverable: "Schema esperado e assertions de contrato.", rubric: ["Valida tipo e presença de campos.", "Define comportamento para coleção vazia.", "Evita assertions frágeis em dados variáveis."] },
  { id: "qz-070-api-chaining", order: 70, module: "APIs", title: "Encadeie sem contaminar massa", type: "BUILD", context: "Para testar exclusão de conta você precisa autenticar, criar dado de teste, consultar, excluir e confirmar que não existe mais.", prompt: "Monte uma collection encadeada com captura de IDs e estratégia de cleanup.", deliverable: "Fluxo de requests com variáveis e limpeza.", rubric: ["Reaproveita token e ID de forma controlada.", "Valida cada etapa antes da próxima.", "Não deixa massa residual sem necessidade."] },
  { id: "qz-071-rate-limit", order: 71, module: "APIs", title: "Limite também é contrato", type: "TEST", context: "A API permite 60 tentativas de login por minuto por IP e usuário. Depois deve responder 429 sem bloquear usuários legítimos por tempo excessivo.", prompt: "Defina como testar o limite, headers de retorno e recuperação após a janela.", deliverable: "Plano de teste de rate limit com cuidado para não gerar abuso.", rubric: ["Usa ambiente controlado.", "Valida status e informação de retry.", "Testa recuperação após janela."] },
  { id: "qz-072-idempotencia", order: 72, module: "APIs", title: "Pagamento não pode cobrar duas vezes", type: "TEST", context: "Cliente reenvia a mesma requisição de pagamento após timeout. A API suporta chave de idempotência.", prompt: "Crie casos para requisições duplicadas, mesma chave com payload diferente e repetição após resposta bem-sucedida.", deliverable: "Bateria de cenários de idempotência.", rubric: ["Verifica uma única cobrança/efeito.", "Testa conflito de chave e payload.", "Considera retry por falha de rede."] },
  { id: "qz-073-modelo-relacional", order: 73, module: "Banco de dados e SQL", title: "Leia o domínio antes de escrever query", type: "DECIDE", context: "Um sistema possui usuários, pedidos, itens de pedido e pagamentos. Um usuário pode ter muitos pedidos; um pedido tem muitos itens e pode ter tentativas de pagamento.", prompt: "Defina as relações e chaves que precisam existir para preservar a integridade do domínio.", deliverable: "Modelo relacional simples com PKs e FKs.", rubric: ["Representa cardinalidades corretamente.", "Distingue entidade de atributo.", "Protege relação entre pedido e pagamento."] },
  { id: "qz-074-select", order: 74, module: "Banco de dados e SQL", title: "Consulte sem trazer o mundo inteiro", type: "BUILD", context: "Você investiga um chamado de usuário que não encontra o último pedido. A tabela orders possui id, user_id, status, total e created_at.", prompt: "Escreva uma consulta que localize pedidos de um usuário e mostre primeiro os mais recentes.", deliverable: "Query SELECT com filtro e ordenação, acompanhada da leitura esperada.", rubric: ["Seleciona somente campos necessários.", "Filtra pelo usuário correto.", "Ordena por dado temporal apropriado."] },
  { id: "qz-075-filtro", order: 75, module: "Banco de dados e SQL", title: "WHERE muda a pergunta", type: "BUILD", context: "O time quer investigar pagamentos aprovados com valor acima de R$ 1.000 nos últimos sete dias.", prompt: "Monte a consulta e explique cada condição para evitar resultado amplo ou ambíguo.", deliverable: "Query com WHERE e explicação dos filtros.", rubric: ["Combina condições corretamente.", "Trata período de tempo de forma explícita.", "Evita usar filtro textual para valor numérico."] },
  { id: "qz-076-agregacao", order: 76, module: "Banco de dados e SQL", title: "Número de dashboard precisa ser rastreável", type: "BUILD", context: "Um painel diz que houve R$ 80 mil em receita por categoria no mês. Pedidos e itens ficam em tabelas diferentes.", prompt: "Desenhe a query que agregaria receita por categoria e indique a regra para excluir pedido cancelado.", deliverable: "Query com JOIN, GROUP BY e regra de status.", rubric: ["Agrupa no nível correto.", "Evita contar pedido duplicado por item.", "Explicita exclusão de status indevido."] },
  { id: "qz-077-join", order: 77, module: "Banco de dados e SQL", title: "JOIN sem criar número falso", type: "INVESTIGATE", context: "Uma consulta que junta pedidos, itens e tentativas de pagamento mostra receita três vezes maior que o esperado.", prompt: "Explique como joins de um-para-muitos podem multiplicar linhas e como investigaria a causa.", deliverable: "Hipótese de duplicação e estratégia de correção/validação.", rubric: ["Reconhece multiplicação de cardinalidade.", "Inspeciona granularidade antes de agregar.", "Propõe validação contra dado de origem."] },
  { id: "qz-078-massa-segura", order: 78, module: "Banco de dados e SQL", title: "Dados de teste sem estragar ambiente", type: "BUILD", context: "Você precisa criar usuário, pedido e pagamento para validar um fluxo em homologação compartilhada.", prompt: "Defina uma estratégia de INSERT, identificação da massa e cleanup usando UPDATE/DELETE com segurança.", deliverable: "Plano de setup e cleanup com guardrails.", rubric: ["Usa identificadores rastreáveis.", "Evita comando amplo sem WHERE.", "Prevê limpeza mesmo após falha do teste."] },
  { id: "qz-079-persistencia", order: 79, module: "Banco de dados e SQL", title: "A UI disse salvo. O banco confirma?", type: "TEST", context: "Usuário altera endereço na UI e vê toast de sucesso. Em seguida, a tela de pedido ainda mostra endereço antigo.", prompt: "Defina as verificações entre UI, response da API e registro persistido para localizar a divergência.", deliverable: "Roteiro de validação ponta a ponta.", rubric: ["Compara três fontes de estado.", "Considera cache e leitura atrasada.", "Não conclui só pelo toast."] },
  { id: "qz-080-integridade", order: 80, module: "Banco de dados e SQL", title: "Encontre dados órfãos", type: "INVESTIGATE", context: "Relatório de suporte mostra itens de pedido que não aparecem no detalhe do pedido. Suspeita-se de registros filhos sem pai.", prompt: "Descreva como identificar dados órfãos e qual regra do banco deveria prevenir esse estado.", deliverable: "Query/estratégia de detecção e recomendação de integridade.", rubric: ["Usa relação pai-filho para investigar.", "Diferencia dado excluído de referência quebrada.", "Propõe FK ou regra equivalente."] },
  { id: "qz-081-ui-banco", order: 81, module: "Banco de dados e SQL", title: "Valor exibido não bate com valor persistido", type: "INVESTIGATE", context: "Carrinho mostra total R$ 120; API de criação responde R$ 120; pedido salvo tem total R$ 108.", prompt: "Organize as hipóteses e evidências para encontrar em que camada o valor mudou.", deliverable: "Linha de rastreio UI → request → regra → banco.", rubric: ["Compara cada fronteira de dados.", "Considera regra no servidor e transformação.", "Registra correlação por ID do pedido."] },
  { id: "qz-082-transacao", order: 82, module: "Banco de dados e SQL", title: "Operação parcial é defeito", type: "TEST", context: "Ao finalizar pedido, sistema reserva estoque, cria pagamento e registra pedido. A cobrança pode falhar no último passo.", prompt: "Defina como testar atomicidade e rollback para garantir que não reste estoque reservado ou pedido inconsistente.", deliverable: "Cenários de falha por etapa e estado esperado final.", rubric: ["Modela efeito parcial por dependência.", "Define estado consistente após falha.", "Considera compensação quando transação única não é possível."] },
  { id: "qz-083-concorrencia", order: 83, module: "Banco de dados e SQL", title: "Dois usuários, uma última unidade", type: "TEST", context: "Há uma unidade de um produto. Dois usuários confirmam compra quase no mesmo instante.", prompt: "Crie uma estratégia para testar concorrência e defina quais resultados são aceitáveis para estoque, pedidos e pagamento.", deliverable: "Cenário concorrente com oráculos de integridade.", rubric: ["Executa ações em paralelo de forma controlada.", "Evita venda acima do estoque.", "Valida consistência em todas as entidades afetadas."] },
  { id: "qz-084-acesso-dados", order: 84, module: "Banco de dados e SQL", title: "Consulta também precisa de permissão", type: "DECIDE", context: "QA pede acesso de leitura ao banco de produção para investigar um incidente. A base contém e-mail, CPF e dados de pagamento tokenizados.", prompt: "Defina o menor acesso necessário e um fluxo seguro para investigação sem expor dados pessoais.", deliverable: "Decisão de acesso, controles e alternativa se acesso direto não for necessário.", rubric: ["Aplica princípio do menor privilégio.", "Considera mascaramento e auditoria.", "Diferencia investigação legítima de acesso amplo."] },
  { id: "qz-085-versionamento", order: 85, module: "Git", title: "Por que QA precisa de versionamento", type: "COMMUNICATE", context: "Uma pessoa do time afirma que Git é assunto só de dev porque QA não escreve código de produção.", prompt: "Explique como versionamento apoia QA em testes, evidências, automação e rastreabilidade de release.", deliverable: "Resposta curta para alguém novo no time.", rubric: ["Conecta Git ao trabalho real de QA.", "Cita colaboração e histórico.", "Não depende de QA ser responsável pelo merge."] },
  { id: "qz-086-branch-commits", order: 86, module: "Git", title: "Uma mudança testável em branch", type: "BUILD", context: "Você vai adicionar uma automação de login a um repositório compartilhado.", prompt: "Defina a branch, a sequência de commits e as mensagens que facilitam revisão e rollback.", deliverable: "Plano de branch e commits atômicos.", rubric: ["Nomeia branch pelo propósito.", "Separa setup, teste e documentação quando fizer sentido.", "Escreve mensagens que explicam mudança."] },
  { id: "qz-087-pr-qa", order: 87, module: "Git", title: "QA olhando um Pull Request", type: "TEST", context: "Um PR altera validação de e-mail, atualiza endpoint e inclui teste automatizado que só cobre caso válido.", prompt: "Faça uma revisão sob a ótica de qualidade: riscos, lacunas e perguntas antes de aprovar.", deliverable: "Comentário de revisão priorizado.", rubric: ["Vai além de estilo de código.", "Conecta alteração a cenários negativos.", "Pede evidência ou teste de forma construtiva."] },
  { id: "qz-088-fluxo-basico", order: 88, module: "Git", title: "Do clone ao Pull Request", type: "BUILD", context: "Você recebeu uma tarefa de corrigir um teste flaky em um repositório remoto.", prompt: "Descreva o fluxo seguro de clone, atualização, branch, alteração, execução, commit, push e PR.", deliverable: "Checklist operacional na ordem correta.", rubric: ["Atualiza contexto antes de alterar.", "Executa testes antes de abrir PR.", "Mantém alteração isolada em branch."] },
  { id: "qz-089-conflito", order: 89, module: "Git", title: "Conflito não se resolve escolhendo qualquer lado", type: "INVESTIGATE", context: "Sua branch alterou o mesmo seletor de login que outra mudança recém-integrada. Uma versão usa data-testid novo; outra mantém seletor por texto.", prompt: "Explique como investigar o conflito e decidir a resolução preservando a intenção das duas mudanças.", deliverable: "Roteiro de resolução e validação após merge.", rubric: ["Lê contexto dos dois lados.", "Não resolve por preferência sem verificar app.", "Roda teste após resolver."] },
  { id: "qz-090-gitflow", order: 90, module: "Git", title: "Fluxo de branches proporcional ao time", type: "DECIDE", context: "Um produto pequeno faz deploy diário, tem uma equipe de seis pessoas e ocasionalmente precisa de hotfix urgente.", prompt: "Compare um fluxo simples baseado em trunk com Gitflow e escolha um, explicando trade-offs.", deliverable: "Decisão de fluxo com regras mínimas.", rubric: ["Considera frequência de deploy.", "Inclui estratégia de hotfix.", "Evita processo pesado sem benefício claro."] },
  { id: "qz-091-historico", order: 91, module: "Git", title: "Use histórico para investigar regressão", type: "INVESTIGATE", context: "Um teste de checkout começou a falhar após uma release, mas não há ticket associado e a suite passou na semana anterior.", prompt: "Defina como usaria histórico de commits, PRs e mudanças de arquivo para delimitar a investigação.", deliverable: "Plano de investigação baseado em histórico.", rubric: ["Define intervalo de regressão.", "Relaciona mudança de código a comportamento.", "Evita culpar autor do commit."] },
  { id: "qz-092-rollback", order: 92, module: "Git", title: "Reverter com segurança", type: "DECIDE", context: "Uma correção em produção quebra o cálculo de frete. Outras duas mudanças seguras chegaram junto no mesmo deploy.", prompt: "Decida entre revert, hotfix ou feature flag e descreva as validações antes e depois da ação.", deliverable: "Plano de contenção com risco residual.", rubric: ["Contém impacto rapidamente.", "Evita desfazer mudança não relacionada sem necessidade.", "Inclui smoke após a ação."] },
];

export const qaDoZeroTrack = { slug: "qa-do-zero", title: "QA do Zero", subtitle: "Fundamento, raciocínio e prática antes da ferramenta.", outcome: "Você consegue explicar, planejar e defender decisões básicas de qualidade em contexto de produto.", challenges: qaDoZeroChallenges };

export function findQaDoZeroChallenge(id: string) { return qaDoZeroChallenges.find((challenge) => challenge.id === id); }
