import type { EnrichedChallengeContent } from "./base-content";

const modules: Record<string, EnrichedChallengeContent> = {
  "2.1": { concept: "Trabalhar em times exige alinhar contexto, risco, responsabilidade e comunicação. QA influencia decisões sem virar fiscal isolado.", example: "Antes de testar uma feature, o time combina objetivo, dados, critérios e como decidirá se o risco é aceitável.", steps: ["Identifique pessoas, objetivo e restrições.", "Torne riscos e perguntas visíveis.", "Combine uma decisão e seu dono.", "Registre próximo passo e critério de conclusão."], evidence: ["Mapa de alinhamento", "Decisões e pendências", "Mensagem acionável"], commonMistakes: ["Falar só em testes", "Assumir que todos têm o mesmo contexto", "Escalar sem tentar alinhar"] },
  "2.2": { concept: "Refinement é uma conversa para tornar uma ideia compreensível, testável e pronta para execução. O valor está nas perguntas e exemplos.", example: "Uma história de cupom precisa esclarecer elegibilidade, acúmulo, expiração, mensagem e impacto no frete.", steps: ["Leia a história procurando ambiguidade.", "Pergunte por regra, exceção e dados.", "Escreva exemplos compartilhados.", "Defina saída e pendência do refinement."], evidence: ["Perguntas priorizadas", "Critérios e exemplos", "Definition of Ready"], commonMistakes: ["Aceitar história vaga", "Transformar reunião em leitura", "Esconder decisão não tomada"] },
  "2.3": { concept: "Mudança de requisito altera risco, cobertura e expectativa. QA precisa avaliar impacto, não apenas trocar uma frase no caso de teste.", example: "Se o prazo de cancelamento muda de 24 para 2 horas, regras, dados, mensagens e regressão mudam juntos.", steps: ["Compare antes e depois.", "Liste fluxos e artefatos afetados.", "Reavalie casos positivos, limites e integrações.", "Comunique risco e esforço revisados."], evidence: ["Análise de impacto", "Casos atualizados", "Decisão de escopo"], commonMistakes: ["Testar só a mudança literal", "Ignorar dados existentes", "Não comunicar efeito na release"] },
  "2.4": { concept: "Priorizar é escolher onde investir tempo limitado com base em impacto, probabilidade, alcance, urgência e custo de atraso.", example: "Uma falha de pagamento em campanha pode superar um bug crítico numa tela administrativa pouco usada.", steps: ["Liste riscos e contexto de negócio.", "Defina critérios de comparação.", "Ordene e explique trade-offs.", "Registre o que será aceito como risco."], evidence: ["Matriz impacto/probabilidade", "Fila priorizada", "Risco residual"], commonMistakes: ["Ordenar por quem grita mais", "Confundir severidade e prioridade", "Não revisar prioridade quando contexto muda"] },
  "2.5": { concept: "Em produção, investigação precisa preservar usuários e dados. Observabilidade, contenção, rollback e comunicação importam tanto quanto reproduzir.", example: "Um erro intermitente de cobrança pede correlação de logs e contenção antes de repetir transações reais.", steps: ["Defina impacto e blast radius.", "Colete sinais sem expor dado sensível.", "Proponha contenção segura.", "Registre hipótese, evidência e próxima decisão."], evidence: ["Timeline do incidente", "Logs sanitizados", "Plano de contenção"], commonMistakes: ["Testar destrutivamente em produção", "Fechar hipótese cedo", "Comunicar só depois da correção"] },
  "2.6": { concept: "Ambientes precisam ser conhecidos, isolados e reproduzíveis. Diferença de configuração pode ser a causa do defeito ou mascará-lo.", example: "Uma integração funciona em homologação porque há uma flag e um serviço falso que não existem em produção.", steps: ["Compare versões, flags, dados e serviços.", "Identifique dependências externas.", "Reproduza com configuração documentada.", "Declare limitações do ambiente."], evidence: ["Matriz de ambientes", "Configuração comparada", "Diferenças relevantes"], commonMistakes: ["Tratar ambiente como detalhe", "Copiar segredo para evidência", "Concluir que ‘funciona aqui’ encerra investigação"] },
  "2.7": { concept: "Massa de dados deve ser representativa, controlada, isolada e descartável. Dados bons permitem reproduzir risco sem contaminar outros testes.", example: "Um cliente com pedido cancelado e cupom expirado revela regras que um usuário recém-criado não revela.", steps: ["Defina o estado necessário.", "Crie dados mínimos e identificáveis.", "Execute sem depender de registros alheios.", "Limpe ou restaure a massa."], evidence: ["Fixture ou seed", "Pré-condição explícita", "Estratégia de cleanup"], commonMistakes: ["Usar dados de outra pessoa", "Depender de ordem de execução", "Deixar massa residual"] },
  "2.8": { concept: "Manutenção de testes e produto é trabalho de qualidade: remover duplicidade, atualizar contratos, reduzir flakiness e preservar intenção.", example: "Uma suíte que falha por seletor frágil não deve ser apenas reexecutada; a causa e o valor do teste precisam ser revisados.", steps: ["Classifique falha real, ambiente ou teste.", "Encontre duplicidade e obsolescência.", "Corrija a causa com menor custo.", "Meça estabilidade após a mudança."], evidence: ["Diagnóstico de falha", "Diff de manutenção", "Taxa de estabilidade"], commonMistakes: ["Silenciar teste instável", "Manter cenário sem valor", "Refatorar sem preservar cobertura"] },
  "2.9": { concept: "Sistemas legados exigem investigação incremental, respeito a comportamento existente e atenção a dependências invisíveis.", example: "Uma regra sem documentação pode ser usada por uma integração antiga; corrigir sem mapear consumidores cria regressão.", steps: ["Mapeie comportamento atual e consumidores.", "Capture uma linha de base.", "Escolha mudança pequena e reversível.", "Adicione proteção antes de alterar."], evidence: ["Mapa de dependências", "Caracterização do comportamento", "Plano de rollback"], commonMistakes: ["Assumir que código sem teste não importa", "Reescrever sem observação", "Confundir legado com lixo"] },
  "2.10": { concept: "Uma release é uma decisão operacional: escopo, risco, evidência, rollout, monitoramento e reversão precisam estar combinados.", example: "Uma feature pode estar testada e ainda não pronta se não houver migração reversível ou sinal para interromper rollout.", steps: ["Resuma mudanças e riscos.", "Confirme evidências e pendências.", "Defina rollout, sinais e dono.", "Prepare rollback e comunicação."], evidence: ["Checklist de release", "Go/no-go justificado", "Plano de rollback"], commonMistakes: ["Usar ‘todos os testes passaram’ como decisão", "Esquecer migração e suporte", "Não definir gatilho de rollback"] },
  "2.11": { concept: "Situações reais exigem combinar técnica, contexto, comunicação e decisão sob incerteza. Uma boa resposta deixa fatos, hipóteses e próximos passos separados.", example: "Um bug que só aparece para parte dos usuários pede coleta de contexto e mitigação, não um ‘não reproduzi’ imediato.", steps: ["Separe fato, hipótese e lacuna.", "Avalie impacto e urgência.", "Escolha o menor próximo passo útil.", "Comunique decisão e risco residual."], evidence: ["Registro de investigação", "Perguntas pendentes", "Decisão contextualizada"], commonMistakes: ["Responder com certeza sem evidência", "Pular direto para solução", "Ignorar a pessoa afetada"] },
};

export function getRealLifeContent(module: string) {
  const key = module.match(/^(2\.\d+)/)?.[1];
  return key ? modules[key] ?? null : null;
}
