import Link from "next/link";
import { ArrowRight, CheckCircle2, LockKeyhole } from "lucide-react";
import { qaDoZeroTrack } from "@/lib/roadmap/qa-do-zero";

const typeColor = { INVESTIGATE: "text-coral", TEST: "text-neon", BUILD: "text-mint", DECIDE: "text-[#9BC0F5]", COMMUNICATE: "text-[#E9B7FF]" };

export const metadata = { title: "QA do Zero | QA Lab Pro", description: "Trilha prática de fundamentos de qualidade de software." };

export default function QaDoZeroPage() { const modules = [...new Set(qaDoZeroTrack.challenges.map((challenge) => challenge.module))]; return <main className="mx-auto max-w-5xl px-5 py-14 sm:px-8"><header className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-mint">Trilha Pro · em construção pública</p><h1 className="mt-4 text-4xl font-black text-off-white sm:text-6xl">{qaDoZeroTrack.title}</h1><p className="mt-5 text-lg leading-8 text-[#AAB2BC]">{qaDoZeroTrack.subtitle}</p><p className="mt-5 rounded-xl border border-mint/20 bg-mint/[.05] p-4 text-sm leading-6 text-[#D9DEE4]">Ao concluir este bloco: {qaDoZeroTrack.outcome}</p></header>{modules.map((module, index) => <section key={module} className="mt-12"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-neon">Bloco {String(index + 1).padStart(2, "0")}</p><h2 className="mt-2 text-2xl font-black text-off-white">{module}</h2></div><span className="inline-flex items-center gap-2 text-xs text-[#8B949E]"><LockKeyhole className="size-4" /> Pro</span></div><div className="mt-6 grid gap-3">{qaDoZeroTrack.challenges.filter((challenge) => challenge.module === module).map((challenge) => <Link key={challenge.id} href={`/trilhas/qa-do-zero/${challenge.id}`} className="group flex gap-4 rounded-xl border border-white/10 bg-[#171B21] p-5 transition hover:border-mint/35 hover:bg-mint/[.03]"><span className="flex size-9 shrink-0 items-center justify-center rounded-lg border border-white/10 bg-[#101319] font-mono text-xs font-black text-mint">{String(challenge.order).padStart(2, "0")}</span><span className="min-w-0 flex-1"><span className={`text-xs font-bold tracking-wide ${typeColor[challenge.type]}`}>{challenge.type}</span><strong className="mt-1 block text-base text-off-white">{challenge.title}</strong><span className="mt-1 block text-sm leading-6 text-[#AAB2BC]">{challenge.deliverable}</span></span><ArrowRight className="mt-3 size-4 shrink-0 text-[#69737E] transition group-hover:translate-x-1 group-hover:text-mint" /></Link>)}</div></section>)}</main>; }
