"use client";

import { useMemo, useState, type FormEvent, type ReactNode } from "react";
import Link from "next/link";
import { ArrowRight, CalendarDays, ChevronRight, Circle, Filter, Flame, LayoutList, Plus, Search, Sparkles, Target, X } from "lucide-react";
import { motion } from "motion/react";
import { SaveGate } from "@/components/lab/save-gate";
import { createUserStory, setStoryStatus, updateUserStoryStatus } from "./actions";

const colStagger = { hidden: {}, show: { transition: { staggerChildren: 0.05 } } };
const cardItem = { hidden: { opacity: 0, y: 14 }, show: { opacity: 1, y: 0, transition: { type: "spring" as const, damping: 20, stiffness: 240 } } };

type Status = "backlog" | "todo" | "progress" | "review" | "done";
type Priority = "baixa" | "media" | "alta" | "critica";
type Story = { id: string; key: string; title: string; description: string; criteria: string[]; status: Status; priority: Priority; points: number; assignee: string; labels: string[] };
export type UserStory = { id: string; key: string; title: string; description: string | null; criteria: string[] | null; status: Status; priority: Priority; points: number };

const seed: Story[] = [
  { id: "1", key: "EXP-101", title: "Solicitar reembolso de uma despesa", description: "Como colaborador, quero cadastrar uma despesa com comprovante para solicitar o reembolso.", criteria: ["Título, categoria, valor e data são obrigatórios", "O comprovante deve aceitar PDF, PNG ou JPG", "A solicitação inicia com status Pendente"], status: "progress", priority: "alta", points: 8, assignee: "Marina", labels: ["reembolso", "core"] },
  { id: "2", key: "EXP-102", title: "Aprovar solicitação da equipe", description: "Como gestor, quero aprovar ou rejeitar solicitações para controlar os gastos da equipe.", criteria: ["Somente gestores da equipe podem decidir", "Rejeição exige justificativa", "O colaborador deve ser notificado"], status: "todo", priority: "critica", points: 5, assignee: "Rafael", labels: ["aprovação", "permissão"] },
  { id: "3", key: "EXP-103", title: "Filtrar despesas por período", description: "Como analista financeiro, quero filtrar despesas por período para realizar o fechamento mensal.", criteria: ["Data inicial não pode ser posterior à final", "O total deve refletir somente os resultados filtrados"], status: "review", priority: "media", points: 3, assignee: "João", labels: ["relatório"] },
  { id: "4", key: "EXP-104", title: "Exportar relatório financeiro", description: "Como analista financeiro, quero exportar as despesas em CSV para conciliar os dados.", criteria: ["Exportar os filtros aplicados", "Valores devem usar duas casas decimais"], status: "backlog", priority: "media", points: 5, assignee: "Não atribuído", labels: ["relatório", "csv"] },
  { id: "5", key: "EXP-105", title: "Impedir autoaprovação", description: "Como responsável por compliance, quero impedir que um colaborador aprove a própria despesa.", criteria: ["Autor e aprovador devem ser pessoas diferentes", "A tentativa deve ser auditada"], status: "done", priority: "critica", points: 3, assignee: "Marina", labels: ["segurança", "compliance"] },
  { id: "6", key: "EXP-106", title: "Notificar alteração de status", description: "Como colaborador, quero ser notificado quando minha solicitação mudar de status.", criteria: ["Enviar notificação após aprovação ou rejeição", "A mensagem deve identificar a solicitação"], status: "backlog", priority: "baixa", points: 3, assignee: "Não atribuído", labels: ["notificação"] },
];
const columns: { status: Status; label: string; color: string }[] = [
  { status: "todo", label: "A fazer", color: "bg-[#9BC0F5]" }, { status: "progress", label: "Em andamento", color: "bg-[#F0C040]" }, { status: "review", label: "Em revisão", color: "bg-[#C39BF5]" }, { status: "done", label: "Concluído", color: "bg-neon" },
];
const nextStatus: Record<Exclude<Status, "done">, Status> = { backlog: "todo", todo: "progress", progress: "review", review: "done" };
const priorityStyle: Record<Priority, string> = { baixa: "text-[#8B949E]", media: "text-[#9BC0F5]", alta: "text-[#F0C040]", critica: "text-coral" };

function fromUserStory(u: UserStory): Story { return { id: u.id, key: u.key, title: u.title, description: u.description ?? "", criteria: u.criteria ?? [], status: u.status, priority: u.priority, points: u.points, assignee: "Você", labels: ["sua história"] }; }

export function HistoriasBoard({ authed = false, initialStates = {}, initialUserStories = [] }: { authed?: boolean; initialStates?: Record<string, string>; initialUserStories?: UserStory[] }) {
  const [stories, setStories] = useState<Story[]>(() => [...seed.map((story) => ({ ...story, status: (initialStates[story.key] as Status | undefined) ?? story.status })), ...initialUserStories.map(fromUserStory)]);
  const [userIds, setUserIds] = useState<Set<string>>(() => new Set(initialUserStories.map((story) => story.id)));
  const [view, setView] = useState<"sprint" | "backlog">("sprint"); const [query, setQuery] = useState(""); const [showForm, setShowForm] = useState(false); const [selected, setSelected] = useState<Story | null>(null); const [showGate, setShowGate] = useState(false);
  const filtered = useMemo(() => stories.filter((story) => `${story.key} ${story.title} ${story.description}`.toLowerCase().includes(query.toLowerCase())), [stories, query]);
  const sprint = stories.filter((story) => story.status !== "backlog"); const done = sprint.filter((story) => story.status === "done"); const totalPoints = sprint.reduce((sum, story) => sum + story.points, 0); const donePoints = done.reduce((sum, story) => sum + story.points, 0);
  function updateStory(id: string, changes: Partial<Story>) {
    const story = stories.find((item) => item.id === id);
    setStories((current) => current.map((item) => item.id === id ? { ...item, ...changes } : item));
    setSelected((current) => current?.id === id ? { ...current, ...changes } : current);
    if (!authed) { setShowGate(true); return; }
    if (changes.status && story) {
      if (userIds.has(id)) void updateUserStoryStatus(id, changes.status);
      else void setStoryStatus(story.key, changes.status);
    }
  }
  function addStory(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const tempId = crypto.randomUUID();
    const key = `EXP-${101 + stories.length}`;
    const criteria = String(form.get("criteria")).split("\n").map((x) => x.trim()).filter(Boolean);
    const priority = form.get("priority") as Priority;
    const points = Number(form.get("points"));
    const story: Story = { id: tempId, key, title: String(form.get("title")), description: String(form.get("description")), criteria, status: "backlog", priority, points, assignee: "Você", labels: ["sua história"] };
    setStories((current) => [...current, story]);
    setUserIds((current) => new Set(current).add(tempId));
    setShowForm(false); setView("backlog");
    if (!authed) { setShowGate(true); return; }
    void createUserStory({ key, title: story.title, description: story.description, criteria, priority, points }).then((res) => {
      if (!res?.id) return;
      setStories((current) => current.map((item) => item.id === tempId ? { ...item, id: res.id } : item));
      setUserIds((current) => { const next = new Set(current); next.delete(tempId); next.add(res.id); return next; });
    });
  }

  return <div className="min-h-[calc(100vh-4rem)] bg-[#0D1117]">
    <div className="border-b border-white/10 bg-[#12161C]"><div className="mx-auto flex max-w-[1500px] flex-col gap-4 px-5 py-4 sm:px-8 lg:flex-row lg:items-center lg:justify-between">
      <div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-[#9BC0F5] text-[#101319]"><LayoutList className="size-5" /></span><div><div className="flex items-center gap-2"><span className="text-sm font-black text-off-white">Histórias</span><span className="rounded bg-white/5 px-1.5 py-0.5 text-[9px] font-black uppercase tracking-wider text-[#8B949E]">Product workspace</span></div><p className="mt-0.5 text-[11px] text-[#69737E]">ExpenseFlow · Produto e qualidade no mesmo fluxo</p></div></div>
      <nav className="flex items-center gap-1 rounded-xl border border-white/10 bg-[#0D1117] p-1 text-xs font-bold"><button onClick={() => setView("sprint")} className={`rounded-lg px-3 py-2 ${view === "sprint" ? "bg-[#9BC0F5]/10 text-[#9BC0F5]" : "text-[#8B949E]"}`}>Sprint ativa</button><button onClick={() => setView("backlog")} className={`rounded-lg px-3 py-2 ${view === "backlog" ? "bg-[#9BC0F5]/10 text-[#9BC0F5]" : "text-[#8B949E]"}`}>Backlog <span className="ml-1 rounded-full bg-white/10 px-1.5 py-0.5 text-[9px]">{stories.filter((x) => x.status === "backlog").length}</span></button></nav>
      <div className="flex gap-2"><Link href="/lab/studio" className="flex h-10 items-center gap-2 rounded-lg border border-white/10 px-3 text-xs font-bold text-[#AAB2BC] hover:border-mint/30 hover:text-mint"><Sparkles className="size-3.5" />Test Design</Link><motion.button whileHover={{ scale: 1.04 }} whileTap={{ scale: 0.96 }} onClick={() => setShowForm(true)} className="flex h-10 items-center gap-2 rounded-lg bg-[#9BC0F5] px-4 text-xs font-black text-[#101319]"><Plus className="size-4" />Nova história</motion.button></div>
    </div></div>
    <main className="mx-auto max-w-[1500px] px-5 py-7 sm:px-8">
      <div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.15em] text-[#69737E]">Produto <ChevronRight className="size-3" /><span className="text-[#9BC0F5]">{view === "sprint" ? "Sprint 08" : "Backlog"}</span></div><h1 className="mt-3 text-3xl font-black text-off-white">{view === "sprint" ? "Sprint 08 · Fechamento financeiro" : "Backlog do produto"}</h1><p className="mt-2 text-sm text-[#8B949E]">{view === "sprint" ? "17–28 de junho · Objetivo: tornar o fluxo de reembolso seguro e auditável." : "Priorize, refine e prepare as próximas histórias para desenvolvimento."}</p></div>{view === "sprint" && <div className="grid grid-cols-3 gap-2"><Metric icon={Target} value={`${done.length}/${sprint.length}`} label="Histórias" /><Metric icon={Flame} value={`${donePoints}/${totalPoints}`} label="Pontos" /><Metric icon={CalendarDays} value="4 dias" label="Restantes" /></div>}</div>
      <div className="mt-6 flex gap-2"><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-3 size-4 text-[#69737E]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por chave, título ou descrição" className="field w-full pl-9" /></div><button className="flex size-10 items-center justify-center rounded-lg border border-white/10 text-[#8B949E]"><Filter className="size-4" /></button></div>
      {view === "sprint" ? <div className="mt-6 grid gap-4 lg:grid-cols-4">{columns.map((column) => { const items = filtered.filter((story) => story.status === column.status); return <section key={column.status} className="min-w-0 rounded-2xl border border-white/10 bg-[#12161C]/80 p-3"><div className="flex items-center justify-between px-1 pb-3"><div className="flex items-center gap-2"><span className={`size-2 rounded-full ${column.color}`} /><h2 className="text-xs font-black uppercase tracking-wider text-off-white">{column.label}</h2><span className="text-xs text-[#69737E]">{items.length}</span></div><span className="text-[10px] font-bold text-[#69737E]">{items.reduce((sum, item) => sum + item.points, 0)} pts</span></div><motion.div variants={colStagger} initial="hidden" animate="show" className="space-y-3">{items.map((story) => <StoryCard key={story.id} story={story} open={() => setSelected(story)} advance={() => story.status !== "done" && updateStory(story.id, { status: nextStatus[story.status] })} />)}{!items.length && <div className="rounded-xl border border-dashed border-white/10 p-6 text-center text-xs text-[#4F5965]">Nenhuma história</div>}</motion.div></section>; })}</div> : <div className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-[#12161C]"><div className="grid grid-cols-[1fr_auto] border-b border-white/10 px-5 py-3 text-[10px] font-black uppercase tracking-wider text-[#69737E] sm:grid-cols-[110px_1fr_110px_90px_150px]"><span>Chave</span><span>História</span><span className="hidden sm:block">Prioridade</span><span className="hidden sm:block">Pontos</span><span className="text-right">Ação</span></div>{filtered.filter((story) => story.status === "backlog").map((story) => <div key={story.id} className="grid grid-cols-[1fr_auto] items-center gap-3 border-b border-white/5 px-5 py-4 last:border-0 sm:grid-cols-[110px_1fr_110px_90px_150px]"><button onClick={() => setSelected(story)} className="text-left font-mono text-xs font-bold text-[#9BC0F5]">{story.key}</button><button onClick={() => setSelected(story)} className="text-left"><p className="text-sm font-bold text-off-white">{story.title}</p><p className="mt-1 line-clamp-1 text-xs text-[#69737E]">{story.description}</p></button><span className={`hidden text-xs font-bold capitalize sm:block ${priorityStyle[story.priority]}`}>{story.priority}</span><span className="hidden text-xs font-bold text-[#AAB2BC] sm:block">{story.points} pts</span><button onClick={() => updateStory(story.id, { status: "todo" })} className="flex items-center justify-end gap-1.5 text-xs font-bold text-mint">Planejar sprint <ArrowRight className="size-3.5" /></button></div>)}</div>}
    </main>
    {showForm && <Modal close={() => setShowForm(false)}><form onSubmit={addStory} className="p-6"><ModalHeader title="Nova história" close={() => setShowForm(false)} /><div className="mt-6 space-y-4"><Field label="Título"><input name="title" required className="field w-full" placeholder="Ex.: Cancelar uma solicitação pendente" /></Field><Field label="User story"><textarea name="description" required rows={4} className="field w-full" placeholder="Como..., quero..., para..." /></Field><Field label="Critérios de aceitação"><textarea name="criteria" required rows={5} className="field w-full" placeholder="Um critério por linha" /></Field><div className="grid grid-cols-2 gap-3"><Field label="Prioridade"><select name="priority" className="field w-full"><option value="media">Média</option><option value="alta">Alta</option><option value="critica">Crítica</option><option value="baixa">Baixa</option></select></Field><Field label="Story points"><select name="points" className="field w-full">{[1,2,3,5,8,13].map((point) => <option key={point}>{point}</option>)}</select></Field></div></div><button className="mt-6 w-full rounded-lg bg-[#9BC0F5] py-3 text-sm font-black text-[#101319]">Adicionar ao backlog</button></form></Modal>}
    {selected && <Modal close={() => setSelected(null)}><div className="p-6"><ModalHeader title={selected.key} close={() => setSelected(null)} /><div className="mt-5 flex flex-wrap gap-2"><span className={`text-xs font-bold capitalize ${priorityStyle[selected.priority]}`}>● {selected.priority}</span><span className="rounded bg-white/5 px-2 py-0.5 text-xs text-[#8B949E]">{selected.points} pontos</span><span className="rounded bg-white/5 px-2 py-0.5 text-xs text-[#8B949E]">{selected.assignee}</span></div><h2 className="mt-5 text-xl font-black text-off-white">{selected.title}</h2><p className="mt-3 text-sm leading-6 text-[#AAB2BC]">{selected.description}</p><h3 className="mt-6 text-xs font-black uppercase tracking-wider text-[#69737E]">Critérios de aceitação</h3><div className="mt-3 space-y-2">{selected.criteria.map((criterion) => <div key={criterion} className="flex gap-3 rounded-lg bg-white/[.03] p-3 text-sm text-[#AAB2BC]"><Circle className="mt-0.5 size-3.5 shrink-0 text-mint" />{criterion}</div>)}</div><div className="mt-6 grid gap-2 sm:grid-cols-2"><Link href={`/lab/studio?story=${encodeURIComponent(`${selected.description}\n\nCritérios de aceitação:\n- ${selected.criteria.join("\n- ")}`)}`} className="flex items-center justify-center gap-2 rounded-lg bg-neon py-3 text-xs font-black text-[#101319]"><Sparkles className="size-4" />Desenhar testes</Link>{selected.status !== "done" && <button onClick={() => updateStory(selected.id, { status: nextStatus[selected.status as Exclude<Status, "done">] })} className="flex items-center justify-center gap-2 rounded-lg border border-white/10 py-3 text-xs font-bold text-off-white">Avançar status <ArrowRight className="size-4" /></button>}</div></div></Modal>}
    <SaveGate show={showGate} next="/lab/historias" onDismiss={() => setShowGate(false)} />
  </div>;
}

function StoryCard({ story, open, advance }: { story: Story; open: () => void; advance: () => void }) { return <motion.article variants={cardItem} whileHover={{ y: -3 }} className="group rounded-xl border border-white/10 bg-[#171B21] p-4 transition hover:border-[#9BC0F5]/30"><button onClick={open} className="w-full text-left"><div className="flex items-center justify-between"><span className="font-mono text-[10px] font-bold text-[#9BC0F5]">{story.key}</span><span className={`text-[10px] font-black capitalize ${priorityStyle[story.priority]}`}>● {story.priority}</span></div><h3 className="mt-3 text-sm font-bold leading-5 text-off-white">{story.title}</h3><div className="mt-3 flex flex-wrap gap-1">{story.labels.map((label) => <span key={label} className="rounded bg-white/5 px-1.5 py-1 text-[9px] text-[#69737E]">{label}</span>)}</div><div className="mt-4 flex items-center justify-between"><span className="flex size-6 items-center justify-center rounded-full bg-mint/10 text-[9px] font-black text-mint">{story.assignee === "Não atribuído" ? "?" : story.assignee.slice(0, 2).toUpperCase()}</span><span className="rounded-full border border-white/10 px-2 py-1 text-[10px] font-bold text-[#AAB2BC]">{story.points} pts</span></div></button>{story.status !== "done" && <button onClick={advance} className="mt-3 hidden w-full items-center justify-center gap-1 border-t border-white/5 pt-3 text-[10px] font-bold text-mint group-hover:flex">Avançar <ArrowRight className="size-3" /></button>}</motion.article> }
function Metric({ icon: Icon, value, label }: { icon: typeof Target; value: string; label: string }) { return <div className="min-w-24 rounded-xl border border-white/10 bg-[#12161C] px-4 py-3"><div className="flex items-center gap-2"><Icon className="size-3.5 text-[#9BC0F5]" /><strong className="text-sm text-off-white">{value}</strong></div><p className="mt-1 text-[9px] font-bold uppercase tracking-wider text-[#69737E]">{label}</p></div> }
function Modal({ children, close }: { children: ReactNode; close: () => void }) { return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} onMouseDown={(event) => event.target === event.currentTarget && close()} className="fixed inset-0 z-[80] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"><motion.div initial={{ opacity: 0, scale: 0.95, y: 12 }} animate={{ opacity: 1, scale: 1, y: 0 }} transition={{ type: "spring", damping: 22, stiffness: 280 }} className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl border border-white/10 bg-[#171B21] shadow-2xl">{children}</motion.div></motion.div> }
function ModalHeader({ title, close }: { title: string; close: () => void }) { return <div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#9BC0F5]">Histórias</p><h2 className="mt-1 text-xl font-black text-off-white">{title}</h2></div><button onClick={close} type="button" className="flex size-9 items-center justify-center rounded-lg border border-white/10 text-[#8B949E]"><X className="size-4" /></button></div> }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block"><span className="mb-2 block text-xs font-bold text-[#AAB2BC]">{label}</span>{children}</label> }
