import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Bug, CheckCircle2, CircleDot, ListChecks, PlayCircle } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import { completeRun, createDefect, createRun, updateDefectStatus, updateExecution } from "../actions";

export default async function Page({ params }: { params: Promise<{ projectId: string }> }) {
  const { projectId } = await params;
  if (!isSupabaseConfigured()) return <GuestExecution projectId={projectId} />;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return <GuestExecution projectId={projectId} />;
  const { data: workspace } = await supabase.from("studio_workspaces").select("id,projects(title)").eq("project_id", projectId).eq("user_id", user.id).maybeSingle();
  if (!workspace) notFound();
  const [{ data: cases }, { data: runs }, { data: defects }] = await Promise.all([
    supabase.from("test_cases").select("id,title,priority").eq("workspace_id", workspace.id).neq("status", "deprecated"),
    supabase.from("test_runs").select("id,name,environment,status,created_at,test_executions(id,test_case_id,result,notes,evidence,test_cases(title))").eq("workspace_id", workspace.id).order("created_at", { ascending: false }),
    supabase.from("defects").select("id,title,severity,priority,status,actual_result,updated_at").eq("workspace_id", workspace.id).order("updated_at", { ascending: false }),
  ]);
  const project = Array.isArray(workspace.projects) ? workspace.projects[0] : workspace.projects;
  const allExecutions = (runs ?? []).flatMap((run) => run.test_executions);
  const passed = allExecutions.filter((item) => item.result === "passed").length;
  const failed = allExecutions.filter((item) => item.result === "failed").length;
  const openDefects = (defects ?? []).filter((item) => !["closed", "rejected"].includes(item.status)).length;

  return <div className="mx-auto max-w-7xl px-5 py-10">
    <div className="flex items-center justify-between"><Link href="/lab/execution" className="text-xs text-[#8B949E]"><ArrowLeft className="mr-1 inline size-3" />Execution Hub</Link><Link href={`/lab/studio/${projectId}`} className="text-xs font-bold text-neon">Voltar ao Test Design Studio</Link></div>
    <header className="mt-6"><p className="text-xs font-bold uppercase tracking-[.2em] text-mint">Produto 03 · Execution & Defect Hub</p><h1 className="mt-3 text-3xl font-black text-off-white">{project?.title ?? "Projeto"}</h1><p className="mt-2 text-sm text-[#8B949E]">Execute os casos planejados, capture evidências e acompanhe defeitos até o fechamento.</p></header>
    <section className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={ListChecks} label="Execuções" value={allExecutions.length} /><Metric icon={CheckCircle2} label="Aprovadas" value={passed} tone="neon" /><Metric icon={CircleDot} label="Falhas" value={failed} tone="coral" /><Metric icon={Bug} label="Defeitos abertos" value={openDefects} tone="coral" /></section>

    <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><main className="space-y-6">
      <section className="rounded-2xl border border-white/10 bg-[#171B21] p-5"><h2 className="font-bold text-off-white">Nova rodada</h2><p className="mt-1 text-xs text-[#69737E]">A rodada recebe todos os casos ativos do Studio.</p><form action={createRun} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="workspace_id" value={workspace.id} /><input type="hidden" name="case_ids" value={(cases ?? []).map((item) => item.id).join(",")} /><input required name="name" placeholder="Ex.: Regressão Sprint 12" className="field" /><input name="environment" placeholder="Ambiente, versão, dispositivo" className="field" /><button disabled={!cases?.length} className="inline-flex h-9 items-center justify-center gap-2 rounded-lg bg-mint px-4 text-xs font-black text-[#101319] disabled:opacity-40"><PlayCircle className="size-4" />Criar com {cases?.length ?? 0} casos</button></form></section>
      {(runs ?? []).map((run) => { const pending = run.test_executions.filter((item) => item.result === "pending").length; const done = run.test_executions.length - pending; return <section key={run.id} className="rounded-2xl border border-white/10 bg-[#171B21] p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="font-bold text-off-white">{run.name}</h2><p className="text-xs text-[#69737E]">{run.environment || "Ambiente não informado"} · {done}/{run.test_executions.length} executados</p></div><div className="flex items-center gap-3"><span className={`text-[10px] font-bold uppercase ${run.status === "completed" ? "text-neon" : "text-mint"}`}>{run.status}</span>{run.status !== "completed" && <form action={completeRun}><input type="hidden" name="id" value={run.id} /><button disabled={pending > 0} title={pending > 0 ? "Resolva os casos pendentes" : "Concluir rodada"} className="h-8 rounded-lg border border-neon/25 px-3 text-[10px] font-bold text-neon disabled:cursor-not-allowed disabled:opacity-35">Concluir rodada</button></form>}</div></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/5"><div className="h-full bg-neon transition-all" style={{ width: `${run.test_executions.length ? (done / run.test_executions.length) * 100 : 0}%` }} /></div><div className="mt-4 space-y-3">{run.test_executions.map((execution) => { const testCase = Array.isArray(execution.test_cases) ? execution.test_cases[0] : execution.test_cases; return <details key={execution.id} className="rounded-xl border border-white/[0.08]"><summary className="flex cursor-pointer justify-between p-3 text-sm"><span>{testCase?.title ?? "Caso"}</span><strong className={execution.result === "failed" ? "text-coral" : execution.result === "passed" ? "text-neon" : "text-[#69737E]"}>{execution.result}</strong></summary><form action={updateExecution} className="grid gap-2 border-t border-white/[0.08] p-3"><input type="hidden" name="id" value={execution.id} /><select name="result" defaultValue={execution.result} className="field"><option value="pending">Pendente</option><option value="passed">Passou</option><option value="failed">Falhou</option><option value="blocked">Bloqueado</option><option value="skipped">Ignorado</option></select><textarea name="notes" defaultValue={execution.notes} placeholder="Notas da execução" className="field" /><textarea name="evidence" defaultValue={execution.evidence} placeholder="Evidência, log ou URL" className="field" /><button className="h-9 rounded-lg border border-mint/25 text-xs font-bold text-mint">Salvar resultado</button></form></details>; })}</div></section>; })}
      {!runs?.length && <div className="rounded-2xl border border-dashed border-white/10 p-10 text-center text-sm text-[#69737E]">Crie a primeira rodada para começar a execução.</div>}
    </main><aside className="space-y-5">
      <section className="rounded-2xl border border-coral/20 bg-coral/[0.03] p-5"><Bug className="size-5 text-coral" /><h2 className="mt-3 font-bold text-off-white">Registrar defeito</h2><form action={createDefect} className="mt-4 grid gap-2"><input type="hidden" name="workspace_id" value={workspace.id} /><input required name="title" placeholder="Título objetivo" className="field" /><select name="execution_id" className="field"><option value="">Sem execução vinculada</option>{(runs ?? []).flatMap((run) => run.test_executions.map((execution) => <option key={execution.id} value={execution.id}>{run.name} · {(Array.isArray(execution.test_cases) ? execution.test_cases[0] : execution.test_cases)?.title}</option>))}</select><div className="grid grid-cols-2 gap-2"><select name="severity" className="field"><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option><option value="critical">Crítica</option></select><select name="priority" className="field"><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></div><textarea name="description" placeholder="Descrição" className="field" /><textarea name="steps" placeholder="Passos para reproduzir" className="field" /><textarea name="expected_result" placeholder="Resultado esperado" className="field" /><textarea name="actual_result" placeholder="Resultado atual" className="field" /><textarea name="evidence" placeholder="Evidência, log ou URL" className="field" /><button className="h-9 rounded-lg bg-coral text-xs font-black text-[#101319]">Criar defeito</button></form></section>
      <section className="rounded-2xl border border-white/10 bg-[#171B21] p-5"><h2 className="font-bold text-off-white">Defeitos</h2><div className="mt-3 space-y-3">{(defects ?? []).map((defect) => <details key={defect.id} className="rounded-lg border border-white/[0.08] p-3"><summary className="cursor-pointer text-sm font-bold">{defect.title}<span className="ml-2 text-[9px] uppercase text-coral">{defect.severity}</span></summary><p className="mt-2 text-xs text-[#8B949E]">{defect.actual_result || "Sem resultado observado"}</p><form action={updateDefectStatus} className="mt-3 grid gap-2"><input type="hidden" name="id" value={defect.id} /><select name="status" defaultValue={defect.status} className="field"><option value="open">Aberto</option><option value="in_progress">Em andamento</option><option value="fixed">Corrigido</option><option value="retest">Reteste</option><option value="closed">Fechado</option><option value="reopened">Reaberto</option><option value="rejected">Rejeitado</option></select><input name="comment" placeholder="Comentário da transição" className="field" /><button className="inline-flex h-8 items-center justify-center gap-1 rounded border border-neon/20 text-xs text-neon"><CheckCircle2 className="size-3" />Atualizar</button></form></details>)}</div>{!defects?.length && <p className="mt-4 text-xs text-[#69737E]">Nenhum defeito registrado.</p>}</section>
    </aside></div>
  </div>;
}

function GuestExecution({ projectId }: { projectId: string }) {
  return <main className="mx-auto max-w-5xl px-5 py-12">
    <Link href="/lab/execution" className="text-xs text-[#8B949E]"><ArrowLeft className="mr-1 inline size-3" />Execution Hub</Link>
    <p className="mt-8 text-xs font-bold uppercase tracking-[.2em] text-mint">Produto 03 · demonstração</p>
    <h1 className="mt-3 text-4xl font-black text-off-white">Projeto {projectId}</h1>
    <p className="mt-4 max-w-2xl leading-7 text-[#8B949E]">A rota está aberta. Crie casos no Test Design Studio para iniciar rodadas, registrar evidências e acompanhar defeitos aqui.</p>
    <section className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={ListChecks} label="Execuções" value={0} /><Metric icon={CheckCircle2} label="Aprovadas" value={0} tone="neon" /><Metric icon={CircleDot} label="Falhas" value={0} tone="coral" /><Metric icon={Bug} label="Defeitos abertos" value={0} tone="coral" /></section>
  </main>;
}

function Metric({ icon: Icon, label, value, tone = "mint" }: { icon: typeof Bug; label: string; value: number; tone?: "mint" | "neon" | "coral" }) { const color = tone === "coral" ? "text-coral" : tone === "neon" ? "text-neon" : "text-mint"; return <div className="rounded-xl border border-white/10 bg-[#171B21] p-4"><Icon className={`size-4 ${color}`} /><p className="mt-4 text-2xl font-black text-off-white">{value}</p><p className="mt-1 text-xs text-[#69737E]">{label}</p></div>; }
